#if 0
* hhh-vars.h
* variable declarations
* generated by FormCalc 7.5 on 27-Sep-2012 9:11
* this file is part of FeynHiggs
#endif

#ifndef VARS_H
#define VARS_H

#include "externals.h"
#include "types.h"
#include "debug.h"

#else

#include "Decay.h"
#include "hhh-renconst.h"

	ComplexType Sub1, Sub2, Sub3, Sub4, Sub5, Sub6, Sub7
	common /hhh_abbrev0s/ Sub1, Sub2, Sub3, Sub4, Sub5, Sub6, Sub7

	ComplexType Sub10, Sub100, Sub101, Sub102, Sub103, Sub104
	ComplexType Sub105, Sub106, Sub107, Sub108, Sub109, Sub11
	ComplexType Sub110, Sub111, Sub112, Sub113, Sub114, Sub115
	ComplexType Sub116, Sub117, Sub118, Sub119, Sub12, Sub120
	ComplexType Sub121, Sub122, Sub123, Sub124, Sub125, Sub126
	ComplexType Sub127, Sub128, Sub129, Sub13, Sub130, Sub131
	ComplexType Sub132, Sub133, Sub134, Sub135, Sub136, Sub137
	ComplexType Sub138, Sub139, Sub14, Sub140, Sub141, Sub142
	ComplexType Sub143, Sub144, Sub145, Sub146, Sub147, Sub148
	ComplexType Sub149, Sub15, Sub150, Sub151, Sub152, Sub153
	ComplexType Sub154, Sub155, Sub156, Sub157, Sub158, Sub159
	ComplexType Sub16, Sub160, Sub161, Sub162, Sub163, Sub164
	ComplexType Sub165, Sub166, Sub167, Sub168, Sub169, Sub17
	ComplexType Sub170, Sub171, Sub172, Sub173, Sub174, Sub175
	ComplexType Sub176, Sub177, Sub178, Sub179, Sub18, Sub180
	ComplexType Sub181, Sub182, Sub183, Sub184, Sub185, Sub186
	ComplexType Sub187, Sub188, Sub189, Sub19, Sub190, Sub191
	ComplexType Sub192, Sub193, Sub194, Sub195, Sub196, Sub197
	ComplexType Sub198, Sub199, Sub20, Sub200, Sub201, Sub202
	ComplexType Sub203, Sub204, Sub205, Sub206, Sub207, Sub208
	ComplexType Sub209, Sub21, Sub210, Sub211, Sub212, Sub213
	ComplexType Sub214, Sub215, Sub216, Sub217, Sub218, Sub219
	ComplexType Sub22, Sub220, Sub221, Sub222, Sub223, Sub224
	ComplexType Sub225, Sub226, Sub227, Sub228, Sub229, Sub23
	ComplexType Sub230, Sub231, Sub232, Sub233, Sub234, Sub235
	ComplexType Sub236, Sub237, Sub238, Sub239, Sub24, Sub240
	ComplexType Sub241, Sub242, Sub243, Sub244, Sub245, Sub246
	ComplexType Sub247, Sub248, Sub249, Sub25, Sub250, Sub251
	ComplexType Sub252, Sub253, Sub254, Sub255, Sub256, Sub257
	ComplexType Sub258, Sub259, Sub26, Sub260, Sub261, Sub262
	ComplexType Sub263, Sub264, Sub265, Sub266, Sub267, Sub268
	ComplexType Sub27, Sub28, Sub29, Sub30, Sub31, Sub32, Sub33
	ComplexType Sub331, Sub332, Sub333, Sub334, Sub335, Sub336
	ComplexType Sub337, Sub338, Sub339, Sub34, Sub340, Sub341
	ComplexType Sub342, Sub343, Sub344, Sub345, Sub346, Sub347
	ComplexType Sub348, Sub349, Sub35, Sub350, Sub351, Sub352
	ComplexType Sub353, Sub354, Sub355, Sub356, Sub357, Sub358
	ComplexType Sub359, Sub36, Sub360, Sub361, Sub366, Sub367
	ComplexType Sub368, Sub369, Sub37, Sub370, Sub371, Sub372
	ComplexType Sub373, Sub376, Sub377, Sub378, Sub379, Sub38
	ComplexType Sub380, Sub381, Sub382, Sub383, Sub39, Sub394
	ComplexType Sub40, Sub41, Sub42, Sub43, Sub44, Sub45, Sub46
	ComplexType Sub47, Sub48, Sub482, Sub49, Sub50, Sub51, Sub52
	ComplexType Sub53, Sub54, Sub55, Sub56, Sub57, Sub58, Sub59
	ComplexType Sub60, Sub603, Sub604, Sub606, Sub607, Sub609
	ComplexType Sub61, Sub614, Sub616, Sub617, Sub619, Sub62
	ComplexType Sub620, Sub63, Sub64, Sub65, Sub657, Sub66
	ComplexType Sub67, Sub68, Sub69, Sub70, Sub71, Sub72, Sub73
	ComplexType Sub74, Sub75, Sub76, Sub77, Sub78, Sub79, Sub8
	ComplexType Sub80, Sub81, Sub82, Sub83, Sub84, Sub85, Sub86
	ComplexType Sub87, Sub88, Sub89, Sub9, Sub90, Sub91, Sub92
	ComplexType Sub93, Sub94, Sub95, Sub96, Sub97, Sub98, Sub99
	ComplexType Sub269(4), Sub270(4), Sub271(4), Sub272(4)
	ComplexType Sub273(4,4), Sub274(4), Sub275(4), Sub276(4,4)
	ComplexType Sub277(4), Sub278(4), Sub279(4,4), Sub280(4,4)
	ComplexType Sub281(4), Sub282(4), Sub283(4), Sub284(4)
	ComplexType Sub285(4,4), Sub286(4), Sub287(4), Sub288(4,4)
	ComplexType Sub289(4), Sub290(4), Sub291(4,4), Sub292(4,4)
	ComplexType Sub293(4), Sub294(4), Sub295(4,4), Sub296(4)
	ComplexType Sub297(4), Sub298(4,4), Sub299(4), Sub300(4)
	ComplexType Sub301(4,4), Sub302(4,4), Sub303(4), Sub304(4)
	ComplexType Sub305(4,4), Sub306(4), Sub307(4), Sub308(4,4)
	ComplexType Sub309(4), Sub310(4), Sub311(4,4), Sub312(4,4)
	ComplexType Sub313(4,4), Sub314(4,4), Sub315(4,4)
	ComplexType Sub316(4,4), Sub317(4,4), Sub318(4,4)
	ComplexType Sub319(4,4), Sub320(4,4), Sub321(4,4,4)
	ComplexType Sub322(4,4,4), Sub323(4,4,4), Sub324(4,4,4)
	ComplexType Sub325(4,4,4), Sub326(4,4,4), Sub327(4)
	ComplexType Sub328(4,4,4), Sub329(4,4,4), Sub330(4,4,4)
	ComplexType Sub362(3), Sub363(3), Sub364(3), Sub365(3)
	ComplexType Sub374(3), Sub375(3), Sub384(3), Sub385(3)
	ComplexType Sub386(3), Sub387(3,2,2), Sub388(3), Sub389(3)
	ComplexType Sub390(3,2,2), Sub391(3), Sub392(3)
	ComplexType Sub393(3,2,2), Sub395(3), Sub396(3)
	ComplexType Sub397(3,2,2), Sub398(3,2,2), Sub399(3)
	ComplexType Sub400(3), Sub401(3,2), Sub402(3), Sub403(3)
	ComplexType Sub404(3,2), Sub405(3,2,2), Sub406(3), Sub407(3)
	ComplexType Sub408(3,2), Sub409(3), Sub410(3), Sub411(3,2)
	ComplexType Sub412(3,2,2), Sub413(3), Sub414(3)
	ComplexType Sub415(3,2,2), Sub416(3,2,2), Sub417(3,2,2)
	ComplexType Sub418(3), Sub419(3), Sub420(3,2,2), Sub421(3)
	ComplexType Sub422(3), Sub423(3,2,2), Sub424(3), Sub425(3)
	ComplexType Sub426(3,2,2), Sub427(3), Sub428(3)
	ComplexType Sub429(3,2,2), Sub430(3,2,2), Sub431(3)
	ComplexType Sub432(3), Sub433(3,2), Sub434(3), Sub435(3)
	ComplexType Sub436(3,2), Sub437(3,2,2), Sub438(3), Sub439(3)
	ComplexType Sub440(3,2), Sub441(3), Sub442(3), Sub443(3,2)
	ComplexType Sub444(3,2,2), Sub445(3), Sub446(3)
	ComplexType Sub447(3,2,2), Sub448(3,2,2), Sub449(3)
	ComplexType Sub450(3), Sub451(3,2,2), Sub452(3), Sub453(3)
	ComplexType Sub454(3,2,2), Sub455(3), Sub456(3)
	ComplexType Sub457(3,2,2), Sub458(3), Sub459(3)
	ComplexType Sub460(3,2,2), Sub461(3,2,2), Sub462(3)
	ComplexType Sub463(3), Sub464(3,2), Sub465(3), Sub466(3)
	ComplexType Sub467(3,2), Sub468(3,2,2), Sub469(3), Sub470(3)
	ComplexType Sub471(3,2), Sub472(3), Sub473(3), Sub474(3,2)
	ComplexType Sub475(3,2,2), Sub476(3), Sub477(3)
	ComplexType Sub478(3,2,2), Sub479(3,2,2), Sub480(3,2,2)
	ComplexType Sub481(3,2,2), Sub483(3,2,2), Sub484(3,2,2)
	ComplexType Sub485(3,2,2), Sub486(3,2,2), Sub487(3,2,2)
	ComplexType Sub488(3,2,2), Sub489(3,2,2), Sub490(3,2,2)
	ComplexType Sub491(3,2,2), Sub492(3,2,2), Sub493(3,2,2)
	ComplexType Sub494(3,2,2), Sub495(3,2,2), Sub496(3,2,2)
	ComplexType Sub497(3,2,2), Sub498(3), Sub499(3)
	ComplexType Sub500(3,2,2), Sub501(3,2,2), Sub502(3)
	ComplexType Sub503(3), Sub504(3,2,2), Sub505(3,2,2)
	ComplexType Sub506(3), Sub507(3), Sub508(3,2,2)
	ComplexType Sub509(3,2,2), Sub510(3,2,2), Sub511(3,2)
	ComplexType Sub512(3,2), Sub513(3,2,2), Sub514(3,2)
	ComplexType Sub515(3,2), Sub516(3,2,2), Sub517(3,2,2)
	ComplexType Sub518(3,2,2), Sub519(3,2,2), Sub520(3,2)
	ComplexType Sub521(3,2), Sub522(3,2,2), Sub523(3,2)
	ComplexType Sub524(3,2), Sub525(3,2,2), Sub526(3,2,2)
	ComplexType Sub527(3,2,2), Sub528(3,2,2), Sub529(3,2,2)
	ComplexType Sub530(3,2,2), Sub531(3,2,2), Sub532(3,2,2)
	ComplexType Sub533(3,2,2), Sub534(3,2,2), Sub535(3,2,2)
	ComplexType Sub536(3,2,2), Sub537(3,2,2), Sub538(3,2,2)
	ComplexType Sub539(3,2,2), Sub540(3,2,2), Sub541(3,2,2)
	ComplexType Sub542(3,2,2), Sub543(3,2,2), Sub544(3,2,2,2)
	ComplexType Sub545(3,2), Sub546(3,2), Sub547(3,2,2)
	ComplexType Sub548(3,2), Sub549(3,2), Sub550(3,2,2)
	ComplexType Sub551(3,2,2), Sub552(3,2,2), Sub553(3,2)
	ComplexType Sub554(3,2), Sub555(3,2,2), Sub556(3,2)
	ComplexType Sub557(3,2), Sub558(3,2,2), Sub559(3,2,2)
	ComplexType Sub560(3,2,2), Sub561(3,2,2), Sub562(3,2,2)
	ComplexType Sub563(3,2,2), Sub564(3,2,2), Sub565(3,2,2)
	ComplexType Sub566(3,2,2), Sub567(3,2,2), Sub568(3,2,2)
	ComplexType Sub569(3,2,2), Sub570(3,2,2), Sub571(3,2,2)
	ComplexType Sub572(3,2,2), Sub573(3,2,2,2), Sub574(3,2)
	ComplexType Sub575(3,2), Sub576(3,2,2), Sub577(3,2)
	ComplexType Sub578(3,2), Sub579(3,2,2), Sub580(3,2,2)
	ComplexType Sub581(3,2,2), Sub582(3,2), Sub583(3,2)
	ComplexType Sub584(3,2,2), Sub585(3,2), Sub586(3,2)
	ComplexType Sub587(3,2,2), Sub588(3,2,2), Sub589(3,2,2)
	ComplexType Sub590(3,2,2), Sub591(3,2,2), Sub592(3,2,2)
	ComplexType Sub593(3,2,2), Sub594(3,2,2), Sub595(3,2,2)
	ComplexType Sub596(3,2,2), Sub597(3,2,2), Sub598(3,2,2)
	ComplexType Sub599(3,2,2), Sub600(3,2,2), Sub601(3,2,2)
	ComplexType Sub602(3,2,2,2), Sub605(2,2), Sub608(2,2)
	ComplexType Sub610(2,2), Sub611(2,2), Sub612(2,2)
	ComplexType Sub613(2,2), Sub615(2,2), Sub618(2,2)
	ComplexType Sub621(2,2), Sub622(2,2), Sub623(2,2)
	ComplexType Sub624(2,2), Sub625(2,2,2), Sub626(2,2,2)
	ComplexType Sub627(2,2,2), Sub628(2,2,2), Sub629(2,2,2)
	ComplexType Sub630(2,2,2), Sub631(2,2,2), Sub632(2)
	ComplexType Sub633(2,2,2), Sub634(2,2,2), Sub635(2,2,2)
	ComplexType Sub636(4), Sub637(4), Sub638(4,4), Sub639(4)
	ComplexType Sub640(4), Sub641(4,4), Sub642(4,4), Sub643(4,4)
	ComplexType Sub644(4,4), Sub645(4,4), Sub646(4,4)
	ComplexType Sub647(4,4), Sub648(4,4), Sub649(4,4)
	ComplexType Sub650(4,4), Sub651(4,4), Sub652(3,2)
	ComplexType Sub653(3,2), Sub654(3,2), Sub655(2,2)
	ComplexType Sub656(2,2), Sub658(2,2), Sub659(2,2)
	ComplexType Sub660(2,2), Sub661(2,2), Sub662(2,2)
	ComplexType Sub663(2,2), Sub664(2,2), Sub665(2,2)
	ComplexType Sub666(2,2), Sub667(2,2), Sub668(2,2)
	common /hhh_abbrev1s/ Sub10, Sub100, Sub101, Sub102, Sub103
	common /hhh_abbrev1s/ Sub104, Sub105, Sub106, Sub107, Sub108
	common /hhh_abbrev1s/ Sub109, Sub11, Sub110, Sub111, Sub112
	common /hhh_abbrev1s/ Sub113, Sub114, Sub115, Sub116, Sub117
	common /hhh_abbrev1s/ Sub118, Sub119, Sub12, Sub120, Sub121
	common /hhh_abbrev1s/ Sub122, Sub123, Sub124, Sub125, Sub126
	common /hhh_abbrev1s/ Sub127, Sub128, Sub129, Sub13, Sub130
	common /hhh_abbrev1s/ Sub131, Sub132, Sub133, Sub134, Sub135
	common /hhh_abbrev1s/ Sub136, Sub137, Sub138, Sub139, Sub14
	common /hhh_abbrev1s/ Sub140, Sub141, Sub142, Sub143, Sub144
	common /hhh_abbrev1s/ Sub145, Sub146, Sub147, Sub148, Sub149
	common /hhh_abbrev1s/ Sub15, Sub150, Sub151, Sub152, Sub153
	common /hhh_abbrev1s/ Sub154, Sub155, Sub156, Sub157, Sub158
	common /hhh_abbrev1s/ Sub159, Sub16, Sub160, Sub161, Sub162
	common /hhh_abbrev1s/ Sub163, Sub164, Sub165, Sub166, Sub167
	common /hhh_abbrev1s/ Sub168, Sub169, Sub17, Sub170, Sub171
	common /hhh_abbrev1s/ Sub172, Sub173, Sub174, Sub175, Sub176
	common /hhh_abbrev1s/ Sub177, Sub178, Sub179, Sub18, Sub180
	common /hhh_abbrev1s/ Sub181, Sub182, Sub183, Sub184, Sub185
	common /hhh_abbrev1s/ Sub186, Sub187, Sub188, Sub189, Sub19
	common /hhh_abbrev1s/ Sub190, Sub191, Sub192, Sub193, Sub194
	common /hhh_abbrev1s/ Sub195, Sub196, Sub197, Sub198, Sub199
	common /hhh_abbrev1s/ Sub20, Sub200, Sub201, Sub202, Sub203
	common /hhh_abbrev1s/ Sub204, Sub205, Sub206, Sub207, Sub208
	common /hhh_abbrev1s/ Sub209, Sub21, Sub210, Sub211, Sub212
	common /hhh_abbrev1s/ Sub213, Sub214, Sub215, Sub216, Sub217
	common /hhh_abbrev1s/ Sub218, Sub219, Sub22, Sub220, Sub221
	common /hhh_abbrev1s/ Sub222, Sub223, Sub224, Sub225, Sub226
	common /hhh_abbrev1s/ Sub227, Sub228, Sub229, Sub23, Sub230
	common /hhh_abbrev1s/ Sub231, Sub232, Sub233, Sub234, Sub235
	common /hhh_abbrev1s/ Sub236, Sub237, Sub238, Sub239, Sub24
	common /hhh_abbrev1s/ Sub240, Sub241, Sub242, Sub243, Sub244
	common /hhh_abbrev1s/ Sub245, Sub246, Sub247, Sub248, Sub249
	common /hhh_abbrev1s/ Sub25, Sub250, Sub251, Sub252, Sub253
	common /hhh_abbrev1s/ Sub254, Sub255, Sub256, Sub257, Sub258
	common /hhh_abbrev1s/ Sub259, Sub26, Sub260, Sub261, Sub262
	common /hhh_abbrev1s/ Sub263, Sub264, Sub265, Sub266, Sub267
	common /hhh_abbrev1s/ Sub268, Sub27, Sub28, Sub29, Sub30
	common /hhh_abbrev1s/ Sub31, Sub32, Sub33, Sub331, Sub332
	common /hhh_abbrev1s/ Sub333, Sub334, Sub335, Sub336, Sub337
	common /hhh_abbrev1s/ Sub338, Sub339, Sub34, Sub340, Sub341
	common /hhh_abbrev1s/ Sub342, Sub343, Sub344, Sub345, Sub346
	common /hhh_abbrev1s/ Sub347, Sub348, Sub349, Sub35, Sub350
	common /hhh_abbrev1s/ Sub351, Sub352, Sub353, Sub354, Sub355
	common /hhh_abbrev1s/ Sub356, Sub357, Sub358, Sub359, Sub36
	common /hhh_abbrev1s/ Sub360, Sub361, Sub366, Sub367, Sub368
	common /hhh_abbrev1s/ Sub369, Sub37, Sub370, Sub371, Sub372
	common /hhh_abbrev1s/ Sub373, Sub376, Sub377, Sub378, Sub379
	common /hhh_abbrev1s/ Sub38, Sub380, Sub381, Sub382, Sub383
	common /hhh_abbrev1s/ Sub39, Sub394, Sub40, Sub41, Sub42
	common /hhh_abbrev1s/ Sub43, Sub44, Sub45, Sub46, Sub47
	common /hhh_abbrev1s/ Sub48, Sub482, Sub49, Sub50, Sub51
	common /hhh_abbrev1s/ Sub52, Sub53, Sub54, Sub55, Sub56
	common /hhh_abbrev1s/ Sub57, Sub58, Sub59, Sub60, Sub603
	common /hhh_abbrev1s/ Sub604, Sub606, Sub607, Sub609, Sub61
	common /hhh_abbrev1s/ Sub614, Sub616, Sub617, Sub619, Sub62
	common /hhh_abbrev1s/ Sub620, Sub63, Sub64, Sub65, Sub657
	common /hhh_abbrev1s/ Sub66, Sub67, Sub68, Sub69, Sub70
	common /hhh_abbrev1s/ Sub71, Sub72, Sub73, Sub74, Sub75
	common /hhh_abbrev1s/ Sub76, Sub77, Sub78, Sub79, Sub8
	common /hhh_abbrev1s/ Sub80, Sub81, Sub82, Sub83, Sub84
	common /hhh_abbrev1s/ Sub85, Sub86, Sub87, Sub88, Sub89
	common /hhh_abbrev1s/ Sub9, Sub90, Sub91, Sub92, Sub93
	common /hhh_abbrev1s/ Sub94, Sub95, Sub96, Sub97, Sub98
	common /hhh_abbrev1s/ Sub99, Sub269, Sub270, Sub271, Sub272
	common /hhh_abbrev1s/ Sub273, Sub274, Sub275, Sub276, Sub277
	common /hhh_abbrev1s/ Sub278, Sub279, Sub280, Sub281, Sub282
	common /hhh_abbrev1s/ Sub283, Sub284, Sub285, Sub286, Sub287
	common /hhh_abbrev1s/ Sub288, Sub289, Sub290, Sub291, Sub292
	common /hhh_abbrev1s/ Sub293, Sub294, Sub295, Sub296, Sub297
	common /hhh_abbrev1s/ Sub298, Sub299, Sub300, Sub301, Sub302
	common /hhh_abbrev1s/ Sub303, Sub304, Sub305, Sub306, Sub307
	common /hhh_abbrev1s/ Sub308, Sub309, Sub310, Sub311, Sub312
	common /hhh_abbrev1s/ Sub313, Sub314, Sub315, Sub316, Sub317
	common /hhh_abbrev1s/ Sub318, Sub319, Sub320, Sub321, Sub322
	common /hhh_abbrev1s/ Sub323, Sub324, Sub325, Sub326, Sub327
	common /hhh_abbrev1s/ Sub328, Sub329, Sub330, Sub362, Sub363
	common /hhh_abbrev1s/ Sub364, Sub365, Sub374, Sub375, Sub384
	common /hhh_abbrev1s/ Sub385, Sub386, Sub387, Sub388, Sub389
	common /hhh_abbrev1s/ Sub390, Sub391, Sub392, Sub393, Sub395
	common /hhh_abbrev1s/ Sub396, Sub397, Sub398, Sub399, Sub400
	common /hhh_abbrev1s/ Sub401, Sub402, Sub403, Sub404, Sub405
	common /hhh_abbrev1s/ Sub406, Sub407, Sub408, Sub409, Sub410
	common /hhh_abbrev1s/ Sub411, Sub412, Sub413, Sub414, Sub415
	common /hhh_abbrev1s/ Sub416, Sub417, Sub418, Sub419, Sub420
	common /hhh_abbrev1s/ Sub421, Sub422, Sub423, Sub424, Sub425
	common /hhh_abbrev1s/ Sub426, Sub427, Sub428, Sub429, Sub430
	common /hhh_abbrev1s/ Sub431, Sub432, Sub433, Sub434, Sub435
	common /hhh_abbrev1s/ Sub436, Sub437, Sub438, Sub439, Sub440
	common /hhh_abbrev1s/ Sub441, Sub442, Sub443, Sub444, Sub445
	common /hhh_abbrev1s/ Sub446, Sub447, Sub448, Sub449, Sub450
	common /hhh_abbrev1s/ Sub451, Sub452, Sub453, Sub454, Sub455
	common /hhh_abbrev1s/ Sub456, Sub457, Sub458, Sub459, Sub460
	common /hhh_abbrev1s/ Sub461, Sub462, Sub463, Sub464, Sub465
	common /hhh_abbrev1s/ Sub466, Sub467, Sub468, Sub469, Sub470
	common /hhh_abbrev1s/ Sub471, Sub472, Sub473, Sub474, Sub475
	common /hhh_abbrev1s/ Sub476, Sub477, Sub478, Sub479, Sub480
	common /hhh_abbrev1s/ Sub481, Sub483, Sub484, Sub485, Sub486
	common /hhh_abbrev1s/ Sub487, Sub488, Sub489, Sub490, Sub491
	common /hhh_abbrev1s/ Sub492, Sub493, Sub494, Sub495, Sub496
	common /hhh_abbrev1s/ Sub497, Sub498, Sub499, Sub500, Sub501
	common /hhh_abbrev1s/ Sub502, Sub503, Sub504, Sub505, Sub506
	common /hhh_abbrev1s/ Sub507, Sub508, Sub509, Sub510, Sub511
	common /hhh_abbrev1s/ Sub512, Sub513, Sub514, Sub515, Sub516
	common /hhh_abbrev1s/ Sub517, Sub518, Sub519, Sub520, Sub521
	common /hhh_abbrev1s/ Sub522, Sub523, Sub524, Sub525, Sub526
	common /hhh_abbrev1s/ Sub527, Sub528, Sub529, Sub530, Sub531
	common /hhh_abbrev1s/ Sub532, Sub533, Sub534, Sub535, Sub536
	common /hhh_abbrev1s/ Sub537, Sub538, Sub539, Sub540, Sub541
	common /hhh_abbrev1s/ Sub542, Sub543, Sub544, Sub545, Sub546
	common /hhh_abbrev1s/ Sub547, Sub548, Sub549, Sub550, Sub551
	common /hhh_abbrev1s/ Sub552, Sub553, Sub554, Sub555, Sub556
	common /hhh_abbrev1s/ Sub557, Sub558, Sub559, Sub560, Sub561
	common /hhh_abbrev1s/ Sub562, Sub563, Sub564, Sub565, Sub566
	common /hhh_abbrev1s/ Sub567, Sub568, Sub569, Sub570, Sub571
	common /hhh_abbrev1s/ Sub572, Sub573, Sub574, Sub575, Sub576
	common /hhh_abbrev1s/ Sub577, Sub578, Sub579, Sub580, Sub581
	common /hhh_abbrev1s/ Sub582, Sub583, Sub584, Sub585, Sub586
	common /hhh_abbrev1s/ Sub587, Sub588, Sub589, Sub590, Sub591
	common /hhh_abbrev1s/ Sub592, Sub593, Sub594, Sub595, Sub596
	common /hhh_abbrev1s/ Sub597, Sub598, Sub599, Sub600, Sub601
	common /hhh_abbrev1s/ Sub602, Sub605, Sub608, Sub610, Sub611
	common /hhh_abbrev1s/ Sub612, Sub613, Sub615, Sub618, Sub621
	common /hhh_abbrev1s/ Sub622, Sub623, Sub624, Sub625, Sub626
	common /hhh_abbrev1s/ Sub627, Sub628, Sub629, Sub630, Sub631
	common /hhh_abbrev1s/ Sub632, Sub633, Sub634, Sub635, Sub636
	common /hhh_abbrev1s/ Sub637, Sub638, Sub639, Sub640, Sub641
	common /hhh_abbrev1s/ Sub642, Sub643, Sub644, Sub645, Sub646
	common /hhh_abbrev1s/ Sub647, Sub648, Sub649, Sub650, Sub651
	common /hhh_abbrev1s/ Sub652, Sub653, Sub654, Sub655, Sub656
	common /hhh_abbrev1s/ Sub658, Sub659, Sub660, Sub661, Sub662
	common /hhh_abbrev1s/ Sub663, Sub664, Sub665, Sub666, Sub667
	common /hhh_abbrev1s/ Sub668

	ComplexType lint1, lint139, lint140, lint153, lint158
	ComplexType lint159, lint160, lint161, lint162, lint165
	ComplexType lint166, lint167, lint168, lint169, lint170
	ComplexType lint172, lint173, lint174, lint175, lint2
	ComplexType lint24, lint25, lint26, lint27, lint28, lint29
	ComplexType lint3, lint30, lint31, lint32, lint33, lint34
	ComplexType lint35, lint36, lint37, lint38, lint39, lint4
	ComplexType lint40, lint41, lint42, lint43, lint46, lint47
	ComplexType lint5, lint6, lint65, lint7, lint8, lint80
	ComplexType lint92, lint10(Ncc), lint100(Ncc), lint101(Ncc)
	ComplexType lint102(Ncc), lint103(Ncc), lint104(Ncc)
	ComplexType lint105(Ncc), lint106(Ncc), lint107(Ncc)
	ComplexType lint108(Ncc), lint109(Ncc), lint11(Ncc)
	ComplexType lint110(Ncc), lint111(Ncc), lint112(Ncc)
	ComplexType lint113(Ncc), lint114(Ncc), lint115(Ncc)
	ComplexType lint116(Ncc), lint117(Ncc), lint118(Ncc)
	ComplexType lint119(Ncc), lint12(Ncc), lint120(Ncc)
	ComplexType lint121(Ncc), lint122(Ncc), lint123(Ncc)
	ComplexType lint124(Ncc), lint125(Ncc), lint126(Ncc)
	ComplexType lint127(Ncc), lint128(Ncc), lint129(Ncc)
	ComplexType lint13(Ncc), lint130(Ncc), lint131(Ncc)
	ComplexType lint132(Ncc), lint133(Ncc), lint134(Ncc)
	ComplexType lint135(Ncc), lint136(Ncc), lint137(Ncc)
	ComplexType lint138(Ncc), lint14(Ncc), lint141(Ncc)
	ComplexType lint142(Ncc), lint143(Ncc), lint144(Ncc)
	ComplexType lint145(Ncc), lint146(Ncc), lint147(Ncc)
	ComplexType lint148(Ncc), lint149(Ncc), lint15(Ncc)
	ComplexType lint150(Ncc), lint151(Ncc), lint152(Ncc)
	ComplexType lint154(Ncc), lint155(Ncc), lint156(Ncc)
	ComplexType lint157(Ncc), lint16(Ncc), lint163(Ncc)
	ComplexType lint164(Ncc), lint17(Ncc), lint171(Ncc)
	ComplexType lint176(4,4), lint177(Ncc,4,4,4), lint178(3)
	ComplexType lint179(3), lint18(Ncc), lint180(3)
	ComplexType lint181(Ncc,3), lint182(3), lint183(Ncc,3)
	ComplexType lint184(3), lint185(Ncc,3), lint186(3)
	ComplexType lint187(Ncc,3), lint188(3,2,2), lint189(3,2,2)
	ComplexType lint19(Ncc), lint190(3,2,2), lint191(3,2,2)
	ComplexType lint192(3,2,2), lint193(3,2,2), lint194(3,2,2)
	ComplexType lint195(3,2,2), lint196(3,2,2)
	ComplexType lint197(Ncc,3,2,2,2), lint198(Ncc,3,2,2,2)
	ComplexType lint199(Ncc,3,2,2,2), lint20(Ncc), lint200(2,2)
	ComplexType lint201(Ncc,2,2,2), lint202(4), lint203(4,4)
	ComplexType lint204(4,4), lint205(3,2), lint206(3,2)
	ComplexType lint207(3,2), lint208(2), lint209(2,2)
	ComplexType lint21(Ncc), lint210(2,2), lint211(3,2,2)
	ComplexType lint212(3,2,2), lint213(3,2,2), lint214(3)
	ComplexType lint215(3), lint216(3), lint217(3), lint218(3)
	ComplexType lint219(3), lint22(Ncc), lint220(3), lint221(3)
	ComplexType lint222(3), lint223(3), lint224(3), lint23(Ncc)
	ComplexType lint44(Ncc), lint45(Ncc), lint48(Ncc)
	ComplexType lint49(Ncc), lint50(Ncc), lint51(Ncc)
	ComplexType lint52(Ncc), lint53(Ncc), lint54(Ncc)
	ComplexType lint55(Ncc), lint56(Ncc), lint57(Ncc)
	ComplexType lint58(Ncc), lint59(Ncc), lint60(Ncc)
	ComplexType lint61(Ncc), lint62(Ncc), lint63(Ncc)
	ComplexType lint64(Ncc), lint66(Ncc), lint67(Ncc)
	ComplexType lint68(Ncc), lint69(Ncc), lint70(Ncc)
	ComplexType lint71(Ncc), lint72(Ncc), lint73(Ncc)
	ComplexType lint74(Ncc), lint75(Ncc), lint76(Ncc)
	ComplexType lint77(Ncc), lint78(Ncc), lint79(Ncc)
	ComplexType lint81(Ncc), lint82(Ncc), lint83(Ncc)
	ComplexType lint84(Ncc), lint85(Ncc), lint86(Ncc)
	ComplexType lint87(Ncc), lint88(Ncc), lint89(Ncc)
	ComplexType lint9(Ncc), lint90(Ncc), lint91(Ncc)
	ComplexType lint93(Ncc), lint94(Ncc), lint95(Ncc)
	ComplexType lint96(Ncc), lint97(Ncc), lint98(Ncc)
	ComplexType lint99(Ncc)
	common /hhh_loopint1s/ lint1, lint139, lint140, lint153
	common /hhh_loopint1s/ lint158, lint159, lint160, lint161
	common /hhh_loopint1s/ lint162, lint165, lint166, lint167
	common /hhh_loopint1s/ lint168, lint169, lint170, lint172
	common /hhh_loopint1s/ lint173, lint174, lint175, lint2
	common /hhh_loopint1s/ lint24, lint25, lint26, lint27
	common /hhh_loopint1s/ lint28, lint29, lint3, lint30, lint31
	common /hhh_loopint1s/ lint32, lint33, lint34, lint35
	common /hhh_loopint1s/ lint36, lint37, lint38, lint39, lint4
	common /hhh_loopint1s/ lint40, lint41, lint42, lint43
	common /hhh_loopint1s/ lint46, lint47, lint5, lint6, lint65
	common /hhh_loopint1s/ lint7, lint8, lint80, lint92, lint10
	common /hhh_loopint1s/ lint100, lint101, lint102, lint103
	common /hhh_loopint1s/ lint104, lint105, lint106, lint107
	common /hhh_loopint1s/ lint108, lint109, lint11, lint110
	common /hhh_loopint1s/ lint111, lint112, lint113, lint114
	common /hhh_loopint1s/ lint115, lint116, lint117, lint118
	common /hhh_loopint1s/ lint119, lint12, lint120, lint121
	common /hhh_loopint1s/ lint122, lint123, lint124, lint125
	common /hhh_loopint1s/ lint126, lint127, lint128, lint129
	common /hhh_loopint1s/ lint13, lint130, lint131, lint132
	common /hhh_loopint1s/ lint133, lint134, lint135, lint136
	common /hhh_loopint1s/ lint137, lint138, lint14, lint141
	common /hhh_loopint1s/ lint142, lint143, lint144, lint145
	common /hhh_loopint1s/ lint146, lint147, lint148, lint149
	common /hhh_loopint1s/ lint15, lint150, lint151, lint152
	common /hhh_loopint1s/ lint154, lint155, lint156, lint157
	common /hhh_loopint1s/ lint16, lint163, lint164, lint17
	common /hhh_loopint1s/ lint171, lint176, lint177, lint178
	common /hhh_loopint1s/ lint179, lint18, lint180, lint181
	common /hhh_loopint1s/ lint182, lint183, lint184, lint185
	common /hhh_loopint1s/ lint186, lint187, lint188, lint189
	common /hhh_loopint1s/ lint19, lint190, lint191, lint192
	common /hhh_loopint1s/ lint193, lint194, lint195, lint196
	common /hhh_loopint1s/ lint197, lint198, lint199, lint20
	common /hhh_loopint1s/ lint200, lint201, lint202, lint203
	common /hhh_loopint1s/ lint204, lint205, lint206, lint207
	common /hhh_loopint1s/ lint208, lint209, lint21, lint210
	common /hhh_loopint1s/ lint211, lint212, lint213, lint214
	common /hhh_loopint1s/ lint215, lint216, lint217, lint218
	common /hhh_loopint1s/ lint219, lint22, lint220, lint221
	common /hhh_loopint1s/ lint222, lint223, lint224, lint23
	common /hhh_loopint1s/ lint44, lint45, lint48, lint49
	common /hhh_loopint1s/ lint50, lint51, lint52, lint53
	common /hhh_loopint1s/ lint54, lint55, lint56, lint57
	common /hhh_loopint1s/ lint58, lint59, lint60, lint61
	common /hhh_loopint1s/ lint62, lint63, lint64, lint66
	common /hhh_loopint1s/ lint67, lint68, lint69, lint70
	common /hhh_loopint1s/ lint71, lint72, lint73, lint74
	common /hhh_loopint1s/ lint75, lint76, lint77, lint78
	common /hhh_loopint1s/ lint79, lint81, lint82, lint83
	common /hhh_loopint1s/ lint84, lint85, lint86, lint87
	common /hhh_loopint1s/ lint88, lint89, lint9, lint90, lint91
	common /hhh_loopint1s/ lint93, lint94, lint95, lint96
	common /hhh_loopint1s/ lint97, lint98, lint99

	integer seq(2), Hel(3)
	common /hhh_helvars/ seq, Hel

	integer Cha4, Cha5, Cha6, Gen4, Neu4, Neu5, Neu6, Sfe4, Sfe5
	integer Sfe6
	common /hhh_indices/ Cha4, Cha5, Cha6, Gen4, Neu4, Neu5, Neu6
	common /hhh_indices/ Sfe4, Sfe5, Sfe6

	ComplexType Ctree(1), Cloop(1)
	common /hhh_formfactors/ Ctree, Cloop

#endif
