#if 0
* hgaga-vars.h
* variable declarations
* generated by FormCalc 7.5 on 27-Sep-2012 9:09
* this file is part of FeynHiggs
#endif

#ifndef VARS_H
#define VARS_H

#include "externals.h"
#include "types.h"
#include "debug.h"

#else

#include "Decay.h"

	ComplexType Sub1, Sub11, Sub2, Sub3, Sub36, Sub37, Sub38
	ComplexType Sub39, Sub7, Sub10(3), Sub12(3), Sub16(3)
	ComplexType Sub17(3), Sub18(3,2), Sub19(3), Sub20(3)
	ComplexType Sub21(3,2), Sub22(3,2), Sub23(3), Sub24(3)
	ComplexType Sub25(3,2), Sub26(3), Sub27(3), Sub28(3,2)
	ComplexType Sub29(3,2), Sub30(3), Sub31(3), Sub32(3,2)
	ComplexType Sub33(3,2), Sub34(3,2), Sub35(3,2), Sub40(2)
	ComplexType Sub41(2), Sub42(2), Sub45(6), Sub46(3)
	ComplexType Sub47(3,3), Sub48(6,3,3), Sub49(3), Sub50(6,3,3)
	ComplexType Sub51(6,3,3), Sub52(6,3,3), Sub53(3), Sub54(3,3)
	ComplexType Sub55(6,3,3), Sub56(3), Sub57(6,3,3)
	ComplexType Sub58(6,3,3), Sub59(6,3,3), Sub60(3,3)
	ComplexType Sub61(3,3), Sub62(6,3,3), Sub63(6,3,3), Sub64(6)
	ComplexType Sub65(3), Sub66(3,3), Sub67(6,3,3), Sub68(3)
	ComplexType Sub69(6,3,3), Sub70(6,3,3), Sub71(6,3,3)
	ComplexType Sub72(3), Sub73(3,3), Sub74(6,3,3), Sub75(3)
	ComplexType Sub76(6,3,3), Sub77(6,3,3), Sub78(6,3,3)
	ComplexType Sub79(3,3), Sub80(3,3), Sub81(6,3,3)
	ComplexType Sub82(6,3,3), Sub9(3)
	common /hgaga_abbrev1s/ Sub1, Sub11, Sub2, Sub3, Sub36, Sub37
	common /hgaga_abbrev1s/ Sub38, Sub39, Sub7, Sub10, Sub12
	common /hgaga_abbrev1s/ Sub16, Sub17, Sub18, Sub19, Sub20
	common /hgaga_abbrev1s/ Sub21, Sub22, Sub23, Sub24, Sub25
	common /hgaga_abbrev1s/ Sub26, Sub27, Sub28, Sub29, Sub30
	common /hgaga_abbrev1s/ Sub31, Sub32, Sub33, Sub34, Sub35
	common /hgaga_abbrev1s/ Sub40, Sub41, Sub42, Sub45, Sub46
	common /hgaga_abbrev1s/ Sub47, Sub48, Sub49, Sub50, Sub51
	common /hgaga_abbrev1s/ Sub52, Sub53, Sub54, Sub55, Sub56
	common /hgaga_abbrev1s/ Sub57, Sub58, Sub59, Sub60, Sub61
	common /hgaga_abbrev1s/ Sub62, Sub63, Sub64, Sub65, Sub66
	common /hgaga_abbrev1s/ Sub67, Sub68, Sub69, Sub70, Sub71
	common /hgaga_abbrev1s/ Sub72, Sub73, Sub74, Sub75, Sub76
	common /hgaga_abbrev1s/ Sub77, Sub78, Sub79, Sub80, Sub81
	common /hgaga_abbrev1s/ Sub82, Sub9

	ComplexType Abb1, Abb2, Abb3, AbbSum1, AbbSum2, Eps1, Pair1
	ComplexType Pair2, Pair3, Pair4, Pair5, Sub13, Sub14, Sub15
	ComplexType Sub4, Sub5, Sub6, Sub8, Sub43(2), Sub44(2)
	common /hgaga_abbrev1hel/ Abb1, Abb2, Abb3, AbbSum1, AbbSum2
	common /hgaga_abbrev1hel/ Eps1, Pair1, Pair2, Pair3, Pair4
	common /hgaga_abbrev1hel/ Pair5, Sub13, Sub14, Sub15, Sub4
	common /hgaga_abbrev1hel/ Sub5, Sub6, Sub8, Sub43, Sub44

	ComplexType lint2, lint3, lint4, lint6, lint1(Ncc)
	ComplexType lint10(Ncc,3), lint11(3), lint12(Ncc,3)
	ComplexType lint13(3,2), lint14(Ncc,3,2), lint15(2)
	ComplexType lint16(Ncc,2), lint17(6), lint18(Ncc,6)
	ComplexType lint19(6), lint20(Ncc,6), lint5(Ncc), lint7(3)
	ComplexType lint8(Ncc,3), lint9(3)
	common /hgaga_loopint1s/ lint2, lint3, lint4, lint6, lint1
	common /hgaga_loopint1s/ lint10, lint11, lint12, lint13
	common /hgaga_loopint1s/ lint14, lint15, lint16, lint17
	common /hgaga_loopint1s/ lint18, lint19, lint20, lint5
	common /hgaga_loopint1s/ lint7, lint8, lint9

	integer seq(2), Hel(3)
	common /hgaga_helvars/ seq, Hel

	integer All4, Cha4, Gen4, Ind1, Ind2, Sfe4
	common /hgaga_indices/ All4, Cha4, Gen4, Ind1, Ind2, Sfe4

	ComplexType Cloop(1)
	common /hgaga_formfactors/ Cloop

#endif
