CDECK  ID>, SETCON.
      SUBROUTINE SETCON
C          THIS SUBROUTINE SETS THE CONSTANTS IN /CONST/.
      COMMON/ITAPES/ITDKY,ITEVT,ITCOM,ITLIS
      SAVE /ITAPES/
      INTEGER   ITDKY,ITEVT,ITCOM,ITLIS
      COMMON/CONST/PI,SQRT2,ALFA,GF,UNITS
      SAVE /CONST/
      REAL      PI,SQRT2,ALFA,GF,UNITS
      PI=4.*ATAN(1.)
      SQRT2=SQRT(2.)
      ALFA=1./137.036
      GF=1.16570E-5
      UNITS=1./2.56815
      RETURN
      END
