CDECK  ID>, SSA0.
      DOUBLE PRECISION FUNCTION SSA0(M)
      IMPLICIT NONE
      COMMON/SSINF/XLAM
      DOUBLE PRECISION XLAM
      REAL M
      DOUBLE PRECISION MSQ
      MSQ=M**2
      IF(M.NE.0.) THEN
        SSA0=MSQ*(1.D0-DLOG(MSQ)+XLAM)
      ELSE
        SSA0=0.D0
      ENDIF
      RETURN
      END
