CDECK  ID>, SSB00.
      DOUBLE PRECISION FUNCTION SSB00(M1,M2)
      IMPLICIT NONE
      COMMON/SSINF/XLAM
      DOUBLE PRECISION XLAM
      REAL M1,M2
      DOUBLE PRECISION M1SQ,M2SQ,MCAP,MREG
      M1SQ=M1*M1
      M2SQ=M2*M2
      IF(M1SQ.GT.M2SQ) THEN
        MCAP=M1SQ
        MREG=M2SQ
      ELSE
        MCAP=M2SQ
        MREG=M1SQ
      ENDIF
      IF(M1.NE.M2) THEN
        SSB00=1.+XLAM-DLOG(MCAP)+MREG/(MREG-MCAP)
     $*DLOG(MCAP/MREG)
      ELSE
        SSB00=XLAM-DLOG(M1SQ)
      ENDIF
      IF(MREG.EQ.0) THEN
        SSB00=1.D0+XLAM-DLOG(MCAP)
      ENDIF
      IF(MCAP.EQ.0) THEN
        SSB00=1.D0+XLAM-DLOG(MREG)
      ENDIF
C      IF(M1.NE.M2) THEN
C        SSB00=1.+XLAM-DLOG(M2SQ)+M1SQ/(M1SQ-M2SQ)
C     $*DLOG(M2SQ/M1SQ)
C      ELSE
C        SSB00=XLAM-DLOG(M2SQ)
C      ENDIF
C      IF(M1.EQ.0) THEN
C        SSB00=1.D0+XLAM-DLOG(M2SQ)
C      ENDIF
C      IF(M2.EQ.0) THEN
C        SSB00=1.D0+XLAM-DLOG(M1SQ)
C      ENDIF
      RETURN
      END
