!
      SUBROUTINE UPMHCOND2
!
!Purpose: Apply the matching conditions at m_H when running up
!
      IMPLICIT NONE
!
      COMMON/COUPLINGS/G,DG
      DOUBLE COMPLEX G(601)
      DOUBLE PRECISION DG(601)
      SAVE/COUPLINGS/
!
      COMMON/RGEMS/VEVMH,RGEMS,RGEMU
      DOUBLE COMPLEX VEVMH
      DOUBLE PRECISION RGEMS,RGEMU
      SAVE/RGEMS/
!
      COMMON/MYSUGRA/M0,M12,A0,TANB,SIGNMU,MT
      DOUBLE PRECISION M0,M12,A0,TANB,SIGNMU,MT
      SAVE/MYSUGRA/
!
      COMMON/THRESH/QTHSORT,QTHQL,QTHUR,QTHDR,QTHLL,QTHER,QNSH,QNSG,
     $              QNH,QTHSB,QTHSW,EPS,LOCMH
      DOUBLE PRECISION QTHSORT(20),QTHQL(3),QTHUR(3),QTHDR(3),QTHLL(3),
     $                QTHER(3),QNSH,QNSG,QNH,QTHSB,QTHSW,EPS
                                     !EPSILON IS USED WHEN Q=THRESHOLD
      INTEGER LOCMH
      SAVE/THRESH/
!
      COMMON/EWSBSAV/CSHSH,CSHLH,CLHLH,CULSHUR,CDLSHDR,CELSHER,CULLHUR,
     $               CDLLHDR,CELLHER
      DOUBLE COMPLEX CSHSH,CSHLH,CLHLH,CULSHUR(3,3),CDLSHDR(3,3),
     $               CELSHER(3,3),CULLHUR(3,3),CDLLHDR(3,3),CELLHER(3,3)
      SAVE/EWSBSAV/
!
      DOUBLE PRECISION SINB,COSB
      INTEGER I,J
!
      SINB=DSQRT(TANB**2/(1+TANB**2))
      COSB=SINB/TANB
!
      VEVMH=G(428)
      G(111)=DCMPLX(DSQRT((DBLE(G(428)))**2/(1.D0+TANB**2)))
      G(110)=DCMPLX(DSQRT((DBLE(G(428)))**2*TANB**2
     $        /(1.D0+TANB**2)))
!
      DO I=4,12
        G(I)=G(I+108)/SINB
      END DO
      DO I=13,30
        G(I)=G(I+108)/COSB
      END DO
!
!Refine the EWSB parameters if m_H>m_SUSY
!
      CSHSH=G(427)
      IF(RGEMS.LT.QNH)THEN
        G(62)=COSB**2*CSHSH-2.D0*SINB*COSB*CSHLH+SINB**2*CLHLH
        G(61)=SINB**2*CSHSH+2.D0*SINB*COSB*CSHLH+COSB**2*CLHLH
        G(109)=SINB*COSB*(-CSHSH+CLHLH)+(SINB**2-COSB**2)*CSHLH
      END IF
!
      RETURN
      END
