CDECK  ID>, ZEROL.
      SUBROUTINE ZEROL(Z,N)
C          SET N VALUES OF Z IN LEVEL2 TO ZERO
      COMMON/ITAPES/ITDKY,ITEVT,ITCOM,ITLIS
      SAVE /ITAPES/
      INTEGER   ITDKY,ITEVT,ITCOM,ITLIS
      DIMENSION Z(N)
      DO 1 I=1,N
    1 Z(I)=0
      RETURN
      END
