#if 0
* heeSM-vars.h
* variable declarations
* generated by FormCalc 7.5 on 27-Sep-2012 9:08
* this file is part of FeynHiggs
#endif

#ifndef VARS_H
#define VARS_H

#include "externals.h"
#include "types.h"
#include "debug.h"

#else

#include "Decay.h"
#include "heeSM-renconst.h"

	ComplexType Sub1, Sub11, Sub12, Sub14, Sub15, Sub19, Sub6
	ComplexType Sub8, Sub9
	common /heeSM_abbrev1s/ Sub1, Sub11, Sub12, Sub14, Sub15
	common /heeSM_abbrev1s/ Sub19, Sub6, Sub8, Sub9

	ComplexType AbbSum1, F1, F2
	common /heeSM_abbrev0hel/ AbbSum1, F1, F2

	ComplexType Sub10, Sub13, Sub16, Sub17, Sub18, Sub2, Sub20
	ComplexType Sub21, Sub3, Sub4, Sub5, Sub7
	common /heeSM_abbrev1hel/ Sub10, Sub13, Sub16, Sub17, Sub18
	common /heeSM_abbrev1hel/ Sub2, Sub20, Sub21, Sub3, Sub4
	common /heeSM_abbrev1hel/ Sub5, Sub7

	ComplexType lint1, lint2, lint4, lint6, lint3(Ncc)
	ComplexType lint5(Ncc), lint7(Ncc), lint8(Ncc), lint9(Ncc)
	common /heeSM_loopint1s/ lint1, lint2, lint4, lint6, lint3
	common /heeSM_loopint1s/ lint5, lint7, lint8, lint9

	integer seq(2), Hel(3)
	common /heeSM_helvars/ seq, Hel

	ComplexType Ctree(1), Cloop(1)
	common /heeSM_formfactors/ Ctree, Cloop

#endif
