#if 0
* hggSM-vars.h
* variable declarations
* generated by FormCalc 7.5 on 27-Sep-2012 9:08
* this file is part of FeynHiggs
#endif

#ifndef VARS_H
#define VARS_H

#include "externals.h"
#include "types.h"
#include "debug.h"

#else

#include "Decay.h"

	ComplexType Abb1, Abb2, Abb3, Pair1, Pair2, Pair3, Pair4
	ComplexType Pair5, Sub1, Sub2(3), Sub3(3), Sub4(3), Sub5(3)
	ComplexType Sub6(3), Sub7(3)
	common /hggSM_abbrev1hel/ Abb1, Abb2, Abb3, Pair1, Pair2
	common /hggSM_abbrev1hel/ Pair3, Pair4, Pair5, Sub1, Sub2
	common /hggSM_abbrev1hel/ Sub3, Sub4, Sub5, Sub6, Sub7

	ComplexType lint1(3), lint2(Ncc,3), lint3(3), lint4(Ncc,3)
	common /hggSM_loopint1s/ lint1, lint2, lint3, lint4

	integer seq(2), Hel(3)
	common /hggSM_helvars/ seq, Hel

	integer Gen4
	common /hggSM_indices/ Gen4

	ComplexType Cloop(1), MatSUN(1,1)
	common /hggSM_formfactors/ Cloop, MatSUN

#endif
