#if 0
* hddSM-vars.h
* variable declarations
* generated by FormCalc 7.5 on 27-Sep-2012 9:09
* this file is part of FeynHiggs
#endif

#ifndef VARS_H
#define VARS_H

#include "externals.h"
#include "types.h"
#include "debug.h"

#else

#include "Decay.h"
#include "hddSM-renconst.h"

	ComplexType Sub1, Sub12, Sub13, Sub14, Sub15, Sub19, Sub20
	ComplexType Sub3, Sub35, Sub39, Sub4, Sub5, Sub24(3)
	ComplexType Sub25(3), Sub27(3), Sub28(3), Sub30(3), Sub32(3)
	ComplexType Sub33(3), Sub34(3), Sub37(3), Sub38(3)
	common /hddSM_abbrev1s/ Sub1, Sub12, Sub13, Sub14, Sub15
	common /hddSM_abbrev1s/ Sub19, Sub20, Sub3, Sub35, Sub39
	common /hddSM_abbrev1s/ Sub4, Sub5, Sub24, Sub25, Sub27
	common /hddSM_abbrev1s/ Sub28, Sub30, Sub32, Sub33, Sub34
	common /hddSM_abbrev1s/ Sub37, Sub38

	ComplexType AbbSum1, F1, F2
	common /hddSM_abbrev0hel/ AbbSum1, F1, F2

	ComplexType Sub10, Sub11, Sub16, Sub17, Sub18, Sub2, Sub21
	ComplexType Sub22, Sub23, Sub6, Sub7, Sub8, Sub9, Sub26(3)
	ComplexType Sub29(3), Sub31(3), Sub36(3), Sub40(3)
	common /hddSM_abbrev1hel/ Sub10, Sub11, Sub16, Sub17, Sub18
	common /hddSM_abbrev1hel/ Sub2, Sub21, Sub22, Sub23, Sub6
	common /hddSM_abbrev1hel/ Sub7, Sub8, Sub9, Sub26, Sub29
	common /hddSM_abbrev1hel/ Sub31, Sub36, Sub40

	ComplexType lint1, lint4, lint2(Ncc), lint3(Ncc), lint5(Ncc)
	ComplexType lint6(Ncc), lint7(3), lint8(Ncc,3), lint9(Ncc,3)
	common /hddSM_loopint1s/ lint1, lint4, lint2, lint3, lint5
	common /hddSM_loopint1s/ lint6, lint7, lint8, lint9

	integer seq(2), Hel(3)
	common /hddSM_helvars/ seq, Hel

	integer Gen4
	common /hddSM_indices/ Gen4

	ComplexType Ctree(1), Cloop(1), MatSUN(1,1)
	common /hddSM_formfactors/ Ctree, Cloop, MatSUN

#endif
