#if 0
* huu-vars.h
* variable declarations
* generated by FormCalc 7.5 on 27-Sep-2012 9:19
* this file is part of FeynHiggs
#endif

#ifndef VARS_H
#define VARS_H

#include "externals.h"
#include "types.h"
#include "debug.h"

#else

#include "Decay.h"
#include "huu-renconst.h"

	ComplexType Opt1, Opt2, Sub1, Sub102, Sub104, Sub107, Sub108
	ComplexType Sub109, Sub11, Sub110, Sub111, Sub112, Sub113
	ComplexType Sub114, Sub115, Sub116, Sub117, Sub118, Sub119
	ComplexType Sub12, Sub120, Sub121, Sub122, Sub123, Sub124
	ComplexType Sub125, Sub129, Sub13, Sub14, Sub141, Sub143
	ComplexType Sub147, Sub15, Sub153, Sub156, Sub158, Sub16
	ComplexType Sub165, Sub168, Sub169, Sub197, Sub199, Sub2
	ComplexType Sub202, Sub206, Sub208, Sub248, Sub25, Sub258
	ComplexType Sub26, Sub261, Sub27, Sub28, Sub3, Sub30, Sub31
	ComplexType Sub32, Sub33, Sub35, Sub36, Sub398, Sub399, Sub4
	ComplexType Sub402, Sub403, Sub41, Sub42, Sub43, Sub44
	ComplexType Sub67, Sub7, Sub73, Sub74, Sub75, Sub76, Sub77
	ComplexType Sub78, Sub80, Sub81, Sub82, Sub83, Sub85, Sub86
	ComplexType Sub87, Sub88, Sub93, Sub94, Sub95, Sub96
	ComplexType Sub127(3), Sub131(3), Sub136(3), Sub138(3)
	ComplexType Sub139(3), Sub142(3), Sub145(3), Sub148(3)
	ComplexType Sub150(3), Sub157(3), Sub161(3), Sub162(3)
	ComplexType Sub164(3), Sub166(3), Sub170(3), Sub172(3)
	ComplexType Sub173(3), Sub174(3), Sub176(3), Sub177(3)
	ComplexType Sub179(3), Sub180(3), Sub181(3), Sub183(3)
	ComplexType Sub184(3), Sub185(3), Sub186(3), Sub188(3)
	ComplexType Sub190(3), Sub191(3), Sub192(3), Sub193(3)
	ComplexType Sub194(3), Sub195(3), Sub198(3), Sub200(3)
	ComplexType Sub212(4), Sub213(4), Sub214(4), Sub215(4)
	ComplexType Sub216(4,4), Sub217(4), Sub218(4), Sub219(4,4)
	ComplexType Sub220(4), Sub221(4), Sub222(4,4), Sub223(4,4)
	ComplexType Sub224(6,4), Sub225(4), Sub226(6,4), Sub227(4)
	ComplexType Sub228(6,4), Sub229(6,4), Sub230(4), Sub231(4)
	ComplexType Sub232(4), Sub233(4), Sub234(4,4), Sub235(4)
	ComplexType Sub236(4), Sub237(4,4), Sub238(4), Sub239(4)
	ComplexType Sub240(4,4), Sub241(4,4), Sub257(6,2,3)
	ComplexType Sub259(2,2), Sub260(6,2,3), Sub262(2,2)
	ComplexType Sub264(6,2,3), Sub268(3), Sub269(3,3)
	ComplexType Sub270(6,3,3), Sub271(3), Sub272(6,3,3)
	ComplexType Sub273(6,3,3), Sub274(6,6,3,3), Sub275(3)
	ComplexType Sub276(3,3), Sub277(6,3,3), Sub278(3)
	ComplexType Sub279(6,3,3), Sub280(6,3,3), Sub281(6,6,3,3)
	ComplexType Sub282(6,6,3,3), Sub283(3,3), Sub284(3,3)
	ComplexType Sub285(6,6,3,3), Sub287(6,6,3,3), Sub290(4)
	ComplexType Sub291(6,4), Sub292(6,4), Sub296(3), Sub297(3,3)
	ComplexType Sub298(6,3,3), Sub299(3), Sub300(6,3,3)
	ComplexType Sub301(6,3,3), Sub302(6,6,3,3), Sub303(3)
	ComplexType Sub304(3,3), Sub305(6,3,3), Sub306(3)
	ComplexType Sub307(6,3,3), Sub308(6,3,3), Sub309(6,6,3,3)
	ComplexType Sub310(6,6,3,3), Sub311(6,2,3), Sub312(3,3)
	ComplexType Sub313(3,3), Sub314(6,6,3,3), Sub316(3)
	ComplexType Sub317(3,3), Sub318(6,3,3), Sub319(3)
	ComplexType Sub320(6,3,3), Sub321(6,3,3), Sub322(6,6,3,3)
	ComplexType Sub323(3), Sub324(3,3), Sub325(6,3,3), Sub326(3)
	ComplexType Sub327(6,3,3), Sub328(6,3,3), Sub329(6,6,3,3)
	ComplexType Sub330(6,6,3,3), Sub331(3), Sub332(3,3)
	ComplexType Sub333(6,3,3), Sub334(3), Sub335(6,3,3)
	ComplexType Sub336(6,3,3), Sub337(6,6,3,3), Sub338(3)
	ComplexType Sub339(3,3), Sub340(6,3,3), Sub341(3)
	ComplexType Sub342(6,3,3), Sub343(6,3,3), Sub344(6,6,3,3)
	ComplexType Sub345(6,6,3,3), Sub346(3,3), Sub347(3,3)
	ComplexType Sub348(6,6,3,3), Sub349(3,3), Sub350(3,3)
	ComplexType Sub351(6,6,3,3), Sub352(6,6,3,3)
	ComplexType Sub353(6,6,3,3), Sub356(4), Sub357(4)
	ComplexType Sub358(4,4), Sub359(4), Sub360(4), Sub361(4,4)
	ComplexType Sub362(4,4), Sub363(4,4), Sub364(4,4)
	ComplexType Sub365(4,4), Sub366(4,4), Sub368(4,4), Sub371(3)
	ComplexType Sub372(3), Sub373(3), Sub374(3), Sub375(3,2,2)
	ComplexType Sub376(3), Sub377(3), Sub378(3,2), Sub379(3)
	ComplexType Sub380(3), Sub381(3,2), Sub382(3,2,2), Sub383(3)
	ComplexType Sub384(3), Sub385(3,2), Sub386(3), Sub387(3)
	ComplexType Sub388(3,2), Sub389(3,2,2), Sub390(3), Sub391(3)
	ComplexType Sub392(3,2,2), Sub393(3,2,2), Sub394(3,2,2)
	ComplexType Sub395(3,2,2), Sub397(2,2), Sub400(2,2)
	ComplexType Sub401(2,2), Sub404(2,2), Sub405(2,2)
	ComplexType Sub406(2,2), Sub407(2,2), Sub408(2,2)
	ComplexType Sub409(2,2), Sub411(2,2), Sub414(3), Sub415(3)
	ComplexType Sub416(6,3), Sub417(3), Sub418(3), Sub419(6,3)
	ComplexType Sub420(6,6,3), Sub421(6,3,3), Sub422(6,3,3)
	ComplexType Sub423(6,3,3), Sub424(6,6,3,3), Sub425(6,3,3)
	ComplexType Sub426(6,3,3), Sub427(6,3,3), Sub428(6,6,3,3)
	ComplexType Sub429(6,6,3,3), Sub430(6,6,3,3)
	ComplexType Sub431(6,6,3,3), Sub432(6,6,3,3), Sub435(6,6,3)
	ComplexType Sub436(3), Sub437(3,3), Sub438(6,3,3), Sub439(3)
	ComplexType Sub440(6,3,3), Sub441(6,3,3), Sub442(6,6,3,3)
	ComplexType Sub443(3), Sub444(3,3), Sub445(6,3,3), Sub446(3)
	ComplexType Sub447(6,3,3), Sub448(6,3,3), Sub449(6,6,3,3)
	ComplexType Sub450(6,6,3,3), Sub451(3,3), Sub452(3,3)
	ComplexType Sub453(6,6,3,3), Sub454(6,6,3,3)
	ComplexType Sub455(6,6,3,3), Sub458(3,3), Sub459(3,3)
	ComplexType Sub460(6,6,3,3), Sub461(6,3,3), Sub462(6,3,3)
	ComplexType Sub463(6,3,3), Sub464(6,6,3,3), Sub465(6,3,3)
	ComplexType Sub466(6,3,3), Sub467(6,3,3), Sub468(6,6,3,3)
	ComplexType Sub469(6,6,3,3), Sub470(6,6,3,3)
	ComplexType Sub471(6,6,3,3), Sub472(3,3), Sub473(3,3)
	ComplexType Sub474(6,6,3,3), Sub475(3), Sub476(3,3)
	ComplexType Sub477(6,3,3), Sub478(3), Sub479(6,3,3)
	ComplexType Sub480(6,3,3), Sub481(6,6,3,3), Sub482(3)
	ComplexType Sub483(3,3), Sub484(6,3,3), Sub485(3)
	ComplexType Sub486(6,3,3), Sub487(6,3,3), Sub488(6,6,3,3)
	ComplexType Sub489(6,6,3,3), Sub490(6,6,3,3), Sub491(3,3)
	ComplexType Sub492(3,3), Sub493(6,6,3,3), Sub494(6,6,3,3,3,3)
	common /huu_abbrev1s/ Opt1, Opt2, Sub1, Sub102, Sub104
	common /huu_abbrev1s/ Sub107, Sub108, Sub109, Sub11, Sub110
	common /huu_abbrev1s/ Sub111, Sub112, Sub113, Sub114, Sub115
	common /huu_abbrev1s/ Sub116, Sub117, Sub118, Sub119, Sub12
	common /huu_abbrev1s/ Sub120, Sub121, Sub122, Sub123, Sub124
	common /huu_abbrev1s/ Sub125, Sub129, Sub13, Sub14, Sub141
	common /huu_abbrev1s/ Sub143, Sub147, Sub15, Sub153, Sub156
	common /huu_abbrev1s/ Sub158, Sub16, Sub165, Sub168, Sub169
	common /huu_abbrev1s/ Sub197, Sub199, Sub2, Sub202, Sub206
	common /huu_abbrev1s/ Sub208, Sub248, Sub25, Sub258, Sub26
	common /huu_abbrev1s/ Sub261, Sub27, Sub28, Sub3, Sub30
	common /huu_abbrev1s/ Sub31, Sub32, Sub33, Sub35, Sub36
	common /huu_abbrev1s/ Sub398, Sub399, Sub4, Sub402, Sub403
	common /huu_abbrev1s/ Sub41, Sub42, Sub43, Sub44, Sub67
	common /huu_abbrev1s/ Sub7, Sub73, Sub74, Sub75, Sub76
	common /huu_abbrev1s/ Sub77, Sub78, Sub80, Sub81, Sub82
	common /huu_abbrev1s/ Sub83, Sub85, Sub86, Sub87, Sub88
	common /huu_abbrev1s/ Sub93, Sub94, Sub95, Sub96, Sub127
	common /huu_abbrev1s/ Sub131, Sub136, Sub138, Sub139, Sub142
	common /huu_abbrev1s/ Sub145, Sub148, Sub150, Sub157, Sub161
	common /huu_abbrev1s/ Sub162, Sub164, Sub166, Sub170, Sub172
	common /huu_abbrev1s/ Sub173, Sub174, Sub176, Sub177, Sub179
	common /huu_abbrev1s/ Sub180, Sub181, Sub183, Sub184, Sub185
	common /huu_abbrev1s/ Sub186, Sub188, Sub190, Sub191, Sub192
	common /huu_abbrev1s/ Sub193, Sub194, Sub195, Sub198, Sub200
	common /huu_abbrev1s/ Sub212, Sub213, Sub214, Sub215, Sub216
	common /huu_abbrev1s/ Sub217, Sub218, Sub219, Sub220, Sub221
	common /huu_abbrev1s/ Sub222, Sub223, Sub224, Sub225, Sub226
	common /huu_abbrev1s/ Sub227, Sub228, Sub229, Sub230, Sub231
	common /huu_abbrev1s/ Sub232, Sub233, Sub234, Sub235, Sub236
	common /huu_abbrev1s/ Sub237, Sub238, Sub239, Sub240, Sub241
	common /huu_abbrev1s/ Sub257, Sub259, Sub260, Sub262, Sub264
	common /huu_abbrev1s/ Sub268, Sub269, Sub270, Sub271, Sub272
	common /huu_abbrev1s/ Sub273, Sub274, Sub275, Sub276, Sub277
	common /huu_abbrev1s/ Sub278, Sub279, Sub280, Sub281, Sub282
	common /huu_abbrev1s/ Sub283, Sub284, Sub285, Sub287, Sub290
	common /huu_abbrev1s/ Sub291, Sub292, Sub296, Sub297, Sub298
	common /huu_abbrev1s/ Sub299, Sub300, Sub301, Sub302, Sub303
	common /huu_abbrev1s/ Sub304, Sub305, Sub306, Sub307, Sub308
	common /huu_abbrev1s/ Sub309, Sub310, Sub311, Sub312, Sub313
	common /huu_abbrev1s/ Sub314, Sub316, Sub317, Sub318, Sub319
	common /huu_abbrev1s/ Sub320, Sub321, Sub322, Sub323, Sub324
	common /huu_abbrev1s/ Sub325, Sub326, Sub327, Sub328, Sub329
	common /huu_abbrev1s/ Sub330, Sub331, Sub332, Sub333, Sub334
	common /huu_abbrev1s/ Sub335, Sub336, Sub337, Sub338, Sub339
	common /huu_abbrev1s/ Sub340, Sub341, Sub342, Sub343, Sub344
	common /huu_abbrev1s/ Sub345, Sub346, Sub347, Sub348, Sub349
	common /huu_abbrev1s/ Sub350, Sub351, Sub352, Sub353, Sub356
	common /huu_abbrev1s/ Sub357, Sub358, Sub359, Sub360, Sub361
	common /huu_abbrev1s/ Sub362, Sub363, Sub364, Sub365, Sub366
	common /huu_abbrev1s/ Sub368, Sub371, Sub372, Sub373, Sub374
	common /huu_abbrev1s/ Sub375, Sub376, Sub377, Sub378, Sub379
	common /huu_abbrev1s/ Sub380, Sub381, Sub382, Sub383, Sub384
	common /huu_abbrev1s/ Sub385, Sub386, Sub387, Sub388, Sub389
	common /huu_abbrev1s/ Sub390, Sub391, Sub392, Sub393, Sub394
	common /huu_abbrev1s/ Sub395, Sub397, Sub400, Sub401, Sub404
	common /huu_abbrev1s/ Sub405, Sub406, Sub407, Sub408, Sub409
	common /huu_abbrev1s/ Sub411, Sub414, Sub415, Sub416, Sub417
	common /huu_abbrev1s/ Sub418, Sub419, Sub420, Sub421, Sub422
	common /huu_abbrev1s/ Sub423, Sub424, Sub425, Sub426, Sub427
	common /huu_abbrev1s/ Sub428, Sub429, Sub430, Sub431, Sub432
	common /huu_abbrev1s/ Sub435, Sub436, Sub437, Sub438, Sub439
	common /huu_abbrev1s/ Sub440, Sub441, Sub442, Sub443, Sub444
	common /huu_abbrev1s/ Sub445, Sub446, Sub447, Sub448, Sub449
	common /huu_abbrev1s/ Sub450, Sub451, Sub452, Sub453, Sub454
	common /huu_abbrev1s/ Sub455, Sub458, Sub459, Sub460, Sub461
	common /huu_abbrev1s/ Sub462, Sub463, Sub464, Sub465, Sub466
	common /huu_abbrev1s/ Sub467, Sub468, Sub469, Sub470, Sub471
	common /huu_abbrev1s/ Sub472, Sub473, Sub474, Sub475, Sub476
	common /huu_abbrev1s/ Sub477, Sub478, Sub479, Sub480, Sub481
	common /huu_abbrev1s/ Sub482, Sub483, Sub484, Sub485, Sub486
	common /huu_abbrev1s/ Sub487, Sub488, Sub489, Sub490, Sub491
	common /huu_abbrev1s/ Sub492, Sub493, Sub494

	ComplexType F1, F2
	common /huu_abbrev0hel/ F1, F2

	ComplexType AbbSum1, Sub10, Sub100, Sub101, Sub103, Sub105
	ComplexType Sub106, Sub126, Sub133, Sub152, Sub17, Sub18
	ComplexType Sub19, Sub20, Sub203, Sub204, Sub205, Sub21
	ComplexType Sub22, Sub23, Sub24, Sub29, Sub34, Sub37, Sub38
	ComplexType Sub39, Sub40, Sub45, Sub46, Sub47, Sub48, Sub49
	ComplexType Sub5, Sub50, Sub51, Sub52, Sub53, Sub54, Sub55
	ComplexType Sub56, Sub57, Sub58, Sub59, Sub6, Sub60, Sub61
	ComplexType Sub62, Sub63, Sub64, Sub65, Sub66, Sub68, Sub69
	ComplexType Sub70, Sub71, Sub72, Sub79, Sub8, Sub84, Sub89
	ComplexType Sub9, Sub90, Sub91, Sub92, Sub97, Sub98, Sub99
	ComplexType Sub128(3), Sub130(3), Sub132(3), Sub134(3)
	ComplexType Sub135(3), Sub137(3), Sub140(3), Sub144(3)
	ComplexType Sub146(3), Sub149(3), Sub151(3), Sub154(3)
	ComplexType Sub155(3), Sub159(3), Sub160(3), Sub163(3)
	ComplexType Sub167(3), Sub171(3), Sub175(3), Sub178(3)
	ComplexType Sub182(3), Sub187(3), Sub189(3), Sub196(3)
	ComplexType Sub201(3), Sub207(3), Sub209(3), Sub210(3)
	ComplexType Sub211(3), Sub242(6,4,4), Sub243(6,4,4)
	ComplexType Sub244(6,4,4), Sub245(6,4,4), Sub246(6,4,4)
	ComplexType Sub247(6,4,4), Sub249(6,4,4), Sub250(6,4,4)
	ComplexType Sub251(6,4,4), Sub252(6,4,4), Sub253(6,4,4)
	ComplexType Sub254(6,4,4), Sub255(6,4,4), Sub256(6,4,4)
	ComplexType Sub263(6,2,2,3,3), Sub265(6,2,2,3,3)
	ComplexType Sub266(6,2,2,3,3), Sub267(6,2,2,3,3)
	ComplexType Sub286(6,6), Sub288(6,6), Sub289(6,6)
	ComplexType Sub293(6,6,4), Sub294(6,6,4), Sub295(6,6,4)
	ComplexType Sub315(6,6,2,3,3,3,3), Sub354(6,6,2,3,3,3,3)
	ComplexType Sub355(6,6,2,3,3,3,3), Sub367(4,4), Sub369(4,4)
	ComplexType Sub370(4,4), Sub396(3,2,2), Sub410(2,2)
	ComplexType Sub412(2,2), Sub413(2,2), Sub433(6,6,3,3,3)
	ComplexType Sub434(6,6,3,3,3), Sub456(6,6,3,3,3)
	ComplexType Sub457(6,6,3,3,3)
	common /huu_abbrev1hel/ AbbSum1, Sub10, Sub100, Sub101
	common /huu_abbrev1hel/ Sub103, Sub105, Sub106, Sub126
	common /huu_abbrev1hel/ Sub133, Sub152, Sub17, Sub18, Sub19
	common /huu_abbrev1hel/ Sub20, Sub203, Sub204, Sub205, Sub21
	common /huu_abbrev1hel/ Sub22, Sub23, Sub24, Sub29, Sub34
	common /huu_abbrev1hel/ Sub37, Sub38, Sub39, Sub40, Sub45
	common /huu_abbrev1hel/ Sub46, Sub47, Sub48, Sub49, Sub5
	common /huu_abbrev1hel/ Sub50, Sub51, Sub52, Sub53, Sub54
	common /huu_abbrev1hel/ Sub55, Sub56, Sub57, Sub58, Sub59
	common /huu_abbrev1hel/ Sub6, Sub60, Sub61, Sub62, Sub63
	common /huu_abbrev1hel/ Sub64, Sub65, Sub66, Sub68, Sub69
	common /huu_abbrev1hel/ Sub70, Sub71, Sub72, Sub79, Sub8
	common /huu_abbrev1hel/ Sub84, Sub89, Sub9, Sub90, Sub91
	common /huu_abbrev1hel/ Sub92, Sub97, Sub98, Sub99, Sub128
	common /huu_abbrev1hel/ Sub130, Sub132, Sub134, Sub135
	common /huu_abbrev1hel/ Sub137, Sub140, Sub144, Sub146
	common /huu_abbrev1hel/ Sub149, Sub151, Sub154, Sub155
	common /huu_abbrev1hel/ Sub159, Sub160, Sub163, Sub167
	common /huu_abbrev1hel/ Sub171, Sub175, Sub178, Sub182
	common /huu_abbrev1hel/ Sub187, Sub189, Sub196, Sub201
	common /huu_abbrev1hel/ Sub207, Sub209, Sub210, Sub211
	common /huu_abbrev1hel/ Sub242, Sub243, Sub244, Sub245
	common /huu_abbrev1hel/ Sub246, Sub247, Sub249, Sub250
	common /huu_abbrev1hel/ Sub251, Sub252, Sub253, Sub254
	common /huu_abbrev1hel/ Sub255, Sub256, Sub263, Sub265
	common /huu_abbrev1hel/ Sub266, Sub267, Sub286, Sub288
	common /huu_abbrev1hel/ Sub289, Sub293, Sub294, Sub295
	common /huu_abbrev1hel/ Sub315, Sub354, Sub355, Sub367
	common /huu_abbrev1hel/ Sub369, Sub370, Sub396, Sub410
	common /huu_abbrev1hel/ Sub412, Sub413, Sub433, Sub434
	common /huu_abbrev1hel/ Sub456, Sub457

	ComplexType lint1, lint10, lint2, lint3, lint76, lint77
	ComplexType lint78, lint79, lint80, lint81, lint82, lint83
	ComplexType lint84, lint85, lint86, lint87, lint88, lint89
	ComplexType lint9, lint90, lint91, lint92, lint93
	ComplexType lint11(Ncc), lint12(Ncc), lint13(Ncc)
	ComplexType lint14(Ncc), lint15(Ncc), lint16(Ncc)
	ComplexType lint17(Ncc), lint18(Ncc), lint19(Ncc)
	ComplexType lint20(Ncc), lint21(Ncc), lint22(Ncc)
	ComplexType lint23(Ncc), lint24(Ncc), lint25(Ncc)
	ComplexType lint26(Ncc), lint27(Ncc), lint28(Ncc)
	ComplexType lint29(Ncc), lint30(Ncc,3), lint31(Ncc,3)
	ComplexType lint32(Ncc,3), lint33(Ncc,3), lint34(Ncc,3)
	ComplexType lint35(Ncc,3), lint36(3), lint37(Ncc,3)
	ComplexType lint38(3), lint39(Ncc,3), lint4(Ncc)
	ComplexType lint40(6,4), lint41(Ncc,6,4,4), lint42(6,2)
	ComplexType lint43(Ncc,6,2,2), lint44(Ncc,6,6)
	ComplexType lint45(Ncc,6,6,4), lint46(Ncc,6,6,2), lint47(4)
	ComplexType lint48(4,4), lint49(4,4), lint5(Ncc)
	ComplexType lint50(3,2), lint51(3,2,2), lint52(3,2,2)
	ComplexType lint53(2), lint54(2,2), lint55(2,2), lint56(6)
	ComplexType lint57(6), lint58(6,6), lint59(6,6), lint6(Ncc)
	ComplexType lint60(6,6), lint61(6,6), lint62(Ncc)
	ComplexType lint63(Ncc), lint64(3), lint65(3), lint66(3)
	ComplexType lint67(3), lint68(3), lint69(3), lint7(Ncc)
	ComplexType lint70(3), lint71(3), lint72(3), lint73(3)
	ComplexType lint74(3), lint75(3), lint8(Ncc)
	common /huu_loopint1s/ lint1, lint10, lint2, lint3, lint76
	common /huu_loopint1s/ lint77, lint78, lint79, lint80
	common /huu_loopint1s/ lint81, lint82, lint83, lint84
	common /huu_loopint1s/ lint85, lint86, lint87, lint88
	common /huu_loopint1s/ lint89, lint9, lint90, lint91, lint92
	common /huu_loopint1s/ lint93, lint11, lint12, lint13
	common /huu_loopint1s/ lint14, lint15, lint16, lint17
	common /huu_loopint1s/ lint18, lint19, lint20, lint21
	common /huu_loopint1s/ lint22, lint23, lint24, lint25
	common /huu_loopint1s/ lint26, lint27, lint28, lint29
	common /huu_loopint1s/ lint30, lint31, lint32, lint33
	common /huu_loopint1s/ lint34, lint35, lint36, lint37
	common /huu_loopint1s/ lint38, lint39, lint4, lint40, lint41
	common /huu_loopint1s/ lint42, lint43, lint44, lint45
	common /huu_loopint1s/ lint46, lint47, lint48, lint49, lint5
	common /huu_loopint1s/ lint50, lint51, lint52, lint53
	common /huu_loopint1s/ lint54, lint55, lint56, lint57
	common /huu_loopint1s/ lint58, lint59, lint6, lint60, lint61
	common /huu_loopint1s/ lint62, lint63, lint64, lint65
	common /huu_loopint1s/ lint66, lint67, lint68, lint69, lint7
	common /huu_loopint1s/ lint70, lint71, lint72, lint73
	common /huu_loopint1s/ lint74, lint75, lint8

	integer seq(2), Hel(3)
	common /huu_helvars/ seq, Hel

	integer All4, All5, Cha4, Cha5, Gen4, Ind1, Ind2, Ind3, Ind4
	integer Neu4, Neu5, Sfe4, Sfe5
	common /huu_indices/ All4, All5, Cha4, Cha5, Gen4, Ind1, Ind2
	common /huu_indices/ Ind3, Ind4, Neu4, Neu5, Sfe4, Sfe5

	ComplexType Ctree(1), Cloop(1), MatSUN(1,1)
	common /huu_formfactors/ Ctree, Cloop, MatSUN

#endif
