#if 0
* hdd-vars.h
* variable declarations
* generated by FormCalc 7.5 on 27-Sep-2012 9:24
* this file is part of FeynHiggs
#endif

#ifndef VARS_H
#define VARS_H

#include "externals.h"
#include "types.h"
#include "debug.h"

#else

#include "Decay.h"
#include "hdd-renconst.h"

	ComplexType Opt1, Opt2, Sub1, Sub103, Sub105, Sub108, Sub109
	ComplexType Sub11, Sub110, Sub111, Sub112, Sub113, Sub114
	ComplexType Sub115, Sub116, Sub117, Sub118, Sub119, Sub12
	ComplexType Sub120, Sub121, Sub122, Sub123, Sub124, Sub126
	ComplexType Sub13, Sub136, Sub138, Sub14, Sub146, Sub148
	ComplexType Sub15, Sub154, Sub157, Sub159, Sub16, Sub160
	ComplexType Sub164, Sub167, Sub170, Sub171, Sub193, Sub194
	ComplexType Sub198, Sub2, Sub200, Sub204, Sub207, Sub211
	ComplexType Sub250, Sub260, Sub263, Sub28, Sub29, Sub3
	ComplexType Sub30, Sub31, Sub33, Sub34, Sub35, Sub36, Sub38
	ComplexType Sub39, Sub4, Sub401, Sub402, Sub405, Sub406
	ComplexType Sub44, Sub45, Sub46, Sub47, Sub7, Sub70, Sub75
	ComplexType Sub76, Sub77, Sub78, Sub79, Sub80, Sub82, Sub83
	ComplexType Sub84, Sub85, Sub88, Sub89, Sub90, Sub91, Sub95
	ComplexType Sub96, Sub97, Sub127(3), Sub129(3), Sub131(3)
	ComplexType Sub137(3), Sub139(3), Sub141(3), Sub142(3)
	ComplexType Sub144(3), Sub149(3), Sub151(3), Sub158(3)
	ComplexType Sub161(3), Sub163(3), Sub165(3), Sub168(3)
	ComplexType Sub172(3), Sub174(3), Sub175(3), Sub177(3)
	ComplexType Sub178(3), Sub180(3), Sub181(3), Sub183(3)
	ComplexType Sub184(3), Sub185(3), Sub186(3), Sub188(3)
	ComplexType Sub189(3), Sub190(3), Sub192(3), Sub195(3)
	ComplexType Sub197(3), Sub199(3), Sub201(3), Sub202(3)
	ComplexType Sub214(4), Sub215(4), Sub216(4), Sub217(4)
	ComplexType Sub218(4,4), Sub219(4), Sub220(4), Sub221(4,4)
	ComplexType Sub222(4), Sub223(4), Sub224(4,4), Sub225(4,4)
	ComplexType Sub226(6,4), Sub227(4), Sub228(6,4), Sub229(4)
	ComplexType Sub230(6,4), Sub231(6,4), Sub232(4), Sub233(4)
	ComplexType Sub234(4), Sub235(4), Sub236(4,4), Sub237(4)
	ComplexType Sub238(4), Sub239(4,4), Sub240(4), Sub241(4)
	ComplexType Sub242(4,4), Sub243(4,4), Sub259(6,2,3)
	ComplexType Sub261(2,2), Sub262(6,2,3), Sub264(2,2)
	ComplexType Sub266(6,2,3), Sub270(3), Sub271(3,3)
	ComplexType Sub272(6,3,3), Sub273(3), Sub274(6,3,3)
	ComplexType Sub275(6,3,3), Sub276(6,6,3,3), Sub277(3)
	ComplexType Sub278(3,3), Sub279(6,3,3), Sub280(3)
	ComplexType Sub281(6,3,3), Sub282(6,3,3), Sub283(6,6,3,3)
	ComplexType Sub284(6,6,3,3), Sub285(3,3), Sub286(3,3)
	ComplexType Sub287(6,6,3,3), Sub289(6,6,3,3), Sub292(4)
	ComplexType Sub293(6,4), Sub294(6,4), Sub298(3), Sub299(3,3)
	ComplexType Sub300(6,3,3), Sub301(3), Sub302(6,3,3)
	ComplexType Sub303(6,3,3), Sub304(6,6,3,3), Sub305(3)
	ComplexType Sub306(3,3), Sub307(6,3,3), Sub308(3)
	ComplexType Sub309(6,3,3), Sub310(6,3,3), Sub311(6,6,3,3)
	ComplexType Sub312(6,6,3,3), Sub313(6,2,3), Sub314(3,3)
	ComplexType Sub315(3,3), Sub316(6,6,3,3), Sub318(6,6,3,3)
	ComplexType Sub319(3), Sub320(3,3), Sub321(6,3,3), Sub322(3)
	ComplexType Sub323(6,3,3), Sub324(6,3,3), Sub325(6,6,3,3)
	ComplexType Sub326(3), Sub327(3,3), Sub328(6,3,3), Sub329(3)
	ComplexType Sub330(6,3,3), Sub331(6,3,3), Sub332(6,6,3,3)
	ComplexType Sub333(6,6,3,3), Sub334(3), Sub335(3,3)
	ComplexType Sub336(6,3,3), Sub337(3), Sub338(6,3,3)
	ComplexType Sub339(6,3,3), Sub340(6,6,3,3), Sub341(3)
	ComplexType Sub342(3,3), Sub343(6,3,3), Sub344(3)
	ComplexType Sub345(6,3,3), Sub346(6,3,3), Sub347(6,6,3,3)
	ComplexType Sub348(6,6,3,3), Sub349(3,3), Sub350(3,3)
	ComplexType Sub351(6,6,3,3), Sub352(3,3), Sub353(3,3)
	ComplexType Sub354(6,6,3,3), Sub355(6,6,3,3)
	ComplexType Sub356(6,6,3,3), Sub359(4), Sub360(4)
	ComplexType Sub361(4,4), Sub362(4), Sub363(4), Sub364(4,4)
	ComplexType Sub365(4,4), Sub366(4,4), Sub367(4,4)
	ComplexType Sub368(4,4), Sub369(4,4), Sub371(4,4), Sub374(3)
	ComplexType Sub375(3), Sub376(3), Sub377(3), Sub378(3,2,2)
	ComplexType Sub379(3), Sub380(3), Sub381(3,2), Sub382(3)
	ComplexType Sub383(3), Sub384(3,2), Sub385(3,2,2), Sub386(3)
	ComplexType Sub387(3), Sub388(3,2), Sub389(3), Sub390(3)
	ComplexType Sub391(3,2), Sub392(3,2,2), Sub393(3), Sub394(3)
	ComplexType Sub395(3,2,2), Sub396(3,2,2), Sub397(3,2,2)
	ComplexType Sub398(3,2,2), Sub400(2,2), Sub403(2,2)
	ComplexType Sub404(2,2), Sub407(2,2), Sub408(2,2)
	ComplexType Sub409(2,2), Sub410(2,2), Sub411(2,2)
	ComplexType Sub412(2,2), Sub413(2,2), Sub415(2,2), Sub418(3)
	ComplexType Sub419(3), Sub420(6,3), Sub421(3), Sub422(3)
	ComplexType Sub423(6,3), Sub424(6,6,3), Sub425(3)
	ComplexType Sub426(3,3), Sub427(6,3,3), Sub428(3)
	ComplexType Sub429(6,3,3), Sub430(6,3,3), Sub431(6,6,3,3)
	ComplexType Sub432(3), Sub433(3,3), Sub434(6,3,3), Sub435(3)
	ComplexType Sub436(6,3,3), Sub437(6,3,3), Sub438(6,6,3,3)
	ComplexType Sub439(6,6,3,3), Sub440(3,3), Sub441(3,3)
	ComplexType Sub442(6,6,3,3), Sub443(6,6,3,3)
	ComplexType Sub444(6,6,3,3), Sub447(6,6,3), Sub448(6,3,3)
	ComplexType Sub449(6,3,3), Sub450(6,3,3), Sub451(6,6,3,3)
	ComplexType Sub452(6,3,3), Sub453(6,3,3), Sub454(6,3,3)
	ComplexType Sub455(6,6,3,3), Sub456(6,6,3,3)
	ComplexType Sub457(6,6,3,3), Sub458(6,6,3,3)
	ComplexType Sub459(6,6,3,3), Sub462(3,3), Sub463(3,3)
	ComplexType Sub464(6,6,3,3), Sub465(3), Sub466(3,3)
	ComplexType Sub467(6,3,3), Sub468(3), Sub469(6,3,3)
	ComplexType Sub470(6,3,3), Sub471(6,6,3,3), Sub472(3)
	ComplexType Sub473(3,3), Sub474(6,3,3), Sub475(3)
	ComplexType Sub476(6,3,3), Sub477(6,3,3), Sub478(6,6,3,3)
	ComplexType Sub479(6,6,3,3), Sub480(3,3), Sub481(3,3)
	ComplexType Sub482(6,6,3,3), Sub483(6,6,3,3), Sub484(3,3)
	ComplexType Sub485(3,3), Sub486(6,6,3,3), Sub487(6,3,3)
	ComplexType Sub488(6,3,3), Sub489(6,3,3), Sub490(6,6,3,3)
	ComplexType Sub491(6,3,3), Sub492(6,3,3), Sub493(6,3,3)
	ComplexType Sub494(6,6,3,3), Sub495(6,6,3,3)
	ComplexType Sub496(6,6,3,3), Sub497(3,3), Sub498(3,3)
	ComplexType Sub499(6,6,3,3), Sub500(6,6,3,3,3,3)
	common /hdd_abbrev1s/ Opt1, Opt2, Sub1, Sub103, Sub105
	common /hdd_abbrev1s/ Sub108, Sub109, Sub11, Sub110, Sub111
	common /hdd_abbrev1s/ Sub112, Sub113, Sub114, Sub115, Sub116
	common /hdd_abbrev1s/ Sub117, Sub118, Sub119, Sub12, Sub120
	common /hdd_abbrev1s/ Sub121, Sub122, Sub123, Sub124, Sub126
	common /hdd_abbrev1s/ Sub13, Sub136, Sub138, Sub14, Sub146
	common /hdd_abbrev1s/ Sub148, Sub15, Sub154, Sub157, Sub159
	common /hdd_abbrev1s/ Sub16, Sub160, Sub164, Sub167, Sub170
	common /hdd_abbrev1s/ Sub171, Sub193, Sub194, Sub198, Sub2
	common /hdd_abbrev1s/ Sub200, Sub204, Sub207, Sub211, Sub250
	common /hdd_abbrev1s/ Sub260, Sub263, Sub28, Sub29, Sub3
	common /hdd_abbrev1s/ Sub30, Sub31, Sub33, Sub34, Sub35
	common /hdd_abbrev1s/ Sub36, Sub38, Sub39, Sub4, Sub401
	common /hdd_abbrev1s/ Sub402, Sub405, Sub406, Sub44, Sub45
	common /hdd_abbrev1s/ Sub46, Sub47, Sub7, Sub70, Sub75
	common /hdd_abbrev1s/ Sub76, Sub77, Sub78, Sub79, Sub80
	common /hdd_abbrev1s/ Sub82, Sub83, Sub84, Sub85, Sub88
	common /hdd_abbrev1s/ Sub89, Sub90, Sub91, Sub95, Sub96
	common /hdd_abbrev1s/ Sub97, Sub127, Sub129, Sub131, Sub137
	common /hdd_abbrev1s/ Sub139, Sub141, Sub142, Sub144, Sub149
	common /hdd_abbrev1s/ Sub151, Sub158, Sub161, Sub163, Sub165
	common /hdd_abbrev1s/ Sub168, Sub172, Sub174, Sub175, Sub177
	common /hdd_abbrev1s/ Sub178, Sub180, Sub181, Sub183, Sub184
	common /hdd_abbrev1s/ Sub185, Sub186, Sub188, Sub189, Sub190
	common /hdd_abbrev1s/ Sub192, Sub195, Sub197, Sub199, Sub201
	common /hdd_abbrev1s/ Sub202, Sub214, Sub215, Sub216, Sub217
	common /hdd_abbrev1s/ Sub218, Sub219, Sub220, Sub221, Sub222
	common /hdd_abbrev1s/ Sub223, Sub224, Sub225, Sub226, Sub227
	common /hdd_abbrev1s/ Sub228, Sub229, Sub230, Sub231, Sub232
	common /hdd_abbrev1s/ Sub233, Sub234, Sub235, Sub236, Sub237
	common /hdd_abbrev1s/ Sub238, Sub239, Sub240, Sub241, Sub242
	common /hdd_abbrev1s/ Sub243, Sub259, Sub261, Sub262, Sub264
	common /hdd_abbrev1s/ Sub266, Sub270, Sub271, Sub272, Sub273
	common /hdd_abbrev1s/ Sub274, Sub275, Sub276, Sub277, Sub278
	common /hdd_abbrev1s/ Sub279, Sub280, Sub281, Sub282, Sub283
	common /hdd_abbrev1s/ Sub284, Sub285, Sub286, Sub287, Sub289
	common /hdd_abbrev1s/ Sub292, Sub293, Sub294, Sub298, Sub299
	common /hdd_abbrev1s/ Sub300, Sub301, Sub302, Sub303, Sub304
	common /hdd_abbrev1s/ Sub305, Sub306, Sub307, Sub308, Sub309
	common /hdd_abbrev1s/ Sub310, Sub311, Sub312, Sub313, Sub314
	common /hdd_abbrev1s/ Sub315, Sub316, Sub318, Sub319, Sub320
	common /hdd_abbrev1s/ Sub321, Sub322, Sub323, Sub324, Sub325
	common /hdd_abbrev1s/ Sub326, Sub327, Sub328, Sub329, Sub330
	common /hdd_abbrev1s/ Sub331, Sub332, Sub333, Sub334, Sub335
	common /hdd_abbrev1s/ Sub336, Sub337, Sub338, Sub339, Sub340
	common /hdd_abbrev1s/ Sub341, Sub342, Sub343, Sub344, Sub345
	common /hdd_abbrev1s/ Sub346, Sub347, Sub348, Sub349, Sub350
	common /hdd_abbrev1s/ Sub351, Sub352, Sub353, Sub354, Sub355
	common /hdd_abbrev1s/ Sub356, Sub359, Sub360, Sub361, Sub362
	common /hdd_abbrev1s/ Sub363, Sub364, Sub365, Sub366, Sub367
	common /hdd_abbrev1s/ Sub368, Sub369, Sub371, Sub374, Sub375
	common /hdd_abbrev1s/ Sub376, Sub377, Sub378, Sub379, Sub380
	common /hdd_abbrev1s/ Sub381, Sub382, Sub383, Sub384, Sub385
	common /hdd_abbrev1s/ Sub386, Sub387, Sub388, Sub389, Sub390
	common /hdd_abbrev1s/ Sub391, Sub392, Sub393, Sub394, Sub395
	common /hdd_abbrev1s/ Sub396, Sub397, Sub398, Sub400, Sub403
	common /hdd_abbrev1s/ Sub404, Sub407, Sub408, Sub409, Sub410
	common /hdd_abbrev1s/ Sub411, Sub412, Sub413, Sub415, Sub418
	common /hdd_abbrev1s/ Sub419, Sub420, Sub421, Sub422, Sub423
	common /hdd_abbrev1s/ Sub424, Sub425, Sub426, Sub427, Sub428
	common /hdd_abbrev1s/ Sub429, Sub430, Sub431, Sub432, Sub433
	common /hdd_abbrev1s/ Sub434, Sub435, Sub436, Sub437, Sub438
	common /hdd_abbrev1s/ Sub439, Sub440, Sub441, Sub442, Sub443
	common /hdd_abbrev1s/ Sub444, Sub447, Sub448, Sub449, Sub450
	common /hdd_abbrev1s/ Sub451, Sub452, Sub453, Sub454, Sub455
	common /hdd_abbrev1s/ Sub456, Sub457, Sub458, Sub459, Sub462
	common /hdd_abbrev1s/ Sub463, Sub464, Sub465, Sub466, Sub467
	common /hdd_abbrev1s/ Sub468, Sub469, Sub470, Sub471, Sub472
	common /hdd_abbrev1s/ Sub473, Sub474, Sub475, Sub476, Sub477
	common /hdd_abbrev1s/ Sub478, Sub479, Sub480, Sub481, Sub482
	common /hdd_abbrev1s/ Sub483, Sub484, Sub485, Sub486, Sub487
	common /hdd_abbrev1s/ Sub488, Sub489, Sub490, Sub491, Sub492
	common /hdd_abbrev1s/ Sub493, Sub494, Sub495, Sub496, Sub497
	common /hdd_abbrev1s/ Sub498, Sub499, Sub500

	ComplexType F1, F2
	common /hdd_abbrev0hel/ F1, F2

	ComplexType AbbSum1, Sub10, Sub100, Sub101, Sub102, Sub104
	ComplexType Sub106, Sub107, Sub125, Sub133, Sub153, Sub17
	ComplexType Sub18, Sub19, Sub20, Sub205, Sub206, Sub208
	ComplexType Sub21, Sub22, Sub23, Sub24, Sub25, Sub26, Sub27
	ComplexType Sub32, Sub37, Sub40, Sub41, Sub42, Sub43, Sub48
	ComplexType Sub49, Sub5, Sub50, Sub51, Sub52, Sub53, Sub54
	ComplexType Sub55, Sub56, Sub57, Sub58, Sub59, Sub6, Sub60
	ComplexType Sub61, Sub62, Sub63, Sub64, Sub65, Sub66, Sub67
	ComplexType Sub68, Sub69, Sub71, Sub72, Sub73, Sub74, Sub8
	ComplexType Sub81, Sub86, Sub87, Sub9, Sub92, Sub93, Sub94
	ComplexType Sub98, Sub99, Sub128(3), Sub130(3), Sub132(3)
	ComplexType Sub134(3), Sub135(3), Sub140(3), Sub143(3)
	ComplexType Sub145(3), Sub147(3), Sub150(3), Sub152(3)
	ComplexType Sub155(3), Sub156(3), Sub162(3), Sub166(3)
	ComplexType Sub169(3), Sub173(3), Sub176(3), Sub179(3)
	ComplexType Sub182(3), Sub187(3), Sub191(3), Sub196(3)
	ComplexType Sub203(3), Sub209(3), Sub210(3), Sub212(3)
	ComplexType Sub213(3), Sub244(6,4,4), Sub245(6,4,4)
	ComplexType Sub246(6,4,4), Sub247(6,4,4), Sub248(6,4,4)
	ComplexType Sub249(6,4,4), Sub251(6,4,4), Sub252(6,4,4)
	ComplexType Sub253(6,4,4), Sub254(6,4,4), Sub255(6,4,4)
	ComplexType Sub256(6,4,4), Sub257(6,4,4), Sub258(6,4,4)
	ComplexType Sub265(6,2,2,3,3), Sub267(6,2,2,3,3)
	ComplexType Sub268(6,2,2,3,3), Sub269(6,2,2,3,3)
	ComplexType Sub288(6,6), Sub290(6,6), Sub291(6,6)
	ComplexType Sub295(6,6,4), Sub296(6,6,4), Sub297(6,6,4)
	ComplexType Sub317(6,6,2,3,3), Sub357(6,6,2,3,3,3,3)
	ComplexType Sub358(6,6,2,3,3,3,3), Sub370(4,4), Sub372(4,4)
	ComplexType Sub373(4,4), Sub399(3,2,2), Sub414(2,2)
	ComplexType Sub416(2,2), Sub417(2,2), Sub445(6,6,3,3,3)
	ComplexType Sub446(6,6,3,3,3), Sub460(6,6,3,3,3)
	ComplexType Sub461(6,6,3,3,3)
	common /hdd_abbrev1hel/ AbbSum1, Sub10, Sub100, Sub101
	common /hdd_abbrev1hel/ Sub102, Sub104, Sub106, Sub107
	common /hdd_abbrev1hel/ Sub125, Sub133, Sub153, Sub17, Sub18
	common /hdd_abbrev1hel/ Sub19, Sub20, Sub205, Sub206, Sub208
	common /hdd_abbrev1hel/ Sub21, Sub22, Sub23, Sub24, Sub25
	common /hdd_abbrev1hel/ Sub26, Sub27, Sub32, Sub37, Sub40
	common /hdd_abbrev1hel/ Sub41, Sub42, Sub43, Sub48, Sub49
	common /hdd_abbrev1hel/ Sub5, Sub50, Sub51, Sub52, Sub53
	common /hdd_abbrev1hel/ Sub54, Sub55, Sub56, Sub57, Sub58
	common /hdd_abbrev1hel/ Sub59, Sub6, Sub60, Sub61, Sub62
	common /hdd_abbrev1hel/ Sub63, Sub64, Sub65, Sub66, Sub67
	common /hdd_abbrev1hel/ Sub68, Sub69, Sub71, Sub72, Sub73
	common /hdd_abbrev1hel/ Sub74, Sub8, Sub81, Sub86, Sub87
	common /hdd_abbrev1hel/ Sub9, Sub92, Sub93, Sub94, Sub98
	common /hdd_abbrev1hel/ Sub99, Sub128, Sub130, Sub132
	common /hdd_abbrev1hel/ Sub134, Sub135, Sub140, Sub143
	common /hdd_abbrev1hel/ Sub145, Sub147, Sub150, Sub152
	common /hdd_abbrev1hel/ Sub155, Sub156, Sub162, Sub166
	common /hdd_abbrev1hel/ Sub169, Sub173, Sub176, Sub179
	common /hdd_abbrev1hel/ Sub182, Sub187, Sub191, Sub196
	common /hdd_abbrev1hel/ Sub203, Sub209, Sub210, Sub212
	common /hdd_abbrev1hel/ Sub213, Sub244, Sub245, Sub246
	common /hdd_abbrev1hel/ Sub247, Sub248, Sub249, Sub251
	common /hdd_abbrev1hel/ Sub252, Sub253, Sub254, Sub255
	common /hdd_abbrev1hel/ Sub256, Sub257, Sub258, Sub265
	common /hdd_abbrev1hel/ Sub267, Sub268, Sub269, Sub288
	common /hdd_abbrev1hel/ Sub290, Sub291, Sub295, Sub296
	common /hdd_abbrev1hel/ Sub297, Sub317, Sub357, Sub358
	common /hdd_abbrev1hel/ Sub370, Sub372, Sub373, Sub399
	common /hdd_abbrev1hel/ Sub414, Sub416, Sub417, Sub445
	common /hdd_abbrev1hel/ Sub446, Sub460, Sub461

	ComplexType lint1, lint10, lint2, lint3, lint76, lint77
	ComplexType lint78, lint79, lint80, lint81, lint82, lint83
	ComplexType lint84, lint85, lint86, lint87, lint88, lint89
	ComplexType lint9, lint90, lint91, lint92, lint93
	ComplexType lint11(Ncc), lint12(Ncc), lint13(Ncc)
	ComplexType lint14(Ncc), lint15(Ncc), lint16(Ncc)
	ComplexType lint17(Ncc), lint18(Ncc), lint19(Ncc)
	ComplexType lint20(Ncc), lint21(Ncc), lint22(Ncc)
	ComplexType lint23(Ncc), lint24(Ncc), lint25(Ncc)
	ComplexType lint26(Ncc), lint27(Ncc), lint28(Ncc)
	ComplexType lint29(Ncc), lint30(Ncc,3), lint31(Ncc,3)
	ComplexType lint32(Ncc,3), lint33(Ncc,3), lint34(Ncc,3)
	ComplexType lint35(Ncc,3), lint36(3), lint37(3)
	ComplexType lint38(Ncc,3), lint39(Ncc,3), lint4(Ncc)
	ComplexType lint40(6,4), lint41(Ncc,6,4,4), lint42(6,2)
	ComplexType lint43(Ncc,6,2,2), lint44(Ncc,6,6)
	ComplexType lint45(Ncc,6,6,4), lint46(Ncc,6,6,2), lint47(4)
	ComplexType lint48(4,4), lint49(4,4), lint5(Ncc)
	ComplexType lint50(3,2), lint51(3,2,2), lint52(3,2,2)
	ComplexType lint53(2), lint54(2,2), lint55(2,2), lint56(6)
	ComplexType lint57(6), lint58(6,6), lint59(6,6), lint6(Ncc)
	ComplexType lint60(6,6), lint61(6,6), lint62(Ncc)
	ComplexType lint63(Ncc), lint64(3), lint65(3), lint66(3)
	ComplexType lint67(3), lint68(3), lint69(3), lint7(Ncc)
	ComplexType lint70(3), lint71(3), lint72(3), lint73(3)
	ComplexType lint74(3), lint75(3), lint8(Ncc)
	common /hdd_loopint1s/ lint1, lint10, lint2, lint3, lint76
	common /hdd_loopint1s/ lint77, lint78, lint79, lint80
	common /hdd_loopint1s/ lint81, lint82, lint83, lint84
	common /hdd_loopint1s/ lint85, lint86, lint87, lint88
	common /hdd_loopint1s/ lint89, lint9, lint90, lint91, lint92
	common /hdd_loopint1s/ lint93, lint11, lint12, lint13
	common /hdd_loopint1s/ lint14, lint15, lint16, lint17
	common /hdd_loopint1s/ lint18, lint19, lint20, lint21
	common /hdd_loopint1s/ lint22, lint23, lint24, lint25
	common /hdd_loopint1s/ lint26, lint27, lint28, lint29
	common /hdd_loopint1s/ lint30, lint31, lint32, lint33
	common /hdd_loopint1s/ lint34, lint35, lint36, lint37
	common /hdd_loopint1s/ lint38, lint39, lint4, lint40, lint41
	common /hdd_loopint1s/ lint42, lint43, lint44, lint45
	common /hdd_loopint1s/ lint46, lint47, lint48, lint49, lint5
	common /hdd_loopint1s/ lint50, lint51, lint52, lint53
	common /hdd_loopint1s/ lint54, lint55, lint56, lint57
	common /hdd_loopint1s/ lint58, lint59, lint6, lint60, lint61
	common /hdd_loopint1s/ lint62, lint63, lint64, lint65
	common /hdd_loopint1s/ lint66, lint67, lint68, lint69, lint7
	common /hdd_loopint1s/ lint70, lint71, lint72, lint73
	common /hdd_loopint1s/ lint74, lint75, lint8

	integer seq(2), Hel(3)
	common /hdd_helvars/ seq, Hel

	integer All4, All5, Cha4, Cha5, Gen4, Ind1, Ind2, Ind3, Ind4
	integer Neu4, Neu5, Sfe4, Sfe5
	common /hdd_indices/ All4, All5, Cha4, Cha5, Gen4, Ind1, Ind2
	common /hdd_indices/ Ind3, Ind4, Neu4, Neu5, Sfe4, Sfe5

	ComplexType Ctree(1), Cloop(1), MatSUN(1,1)
	common /hdd_formfactors/ Ctree, Cloop, MatSUN

#endif
