#if 0
* hee-vars.h
* variable declarations
* generated by FormCalc 7.5 on 27-Sep-2012 9:15
* this file is part of FeynHiggs
#endif

#ifndef VARS_H
#define VARS_H

#include "externals.h"
#include "types.h"
#include "debug.h"

#else

#include "Decay.h"
#include "hee-renconst.h"

	ComplexType Opt1, Sub156, Sub158, Sub16, Sub17, Sub173
	ComplexType Sub174, Sub175, Sub178, Sub179, Sub18, Sub19
	ComplexType Sub20, Sub208, Sub209, Sub21, Sub215, Sub216
	ComplexType Sub217, Sub22, Sub23, Sub24, Sub47, Sub48, Sub49
	ComplexType Sub52, Sub53, Sub54, Sub55, Sub56, Sub62, Sub64
	ComplexType Sub66, Sub67, Sub68, Sub69, Sub70, Sub71, Sub72
	ComplexType Sub73, Sub74, Sub75, Sub76, Sub77, Sub78, Sub79
	ComplexType Sub80, Sub81, Sub82, Sub83, Sub84, Sub86, Sub87
	ComplexType Sub90, Sub91, Sub93, Sub94, Sub97, Sub98
	ComplexType Sub100(2,2), Sub101(2,2), Sub102(4), Sub103(4,2)
	ComplexType Sub104(4), Sub105(4,2), Sub106(4,2), Sub107(4,2)
	ComplexType Sub111(4), Sub112(4), Sub113(4), Sub114(4)
	ComplexType Sub115(4,4), Sub116(4), Sub117(4), Sub118(4,4)
	ComplexType Sub119(4), Sub120(4), Sub121(4,4), Sub122(4,4)
	ComplexType Sub123(4), Sub124(4,2), Sub125(4,2), Sub126(4)
	ComplexType Sub127(4), Sub128(4), Sub129(4), Sub130(4,4)
	ComplexType Sub131(4), Sub132(4), Sub133(4,4), Sub134(4)
	ComplexType Sub135(4), Sub136(4,4), Sub137(4,4), Sub157(2,2)
	ComplexType Sub159(2,2), Sub163(2,2), Sub167(2,2)
	ComplexType Sub169(2,2), Sub172(2,2), Sub176(2,2)
	ComplexType Sub177(2,2), Sub180(2,2), Sub181(2,2)
	ComplexType Sub182(2,2), Sub183(2,2), Sub184(2,2)
	ComplexType Sub185(2,2), Sub186(2,2), Sub188(2,2), Sub193(4)
	ComplexType Sub194(4), Sub195(4,4), Sub196(4), Sub197(4)
	ComplexType Sub198(4,4), Sub199(4,4), Sub200(4,4)
	ComplexType Sub201(4,4), Sub202(4,4), Sub203(4,4)
	ComplexType Sub205(4,4), Sub219(3), Sub220(3), Sub221(3)
	ComplexType Sub222(3), Sub223(3,2,2), Sub224(3), Sub225(3)
	ComplexType Sub226(3,2), Sub227(3), Sub228(3), Sub229(3,2)
	ComplexType Sub230(3,2,2), Sub231(3), Sub232(3), Sub233(3,2)
	ComplexType Sub234(3), Sub235(3), Sub236(3,2), Sub237(3,2,2)
	ComplexType Sub238(3), Sub239(3), Sub240(3,2,2)
	ComplexType Sub241(3,2,2), Sub242(3,2,2), Sub243(3,2,2)
	ComplexType Sub245(3), Sub246(3), Sub247(6,3), Sub248(3)
	ComplexType Sub249(3), Sub250(6,3), Sub251(6,6,3), Sub252(3)
	ComplexType Sub253(3,3), Sub254(6,3,3), Sub255(3)
	ComplexType Sub256(6,3,3), Sub257(6,3,3), Sub258(6,6,3,3)
	ComplexType Sub259(3), Sub260(3,3), Sub261(6,3,3), Sub262(3)
	ComplexType Sub263(6,3,3), Sub264(6,3,3), Sub265(6,6,3,3)
	ComplexType Sub266(6,6,3,3), Sub267(3,3), Sub268(3,3)
	ComplexType Sub269(6,6,3,3), Sub270(6,6,3,3)
	ComplexType Sub271(6,6,3,3), Sub274(6,6,3), Sub275(3)
	ComplexType Sub276(3,3), Sub277(6,3,3), Sub278(3)
	ComplexType Sub279(6,3,3), Sub280(6,3,3), Sub281(6,6,3,3)
	ComplexType Sub282(3), Sub283(3,3), Sub284(6,3,3), Sub285(3)
	ComplexType Sub286(6,3,3), Sub287(6,3,3), Sub288(6,6,3,3)
	ComplexType Sub289(6,6,3,3), Sub290(3,3), Sub291(3,3)
	ComplexType Sub292(6,6,3,3), Sub293(6,6,3,3)
	ComplexType Sub294(6,6,3,3), Sub297(3,3), Sub298(3,3)
	ComplexType Sub299(6,6,3,3), Sub300(3), Sub301(3,3)
	ComplexType Sub302(6,3,3), Sub303(3), Sub304(6,3,3)
	ComplexType Sub305(6,3,3), Sub306(6,6,3,3), Sub307(3)
	ComplexType Sub308(3,3), Sub309(6,3,3), Sub310(3)
	ComplexType Sub311(6,3,3), Sub312(6,3,3), Sub313(6,6,3,3)
	ComplexType Sub314(6,6,3,3), Sub315(3,3), Sub316(3,3)
	ComplexType Sub317(6,6,3,3), Sub318(6,6,3,3), Sub319(3,3)
	ComplexType Sub320(3,3), Sub321(6,6,3,3), Sub322(3)
	ComplexType Sub323(3,3), Sub324(6,3,3), Sub325(3)
	ComplexType Sub326(6,3,3), Sub327(6,3,3), Sub328(6,6,3,3)
	ComplexType Sub329(3), Sub330(3,3), Sub331(6,3,3), Sub332(3)
	ComplexType Sub333(6,3,3), Sub334(6,3,3), Sub335(6,6,3,3)
	ComplexType Sub336(6,6,3,3), Sub337(3,3), Sub338(3,3)
	ComplexType Sub339(6,6,3,3), Sub340(3,3), Sub341(3,3)
	ComplexType Sub342(6,6,3,3), Sub343(6,6,3,3,3,3), Sub85(2)
	ComplexType Sub88(2), Sub89(2,2), Sub92(2), Sub95(2)
	ComplexType Sub96(2,2), Sub99(2,2)
	common /hee_abbrev1s/ Opt1, Sub156, Sub158, Sub16, Sub17
	common /hee_abbrev1s/ Sub173, Sub174, Sub175, Sub178, Sub179
	common /hee_abbrev1s/ Sub18, Sub19, Sub20, Sub208, Sub209
	common /hee_abbrev1s/ Sub21, Sub215, Sub216, Sub217, Sub22
	common /hee_abbrev1s/ Sub23, Sub24, Sub47, Sub48, Sub49
	common /hee_abbrev1s/ Sub52, Sub53, Sub54, Sub55, Sub56
	common /hee_abbrev1s/ Sub62, Sub64, Sub66, Sub67, Sub68
	common /hee_abbrev1s/ Sub69, Sub70, Sub71, Sub72, Sub73
	common /hee_abbrev1s/ Sub74, Sub75, Sub76, Sub77, Sub78
	common /hee_abbrev1s/ Sub79, Sub80, Sub81, Sub82, Sub83
	common /hee_abbrev1s/ Sub84, Sub86, Sub87, Sub90, Sub91
	common /hee_abbrev1s/ Sub93, Sub94, Sub97, Sub98, Sub100
	common /hee_abbrev1s/ Sub101, Sub102, Sub103, Sub104, Sub105
	common /hee_abbrev1s/ Sub106, Sub107, Sub111, Sub112, Sub113
	common /hee_abbrev1s/ Sub114, Sub115, Sub116, Sub117, Sub118
	common /hee_abbrev1s/ Sub119, Sub120, Sub121, Sub122, Sub123
	common /hee_abbrev1s/ Sub124, Sub125, Sub126, Sub127, Sub128
	common /hee_abbrev1s/ Sub129, Sub130, Sub131, Sub132, Sub133
	common /hee_abbrev1s/ Sub134, Sub135, Sub136, Sub137, Sub157
	common /hee_abbrev1s/ Sub159, Sub163, Sub167, Sub169, Sub172
	common /hee_abbrev1s/ Sub176, Sub177, Sub180, Sub181, Sub182
	common /hee_abbrev1s/ Sub183, Sub184, Sub185, Sub186, Sub188
	common /hee_abbrev1s/ Sub193, Sub194, Sub195, Sub196, Sub197
	common /hee_abbrev1s/ Sub198, Sub199, Sub200, Sub201, Sub202
	common /hee_abbrev1s/ Sub203, Sub205, Sub219, Sub220, Sub221
	common /hee_abbrev1s/ Sub222, Sub223, Sub224, Sub225, Sub226
	common /hee_abbrev1s/ Sub227, Sub228, Sub229, Sub230, Sub231
	common /hee_abbrev1s/ Sub232, Sub233, Sub234, Sub235, Sub236
	common /hee_abbrev1s/ Sub237, Sub238, Sub239, Sub240, Sub241
	common /hee_abbrev1s/ Sub242, Sub243, Sub245, Sub246, Sub247
	common /hee_abbrev1s/ Sub248, Sub249, Sub250, Sub251, Sub252
	common /hee_abbrev1s/ Sub253, Sub254, Sub255, Sub256, Sub257
	common /hee_abbrev1s/ Sub258, Sub259, Sub260, Sub261, Sub262
	common /hee_abbrev1s/ Sub263, Sub264, Sub265, Sub266, Sub267
	common /hee_abbrev1s/ Sub268, Sub269, Sub270, Sub271, Sub274
	common /hee_abbrev1s/ Sub275, Sub276, Sub277, Sub278, Sub279
	common /hee_abbrev1s/ Sub280, Sub281, Sub282, Sub283, Sub284
	common /hee_abbrev1s/ Sub285, Sub286, Sub287, Sub288, Sub289
	common /hee_abbrev1s/ Sub290, Sub291, Sub292, Sub293, Sub294
	common /hee_abbrev1s/ Sub297, Sub298, Sub299, Sub300, Sub301
	common /hee_abbrev1s/ Sub302, Sub303, Sub304, Sub305, Sub306
	common /hee_abbrev1s/ Sub307, Sub308, Sub309, Sub310, Sub311
	common /hee_abbrev1s/ Sub312, Sub313, Sub314, Sub315, Sub316
	common /hee_abbrev1s/ Sub317, Sub318, Sub319, Sub320, Sub321
	common /hee_abbrev1s/ Sub322, Sub323, Sub324, Sub325, Sub326
	common /hee_abbrev1s/ Sub327, Sub328, Sub329, Sub330, Sub331
	common /hee_abbrev1s/ Sub332, Sub333, Sub334, Sub335, Sub336
	common /hee_abbrev1s/ Sub337, Sub338, Sub339, Sub340, Sub341
	common /hee_abbrev1s/ Sub342, Sub343, Sub85, Sub88, Sub89
	common /hee_abbrev1s/ Sub92, Sub95, Sub96, Sub99

	ComplexType F1, F2
	common /hee_abbrev0hel/ F1, F2

	ComplexType AbbSum1, AbbSum2, Sub1, Sub10, Sub11, Sub12
	ComplexType Sub13, Sub14, Sub15, Sub2, Sub210, Sub211
	ComplexType Sub212, Sub25, Sub26, Sub27, Sub28, Sub29, Sub3
	ComplexType Sub30, Sub31, Sub32, Sub33, Sub34, Sub35, Sub36
	ComplexType Sub37, Sub38, Sub39, Sub4, Sub40, Sub41, Sub42
	ComplexType Sub43, Sub44, Sub45, Sub46, Sub5, Sub50, Sub51
	ComplexType Sub57, Sub58, Sub59, Sub6, Sub60, Sub61, Sub63
	ComplexType Sub65, Sub7, Sub8, Sub9, Sub108(4,2,2)
	ComplexType Sub109(4,2,2), Sub110(4,2,2), Sub138(4,4,2)
	ComplexType Sub139(4,4,2), Sub140(4,4,2), Sub141(4,4,2)
	ComplexType Sub142(4,4,2), Sub143(4,4,2), Sub144(4,4,2)
	ComplexType Sub145(4,4,2), Sub146(4,4,2), Sub147(4,4,2)
	ComplexType Sub148(4,4,2), Sub149(4,4,2), Sub150(4,4,2)
	ComplexType Sub151(4,4,2), Sub152(4,4,2), Sub153(2)
	ComplexType Sub154(2), Sub155(2), Sub160(2,2), Sub161(2,2)
	ComplexType Sub162(2,2), Sub164(2,2), Sub165(2,2)
	ComplexType Sub166(2,2), Sub168(2,2), Sub170(2,2)
	ComplexType Sub171(2,2), Sub187(2,2), Sub189(2,2)
	ComplexType Sub190(2,2), Sub191(2,2), Sub192(2,2)
	ComplexType Sub204(4,4), Sub206(4,4), Sub207(4,4), Sub213(3)
	ComplexType Sub214(3), Sub218(3), Sub244(3,2,2)
	ComplexType Sub272(6,6,3,3,3), Sub273(6,6,3,3,3)
	ComplexType Sub295(6,6,3,3,3), Sub296(6,6,3,3,3)
	common /hee_abbrev1hel/ AbbSum1, AbbSum2, Sub1, Sub10, Sub11
	common /hee_abbrev1hel/ Sub12, Sub13, Sub14, Sub15, Sub2
	common /hee_abbrev1hel/ Sub210, Sub211, Sub212, Sub25, Sub26
	common /hee_abbrev1hel/ Sub27, Sub28, Sub29, Sub3, Sub30
	common /hee_abbrev1hel/ Sub31, Sub32, Sub33, Sub34, Sub35
	common /hee_abbrev1hel/ Sub36, Sub37, Sub38, Sub39, Sub4
	common /hee_abbrev1hel/ Sub40, Sub41, Sub42, Sub43, Sub44
	common /hee_abbrev1hel/ Sub45, Sub46, Sub5, Sub50, Sub51
	common /hee_abbrev1hel/ Sub57, Sub58, Sub59, Sub6, Sub60
	common /hee_abbrev1hel/ Sub61, Sub63, Sub65, Sub7, Sub8
	common /hee_abbrev1hel/ Sub9, Sub108, Sub109, Sub110, Sub138
	common /hee_abbrev1hel/ Sub139, Sub140, Sub141, Sub142
	common /hee_abbrev1hel/ Sub143, Sub144, Sub145, Sub146
	common /hee_abbrev1hel/ Sub147, Sub148, Sub149, Sub150
	common /hee_abbrev1hel/ Sub151, Sub152, Sub153, Sub154
	common /hee_abbrev1hel/ Sub155, Sub160, Sub161, Sub162
	common /hee_abbrev1hel/ Sub164, Sub165, Sub166, Sub168
	common /hee_abbrev1hel/ Sub170, Sub171, Sub187, Sub189
	common /hee_abbrev1hel/ Sub190, Sub191, Sub192, Sub204
	common /hee_abbrev1hel/ Sub206, Sub207, Sub213, Sub214
	common /hee_abbrev1hel/ Sub218, Sub244, Sub272, Sub273
	common /hee_abbrev1hel/ Sub295, Sub296

	ComplexType lint16, lint19, lint21, lint22, lint34, lint39
	ComplexType lint40, lint41, lint42, lint43, lint44, lint45
	ComplexType lint46, lint47, lint48, lint49, lint50, lint51
	ComplexType lint52, lint53, lint54, lint55, lint56, lint57
	ComplexType lint1(Ncc), lint10(Ncc), lint11(Ncc)
	ComplexType lint12(Ncc), lint13(Ncc), lint14(Ncc)
	ComplexType lint15(Ncc), lint17(Ncc), lint18(Ncc)
	ComplexType lint2(Ncc), lint20(Ncc), lint23(Ncc)
	ComplexType lint24(Ncc), lint25(Ncc), lint26(Ncc)
	ComplexType lint27(Ncc), lint28(Ncc), lint29(Ncc)
	ComplexType lint3(Ncc), lint30(Ncc), lint31(Ncc)
	ComplexType lint32(Ncc), lint33(Ncc), lint35(Ncc)
	ComplexType lint36(Ncc), lint37(Ncc), lint38(Ncc)
	ComplexType lint4(Ncc), lint5(Ncc), lint58(Ncc,4,2,2)
	ComplexType lint59(4,2), lint6(Ncc), lint60(Ncc,4,4,2)
	ComplexType lint61(Ncc,2), lint62(2), lint63(Ncc,2,2)
	ComplexType lint64(4), lint65(4,4), lint66(4,4), lint67(3)
	ComplexType lint68(3), lint69(3), lint7(Ncc), lint70(3)
	ComplexType lint71(3), lint72(3), lint73(3), lint74(3)
	ComplexType lint75(3), lint76(3), lint77(3), lint78(3)
	ComplexType lint79(3,2), lint8(Ncc), lint80(3,2,2)
	ComplexType lint81(3,2,2), lint82(6), lint83(6), lint84(6,6)
	ComplexType lint85(6,6), lint86(6,6), lint87(6,6), lint88(2)
	ComplexType lint89(2,2), lint9(Ncc), lint90(2,2)
	common /hee_loopint1s/ lint16, lint19, lint21, lint22, lint34
	common /hee_loopint1s/ lint39, lint40, lint41, lint42
	common /hee_loopint1s/ lint43, lint44, lint45, lint46
	common /hee_loopint1s/ lint47, lint48, lint49, lint50
	common /hee_loopint1s/ lint51, lint52, lint53, lint54
	common /hee_loopint1s/ lint55, lint56, lint57, lint1, lint10
	common /hee_loopint1s/ lint11, lint12, lint13, lint14
	common /hee_loopint1s/ lint15, lint17, lint18, lint2, lint20
	common /hee_loopint1s/ lint23, lint24, lint25, lint26
	common /hee_loopint1s/ lint27, lint28, lint29, lint3, lint30
	common /hee_loopint1s/ lint31, lint32, lint33, lint35
	common /hee_loopint1s/ lint36, lint37, lint38, lint4, lint5
	common /hee_loopint1s/ lint58, lint59, lint6, lint60, lint61
	common /hee_loopint1s/ lint62, lint63, lint64, lint65
	common /hee_loopint1s/ lint66, lint67, lint68, lint69, lint7
	common /hee_loopint1s/ lint70, lint71, lint72, lint73
	common /hee_loopint1s/ lint74, lint75, lint76, lint77
	common /hee_loopint1s/ lint78, lint79, lint8, lint80, lint81
	common /hee_loopint1s/ lint82, lint83, lint84, lint85
	common /hee_loopint1s/ lint86, lint87, lint88, lint89, lint9
	common /hee_loopint1s/ lint90

	integer seq(2), Hel(3)
	common /hee_helvars/ seq, Hel

	integer All4, All5, Cha4, Cha5, Gen4, Ind1, Ind2, Ind3, Ind4
	integer Neu4, Neu5, Sfe4, Sfe5
	common /hee_indices/ All4, All5, Cha4, Cha5, Gen4, Ind1, Ind2
	common /hee_indices/ Ind3, Ind4, Neu4, Neu5, Sfe4, Sfe5

	ComplexType Ctree(1), Cloop(1)
	common /hee_formfactors/ Ctree, Cloop

#endif
