****************************************************
*** subroutine dsansffsvs                        ***
*** fermion + fermion -> scalar + gauge boson in ***
*** s-channel scalar exchange (index k)          ***
*** 1 - arrow in, 2 - arrow out, k intermediate  ***
*** this code is computer generated by reduce    ***
*** and gentran.                                 ***
*** author: joakim edsjo, edsjo@physto.se        ***
****************************************************

      subroutine dsansffsvs(p,costheta,kp1,kp2,kpk,kp3,kp4)
      implicit none

      include 'dsmssm.h'
      include 'dsandiacom.h'
      integer kp1,kp2,kpk,kp3,kp4
      real*8 p,costheta
      complex*16 dh,gv2,ga2

      call dsankinvar(p,costheta,kp1,kp2,kpk,kp3,kp4)
      if (s.lt.(mp3+mp4)**2) return
      dh=1.0d0/dcmplx(mk**2-s,-width(kpk)*mk)
      gv2=gl(kp3,kp4,kpk)*
     &  (gl(kpk,kp2,kp1)+gr(kpk,kp2,kp1))
      ga2=gl(kp3,kp4,kpk)*
     &  (gl(kpk,kp2,kp1)-gr(kpk,kp2,kp1))

      if (kp3.eq.kgamma) then


      else

      aa(0,0,0,0)=aa(0,0,0,0)-(dsqrt(2.0d0)*(e1+e2+e3+e4)*dh*epl*ga2*
     . kk)/mp3
      aa(1,0,0,0)=aa(1,0,0,0)+(dsqrt(2.0d0)*(e1+e2+e3+e4)*dh*gv2*kk*
     . ppl)/mp3

      endif

      return

      end
