*********************************************************
*** subroutine dsansffvvv                             ***
*** fermion + fermion -> gauge boson + gauge boson in ***
*** s-channel gauge boson exchange (index k)          ***
*** 1 - arrow in, 2 - arrow out, k intermediate       ***
*** this code is computer generated by reduce         ***
*** and gentran.                                      ***
*** author: joakim edsjo, edsjo@physto.se             ***
*********************************************************

      subroutine dsansffvvv(p,costheta,kp1,kp2,kpk,kp3,kp4)
      implicit none

      include 'dsmssm.h'
      include 'dsandiacom.h'
      integer kp1,kp2,kpk,kp3,kp4
      real*8 p,costheta
      complex*16 dv,gv2,ga2

c      write(*,*) 'asffvvv called with',kp1,kp2,kpk,kp3,kp4,
c     &    p,costheta
      call dsankinvar(p,costheta,kp1,kp2,kpk,kp3,kp4)
      if (s.lt.(mp3+mp4)**2) return
      dv=1.0d0/dcmplx(mk**2-s,-width(kpk)*mk)
      gv2=gl(kpk,kp3,kp4)*
     &  (gl(kpk,kp2,kp1)+gr(kpk,kp2,kp1))
      ga2=gl(kpk,kp3,kp4)*
     &  (gl(kpk,kp2,kp1)-gr(kpk,kp2,kp1))
c      write(*,*) 'gv2 = ',gv2,' ga2 = ',ga2
c      write(*,*) 'gl(kpk,kp3,kp4) = ',gl(kpk,kp3,kp4)
c      write(*,*) 'gl(kpk,kp2,kp1) = ',gl(kpk,kp2,kp1)
c      write(*,*) 'gr(kpk,kp2,kp1) = ',gr(kpk,kp2,kp1)
      if (kpk.eq.kgamma) then
        if (kp3.eq.kgamma) then
          if (kp4.eq.kgamma) then

      aa(0,0,-1,-1)=aa(0,0,-1,-1)-(dsqrt(2.0d0)*((e3-e4)*emi+2.0d0*wd(
     . 1,0,0)*kk*pmi)*dv*ga2)
      aa(0,0,1,1)=aa(0,0,1,1)-(dsqrt(2.0d0)*((e3-e4)*emi+2.0d0*wd(1,0,
     . 0)*kk*pmi)*dv*ga2)
      aa(1,-1,-1,-1)=aa(1,-1,-1,-1)-(2.0d0*dsqrt(2.0d0)*(epl*gv2+ga2*
     . ppl)*wd(1,-1,0)*dv*kk)
      aa(1,-1,1,1)=aa(1,-1,1,1)-(2.0d0*dsqrt(2.0d0)*(epl*gv2+ga2*ppl)*
     . wd(1,-1,0)*dv*kk)
      aa(1,0,-1,-1)=aa(1,0,-1,-1)-(dsqrt(2.0d0)*((e3-e4)*pmi+2.0d0*wd(
     . 1,0,0)*emi*kk)*dv*gv2)
      aa(1,0,1,1)=aa(1,0,1,1)-(dsqrt(2.0d0)*((e3-e4)*pmi+2.0d0*wd(1,0,
     . 0)*emi*kk)*dv*gv2)
      aa(1,1,-1,-1)=aa(1,1,-1,-1)-(2.0d0*dsqrt(2.0d0)*(epl*gv2-(ga2*
     . ppl))*wd(1,1,0)*dv*kk)
      aa(1,1,1,1)=aa(1,1,1,1)-(2.0d0*dsqrt(2.0d0)*(epl*gv2-(ga2*ppl))*
     . wd(1,1,0)*dv*kk)

          else

      aa(0,0,-1,-1)=aa(0,0,-1,-1)-(dsqrt(2.0d0)*((e3-e4)*emi+2.0d0*wd(
     . 1,0,0)*kk*pmi)*dv*ga2)
      aa(0,0,-1,0)=aa(0,0,-1,0)-(dsqrt(2.0d0)*(e1+e2+e3+e4)*wd(1,0,-1
     . )*dv*ga2*kk*pmi)/mp4
      aa(0,0,1,0)=aa(0,0,1,0)-(dsqrt(2.0d0)*(e1+e2+e3+e4)*wd(1,0,1)*
     . dv*ga2*kk*pmi)/mp4
      aa(0,0,1,1)=aa(0,0,1,1)-(dsqrt(2.0d0)*((e3-e4)*emi+2.0d0*wd(1,0,
     . 0)*kk*pmi)*dv*ga2)
      aa(1,-1,-1,-1)=aa(1,-1,-1,-1)-(2.0d0*dsqrt(2.0d0)*(epl*gv2+ga2*
     . ppl)*wd(1,-1,0)*dv*kk)
      aa(1,-1,-1,0)=aa(1,-1,-1,0)-(dsqrt(2.0d0)*(e1+e2+e3+e4)*(epl*
     . gv2+ga2*ppl)*wd(1,-1,-1)*dv*kk)/mp4
      aa(1,-1,1,0)=aa(1,-1,1,0)-(dsqrt(2.0d0)*(e1+e2+e3+e4)*(epl*gv2+
     . ga2*ppl)*wd(1,-1,1)*dv*kk)/mp4
      aa(1,-1,1,1)=aa(1,-1,1,1)-(2.0d0*dsqrt(2.0d0)*(epl*gv2+ga2*ppl)*
     . wd(1,-1,0)*dv*kk)
      aa(1,0,-1,-1)=aa(1,0,-1,-1)-(dsqrt(2.0d0)*((e3-e4)*pmi+2.0d0*wd(
     . 1,0,0)*emi*kk)*dv*gv2)
      aa(1,0,-1,0)=aa(1,0,-1,0)-(dsqrt(2.0d0)*(e1+e2+e3+e4)*wd(1,0,-1
     . )*dv*emi*gv2*kk)/mp4
      aa(1,0,1,0)=aa(1,0,1,0)-(dsqrt(2.0d0)*(e1+e2+e3+e4)*wd(1,0,1)*
     . dv*emi*gv2*kk)/mp4
      aa(1,0,1,1)=aa(1,0,1,1)-(dsqrt(2.0d0)*((e3-e4)*pmi+2.0d0*wd(1,0,
     . 0)*emi*kk)*dv*gv2)
      aa(1,1,-1,-1)=aa(1,1,-1,-1)-(2.0d0*dsqrt(2.0d0)*(epl*gv2-(ga2*
     . ppl))*wd(1,1,0)*dv*kk)
      aa(1,1,-1,0)=aa(1,1,-1,0)-(dsqrt(2.0d0)*(e1+e2+e3+e4)*(epl*gv2-
     . (ga2*ppl))*wd(1,1,-1)*dv*kk)/mp4
      aa(1,1,1,0)=aa(1,1,1,0)-(dsqrt(2.0d0)*(e1+e2+e3+e4)*(epl*gv2-(
     . ga2*ppl))*wd(1,1,1)*dv*kk)/mp4
      aa(1,1,1,1)=aa(1,1,1,1)-(2.0d0*dsqrt(2.0d0)*(epl*gv2-(ga2*ppl))*
     . wd(1,1,0)*dv*kk)

          endif
        else
          if (kp4.eq.kgamma) then

      aa(0,0,-1,-1)=aa(0,0,-1,-1)-(dsqrt(2.0d0)*((e3-e4)*emi+2.0d0*wd(
     . 1,0,0)*kk*pmi)*dv*ga2)
      aa(0,0,0,-1)=aa(0,0,0,-1)-(dsqrt(2.0d0)*(e1+e2+e3+e4)*wd(1,0,1)
     . *dv*ga2*kk*pmi)/mp3
      aa(0,0,0,1)=aa(0,0,0,1)-(dsqrt(2.0d0)*(e1+e2+e3+e4)*wd(1,0,-1)*
     . dv*ga2*kk*pmi)/mp3
      aa(0,0,1,1)=aa(0,0,1,1)-(dsqrt(2.0d0)*((e3-e4)*emi+2.0d0*wd(1,0,
     . 0)*kk*pmi)*dv*ga2)
      aa(1,-1,-1,-1)=aa(1,-1,-1,-1)-(2.0d0*dsqrt(2.0d0)*(epl*gv2+ga2*
     . ppl)*wd(1,-1,0)*dv*kk)
      aa(1,-1,0,-1)=aa(1,-1,0,-1)-(dsqrt(2.0d0)*(e1+e2+e3+e4)*(epl*
     . gv2+ga2*ppl)*wd(1,-1,1)*dv*kk)/mp3
      aa(1,-1,0,1)=aa(1,-1,0,1)-(dsqrt(2.0d0)*(e1+e2+e3+e4)*(epl*gv2+
     . ga2*ppl)*wd(1,-1,-1)*dv*kk)/mp3
      aa(1,-1,1,1)=aa(1,-1,1,1)-(2.0d0*dsqrt(2.0d0)*(epl*gv2+ga2*ppl)*
     . wd(1,-1,0)*dv*kk)
      aa(1,0,-1,-1)=aa(1,0,-1,-1)-(dsqrt(2.0d0)*((e3-e4)*pmi+2.0d0*wd(
     . 1,0,0)*emi*kk)*dv*gv2)
      aa(1,0,0,-1)=aa(1,0,0,-1)-(dsqrt(2.0d0)*(e1+e2+e3+e4)*wd(1,0,1)
     . *dv*emi*gv2*kk)/mp3
      aa(1,0,0,1)=aa(1,0,0,1)-(dsqrt(2.0d0)*(e1+e2+e3+e4)*wd(1,0,-1)*
     . dv*emi*gv2*kk)/mp3
      aa(1,0,1,1)=aa(1,0,1,1)-(dsqrt(2.0d0)*((e3-e4)*pmi+2.0d0*wd(1,0,
     . 0)*emi*kk)*dv*gv2)
      aa(1,1,-1,-1)=aa(1,1,-1,-1)-(2.0d0*dsqrt(2.0d0)*(epl*gv2-(ga2*
     . ppl))*wd(1,1,0)*dv*kk)
      aa(1,1,0,-1)=aa(1,1,0,-1)-(dsqrt(2.0d0)*(e1+e2+e3+e4)*(epl*gv2-
     . (ga2*ppl))*wd(1,1,1)*dv*kk)/mp3
      aa(1,1,0,1)=aa(1,1,0,1)-(dsqrt(2.0d0)*(e1+e2+e3+e4)*(epl*gv2-(
     . ga2*ppl))*wd(1,1,-1)*dv*kk)/mp3
      aa(1,1,1,1)=aa(1,1,1,1)-(2.0d0*dsqrt(2.0d0)*(epl*gv2-(ga2*ppl))*
     . wd(1,1,0)*dv*kk)

          else

      aa(0,0,-1,-1)=aa(0,0,-1,-1)-(dsqrt(2.0d0)*((e3-e4)*emi+2.0d0*wd(
     . 1,0,0)*kk*pmi)*dv*ga2)
      aa(0,0,-1,0)=aa(0,0,-1,0)-(dsqrt(2.0d0)*(e1+e2+e3+e4)*wd(1,0,-1
     . )*dv*ga2*kk*pmi)/mp4
      aa(0,0,0,-1)=aa(0,0,0,-1)-(dsqrt(2.0d0)*(e1+e2+e3+e4)*wd(1,0,1)
     . *dv*ga2*kk*pmi)/mp3
      aa(0,0,0,0)=aa(0,0,0,0)-(dsqrt(2.0d0)*(((e1+e2)*(e3+e4)+e3**2+
     . e4**2-(2.0d0*kk**2))*wd(1,0,0)*kk*pmi-((e3*e4+kk**2)*(e3-e4)*
     . emi))*dv*ga2)/(mp3*mp4)
      aa(0,0,0,1)=aa(0,0,0,1)-(dsqrt(2.0d0)*(e1+e2+e3+e4)*wd(1,0,-1)*
     . dv*ga2*kk*pmi)/mp3
      aa(0,0,1,0)=aa(0,0,1,0)-(dsqrt(2.0d0)*(e1+e2+e3+e4)*wd(1,0,1)*
     . dv*ga2*kk*pmi)/mp4
      aa(0,0,1,1)=aa(0,0,1,1)-(dsqrt(2.0d0)*((e3-e4)*emi+2.0d0*wd(1,0,
     . 0)*kk*pmi)*dv*ga2)
      aa(1,-1,-1,-1)=aa(1,-1,-1,-1)-(2.0d0*dsqrt(2.0d0)*(epl*gv2+ga2*
     . ppl)*wd(1,-1,0)*dv*kk)
      aa(1,-1,-1,0)=aa(1,-1,-1,0)-(dsqrt(2.0d0)*(e1+e2+e3+e4)*(epl*
     . gv2+ga2*ppl)*wd(1,-1,-1)*dv*kk)/mp4
      aa(1,-1,0,-1)=aa(1,-1,0,-1)-(dsqrt(2.0d0)*(e1+e2+e3+e4)*(epl*
     . gv2+ga2*ppl)*wd(1,-1,1)*dv*kk)/mp3
      aa(1,-1,0,0)=aa(1,-1,0,0)-(dsqrt(2.0d0)*((e1+e2)*(e3+e4)+e3**2+
     . e4**2-(2.0d0*kk**2))*(epl*gv2+ga2*ppl)*wd(1,-1,0)*dv*kk)/(mp3*
     . mp4)
      aa(1,-1,0,1)=aa(1,-1,0,1)-(dsqrt(2.0d0)*(e1+e2+e3+e4)*(epl*gv2+
     . ga2*ppl)*wd(1,-1,-1)*dv*kk)/mp3
      aa(1,-1,1,0)=aa(1,-1,1,0)-(dsqrt(2.0d0)*(e1+e2+e3+e4)*(epl*gv2+
     . ga2*ppl)*wd(1,-1,1)*dv*kk)/mp4
      aa(1,-1,1,1)=aa(1,-1,1,1)-(2.0d0*dsqrt(2.0d0)*(epl*gv2+ga2*ppl)*
     . wd(1,-1,0)*dv*kk)
      aa(1,0,-1,-1)=aa(1,0,-1,-1)-(dsqrt(2.0d0)*((e3-e4)*pmi+2.0d0*wd(
     . 1,0,0)*emi*kk)*dv*gv2)
      aa(1,0,-1,0)=aa(1,0,-1,0)-(dsqrt(2.0d0)*(e1+e2+e3+e4)*wd(1,0,-1
     . )*dv*emi*gv2*kk)/mp4
      aa(1,0,0,-1)=aa(1,0,0,-1)-(dsqrt(2.0d0)*(e1+e2+e3+e4)*wd(1,0,1)
     . *dv*emi*gv2*kk)/mp3
      aa(1,0,0,0)=aa(1,0,0,0)-(dsqrt(2.0d0)*(((e1+e2)*(e3+e4)+e3**2+
     . e4**2-(2.0d0*kk**2))*wd(1,0,0)*emi*kk-((e3*e4+kk**2)*(e3-e4)*
     . pmi))*dv*gv2)/(mp3*mp4)
      aa(1,0,0,1)=aa(1,0,0,1)-(dsqrt(2.0d0)*(e1+e2+e3+e4)*wd(1,0,-1)*
     . dv*emi*gv2*kk)/mp3
      aa(1,0,1,0)=aa(1,0,1,0)-(dsqrt(2.0d0)*(e1+e2+e3+e4)*wd(1,0,1)*
     . dv*emi*gv2*kk)/mp4
      aa(1,0,1,1)=aa(1,0,1,1)-(dsqrt(2.0d0)*((e3-e4)*pmi+2.0d0*wd(1,0,
     . 0)*emi*kk)*dv*gv2)
      aa(1,1,-1,-1)=aa(1,1,-1,-1)-(2.0d0*dsqrt(2.0d0)*(epl*gv2-(ga2*
     . ppl))*wd(1,1,0)*dv*kk)
      aa(1,1,-1,0)=aa(1,1,-1,0)-(dsqrt(2.0d0)*(e1+e2+e3+e4)*(epl*gv2-
     . (ga2*ppl))*wd(1,1,-1)*dv*kk)/mp4
      aa(1,1,0,-1)=aa(1,1,0,-1)-(dsqrt(2.0d0)*(e1+e2+e3+e4)*(epl*gv2-
     . (ga2*ppl))*wd(1,1,1)*dv*kk)/mp3
      aa(1,1,0,0)=aa(1,1,0,0)-(dsqrt(2.0d0)*((e1+e2)*(e3+e4)+e3**2+e4
     . **2-(2.0d0*kk**2))*(epl*gv2-(ga2*ppl))*wd(1,1,0)*dv*kk)/(mp3*
     . mp4)
      aa(1,1,0,1)=aa(1,1,0,1)-(dsqrt(2.0d0)*(e1+e2+e3+e4)*(epl*gv2-(
     . ga2*ppl))*wd(1,1,-1)*dv*kk)/mp3
      aa(1,1,1,0)=aa(1,1,1,0)-(dsqrt(2.0d0)*(e1+e2+e3+e4)*(epl*gv2-(
     . ga2*ppl))*wd(1,1,1)*dv*kk)/mp4
      aa(1,1,1,1)=aa(1,1,1,1)-(2.0d0*dsqrt(2.0d0)*(epl*gv2-(ga2*ppl))*
     . wd(1,1,0)*dv*kk)

          endif
        endif
      else
        if (kp3.eq.kgamma) then
          if (kp4.eq.kgamma) then

      aa(0,0,-1,-1)=aa(0,0,-1,-1)+(dsqrt(2.0d0)*((e1+e2+mk)*(e1+e2-mk)
     . *(e3-e4)*emi-(2.0d0*wd(1,0,0)*kk*mk**2*pmi))*dv*ga2)/mk**2
      aa(0,0,1,1)=aa(0,0,1,1)+(dsqrt(2.0d0)*((e1+e2+mk)*(e1+e2-mk)*(e3
     . -e4)*emi-(2.0d0*wd(1,0,0)*kk*mk**2*pmi))*dv*ga2)/mk**2
      aa(1,-1,-1,-1)=aa(1,-1,-1,-1)-(2.0d0*dsqrt(2.0d0)*(epl*gv2+ga2*
     . ppl)*wd(1,-1,0)*dv*kk)
      aa(1,-1,1,1)=aa(1,-1,1,1)-(2.0d0*dsqrt(2.0d0)*(epl*gv2+ga2*ppl)*
     . wd(1,-1,0)*dv*kk)
      aa(1,0,-1,-1)=aa(1,0,-1,-1)+(dsqrt(2.0d0)*((e1+e2+mk)*(e1+e2-mk)
     . *(e3-e4)*pmi-(2.0d0*wd(1,0,0)*emi*kk*mk**2))*dv*gv2)/mk**2
      aa(1,0,1,1)=aa(1,0,1,1)+(dsqrt(2.0d0)*((e1+e2+mk)*(e1+e2-mk)*(e3
     . -e4)*pmi-(2.0d0*wd(1,0,0)*emi*kk*mk**2))*dv*gv2)/mk**2
      aa(1,1,-1,-1)=aa(1,1,-1,-1)-(2.0d0*dsqrt(2.0d0)*(epl*gv2-(ga2*
     . ppl))*wd(1,1,0)*dv*kk)
      aa(1,1,1,1)=aa(1,1,1,1)-(2.0d0*dsqrt(2.0d0)*(epl*gv2-(ga2*ppl))*
     . wd(1,1,0)*dv*kk)

          else

      aa(0,0,-1,-1)=aa(0,0,-1,-1)+(dsqrt(2.0d0)*((e1+e2+mk)*(e1+e2-mk)
     . *(e3-e4)*emi-(2.0d0*wd(1,0,0)*kk*mk**2*pmi))*dv*ga2)/mk**2
      aa(0,0,-1,0)=aa(0,0,-1,0)-(dsqrt(2.0d0)*(e1+e2+e3+e4)*wd(1,0,-1
     . )*dv*ga2*kk*pmi)/mp4
      aa(0,0,1,0)=aa(0,0,1,0)-(dsqrt(2.0d0)*(e1+e2+e3+e4)*wd(1,0,1)*
     . dv*ga2*kk*pmi)/mp4
      aa(0,0,1,1)=aa(0,0,1,1)+(dsqrt(2.0d0)*((e1+e2+mk)*(e1+e2-mk)*(e3
     . -e4)*emi-(2.0d0*wd(1,0,0)*kk*mk**2*pmi))*dv*ga2)/mk**2
      aa(1,-1,-1,-1)=aa(1,-1,-1,-1)-(2.0d0*dsqrt(2.0d0)*(epl*gv2+ga2*
     . ppl)*wd(1,-1,0)*dv*kk)
      aa(1,-1,-1,0)=aa(1,-1,-1,0)-(dsqrt(2.0d0)*(e1+e2+e3+e4)*(epl*
     . gv2+ga2*ppl)*wd(1,-1,-1)*dv*kk)/mp4
      aa(1,-1,1,0)=aa(1,-1,1,0)-(dsqrt(2.0d0)*(e1+e2+e3+e4)*(epl*gv2+
     . ga2*ppl)*wd(1,-1,1)*dv*kk)/mp4
      aa(1,-1,1,1)=aa(1,-1,1,1)-(2.0d0*dsqrt(2.0d0)*(epl*gv2+ga2*ppl)*
     . wd(1,-1,0)*dv*kk)
      aa(1,0,-1,-1)=aa(1,0,-1,-1)+(dsqrt(2.0d0)*((e1+e2+mk)*(e1+e2-mk)
     . *(e3-e4)*pmi-(2.0d0*wd(1,0,0)*emi*kk*mk**2))*dv*gv2)/mk**2
      aa(1,0,-1,0)=aa(1,0,-1,0)-(dsqrt(2.0d0)*(e1+e2+e3+e4)*wd(1,0,-1
     . )*dv*emi*gv2*kk)/mp4
      aa(1,0,1,0)=aa(1,0,1,0)-(dsqrt(2.0d0)*(e1+e2+e3+e4)*wd(1,0,1)*
     . dv*emi*gv2*kk)/mp4
      aa(1,0,1,1)=aa(1,0,1,1)+(dsqrt(2.0d0)*((e1+e2+mk)*(e1+e2-mk)*(e3
     . -e4)*pmi-(2.0d0*wd(1,0,0)*emi*kk*mk**2))*dv*gv2)/mk**2
      aa(1,1,-1,-1)=aa(1,1,-1,-1)-(2.0d0*dsqrt(2.0d0)*(epl*gv2-(ga2*
     . ppl))*wd(1,1,0)*dv*kk)
      aa(1,1,-1,0)=aa(1,1,-1,0)-(dsqrt(2.0d0)*(e1+e2+e3+e4)*(epl*gv2-
     . (ga2*ppl))*wd(1,1,-1)*dv*kk)/mp4
      aa(1,1,1,0)=aa(1,1,1,0)-(dsqrt(2.0d0)*(e1+e2+e3+e4)*(epl*gv2-(
     . ga2*ppl))*wd(1,1,1)*dv*kk)/mp4
      aa(1,1,1,1)=aa(1,1,1,1)-(2.0d0*dsqrt(2.0d0)*(epl*gv2-(ga2*ppl))*
     . wd(1,1,0)*dv*kk)

          endif
        else
          if (kp4.eq.kgamma) then

      aa(0,0,-1,-1)=aa(0,0,-1,-1)+(dsqrt(2.0d0)*((e1+e2+mk)*(e1+e2-mk)
     . *(e3-e4)*emi-(2.0d0*wd(1,0,0)*kk*mk**2*pmi))*dv*ga2)/mk**2
      aa(0,0,0,-1)=aa(0,0,0,-1)-(dsqrt(2.0d0)*(e1+e2+e3+e4)*wd(1,0,1)
     . *dv*ga2*kk*pmi)/mp3
      aa(0,0,0,1)=aa(0,0,0,1)-(dsqrt(2.0d0)*(e1+e2+e3+e4)*wd(1,0,-1)*
     . dv*ga2*kk*pmi)/mp3
      aa(0,0,1,1)=aa(0,0,1,1)+(dsqrt(2.0d0)*((e1+e2+mk)*(e1+e2-mk)*(e3
     . -e4)*emi-(2.0d0*wd(1,0,0)*kk*mk**2*pmi))*dv*ga2)/mk**2
      aa(1,-1,-1,-1)=aa(1,-1,-1,-1)-(2.0d0*dsqrt(2.0d0)*(epl*gv2+ga2*
     . ppl)*wd(1,-1,0)*dv*kk)
      aa(1,-1,0,-1)=aa(1,-1,0,-1)-(dsqrt(2.0d0)*(e1+e2+e3+e4)*(epl*
     . gv2+ga2*ppl)*wd(1,-1,1)*dv*kk)/mp3
      aa(1,-1,0,1)=aa(1,-1,0,1)-(dsqrt(2.0d0)*(e1+e2+e3+e4)*(epl*gv2+
     . ga2*ppl)*wd(1,-1,-1)*dv*kk)/mp3
      aa(1,-1,1,1)=aa(1,-1,1,1)-(2.0d0*dsqrt(2.0d0)*(epl*gv2+ga2*ppl)*
     . wd(1,-1,0)*dv*kk)
      aa(1,0,-1,-1)=aa(1,0,-1,-1)+(dsqrt(2.0d0)*((e1+e2+mk)*(e1+e2-mk)
     . *(e3-e4)*pmi-(2.0d0*wd(1,0,0)*emi*kk*mk**2))*dv*gv2)/mk**2
      aa(1,0,0,-1)=aa(1,0,0,-1)-(dsqrt(2.0d0)*(e1+e2+e3+e4)*wd(1,0,1)
     . *dv*emi*gv2*kk)/mp3
      aa(1,0,0,1)=aa(1,0,0,1)-(dsqrt(2.0d0)*(e1+e2+e3+e4)*wd(1,0,-1)*
     . dv*emi*gv2*kk)/mp3
      aa(1,0,1,1)=aa(1,0,1,1)+(dsqrt(2.0d0)*((e1+e2+mk)*(e1+e2-mk)*(e3
     . -e4)*pmi-(2.0d0*wd(1,0,0)*emi*kk*mk**2))*dv*gv2)/mk**2
      aa(1,1,-1,-1)=aa(1,1,-1,-1)-(2.0d0*dsqrt(2.0d0)*(epl*gv2-(ga2*
     . ppl))*wd(1,1,0)*dv*kk)
      aa(1,1,0,-1)=aa(1,1,0,-1)-(dsqrt(2.0d0)*(e1+e2+e3+e4)*(epl*gv2-
     . (ga2*ppl))*wd(1,1,1)*dv*kk)/mp3
      aa(1,1,0,1)=aa(1,1,0,1)-(dsqrt(2.0d0)*(e1+e2+e3+e4)*(epl*gv2-(
     . ga2*ppl))*wd(1,1,-1)*dv*kk)/mp3
      aa(1,1,1,1)=aa(1,1,1,1)-(2.0d0*dsqrt(2.0d0)*(epl*gv2-(ga2*ppl))*
     . wd(1,1,0)*dv*kk)

          else

      aa(0,0,-1,-1)=aa(0,0,-1,-1)+(dsqrt(2.0d0)*((e1+e2+mk)*(e1+e2-mk)
     . *(e3-e4)*emi-(2.0d0*wd(1,0,0)*kk*mk**2*pmi))*dv*ga2)/mk**2
      aa(0,0,-1,0)=aa(0,0,-1,0)-(dsqrt(2.0d0)*(e1+e2+e3+e4)*wd(1,0,-1
     . )*dv*ga2*kk*pmi)/mp4
      aa(0,0,0,-1)=aa(0,0,0,-1)-(dsqrt(2.0d0)*(e1+e2+e3+e4)*wd(1,0,1)
     . *dv*ga2*kk*pmi)/mp3
      aa(0,0,0,0)=aa(0,0,0,0)-(dsqrt(2.0d0)*(((e1+e2)*(e3+e4)+e3**2+
     . e4**2-(2.0d0*kk**2))*wd(1,0,0)*kk*mk**2*pmi+(e1+e2+mk)*(e1+e2-
     . mk)*(e3*e4+kk**2)*(e3-e4)*emi)*dv*ga2)/(mk**2*mp3*mp4)
      aa(0,0,0,1)=aa(0,0,0,1)-(dsqrt(2.0d0)*(e1+e2+e3+e4)*wd(1,0,-1)*
     . dv*ga2*kk*pmi)/mp3
      aa(0,0,1,0)=aa(0,0,1,0)-(dsqrt(2.0d0)*(e1+e2+e3+e4)*wd(1,0,1)*
     . dv*ga2*kk*pmi)/mp4
      aa(0,0,1,1)=aa(0,0,1,1)+(dsqrt(2.0d0)*((e1+e2+mk)*(e1+e2-mk)*(e3
     . -e4)*emi-(2.0d0*wd(1,0,0)*kk*mk**2*pmi))*dv*ga2)/mk**2
      aa(1,-1,-1,-1)=aa(1,-1,-1,-1)-(2.0d0*dsqrt(2.0d0)*(epl*gv2+ga2*
     . ppl)*wd(1,-1,0)*dv*kk)
      aa(1,-1,-1,0)=aa(1,-1,-1,0)-(dsqrt(2.0d0)*(e1+e2+e3+e4)*(epl*
     . gv2+ga2*ppl)*wd(1,-1,-1)*dv*kk)/mp4
      aa(1,-1,0,-1)=aa(1,-1,0,-1)-(dsqrt(2.0d0)*(e1+e2+e3+e4)*(epl*
     . gv2+ga2*ppl)*wd(1,-1,1)*dv*kk)/mp3
      aa(1,-1,0,0)=aa(1,-1,0,0)-(dsqrt(2.0d0)*((e1+e2)*(e3+e4)+e3**2+
     . e4**2-(2.0d0*kk**2))*(epl*gv2+ga2*ppl)*wd(1,-1,0)*dv*kk)/(mp3*
     . mp4)
      aa(1,-1,0,1)=aa(1,-1,0,1)-(dsqrt(2.0d0)*(e1+e2+e3+e4)*(epl*gv2+
     . ga2*ppl)*wd(1,-1,-1)*dv*kk)/mp3
      aa(1,-1,1,0)=aa(1,-1,1,0)-(dsqrt(2.0d0)*(e1+e2+e3+e4)*(epl*gv2+
     . ga2*ppl)*wd(1,-1,1)*dv*kk)/mp4
      aa(1,-1,1,1)=aa(1,-1,1,1)-(2.0d0*dsqrt(2.0d0)*(epl*gv2+ga2*ppl)*
     . wd(1,-1,0)*dv*kk)
      aa(1,0,-1,-1)=aa(1,0,-1,-1)+(dsqrt(2.0d0)*((e1+e2+mk)*(e1+e2-mk)
     . *(e3-e4)*pmi-(2.0d0*wd(1,0,0)*emi*kk*mk**2))*dv*gv2)/mk**2
      aa(1,0,-1,0)=aa(1,0,-1,0)-(dsqrt(2.0d0)*(e1+e2+e3+e4)*wd(1,0,-1
     . )*dv*emi*gv2*kk)/mp4
      aa(1,0,0,-1)=aa(1,0,0,-1)-(dsqrt(2.0d0)*(e1+e2+e3+e4)*wd(1,0,1)
     . *dv*emi*gv2*kk)/mp3
      aa(1,0,0,0)=aa(1,0,0,0)-(dsqrt(2.0d0)*(((e1+e2)*(e3+e4)+e3**2+
     . e4**2-(2.0d0*kk**2))*wd(1,0,0)*emi*kk*mk**2+(e1+e2+mk)*(e1+e2-
     . mk)*(e3*e4+kk**2)*(e3-e4)*pmi)*dv*gv2)/(mk**2*mp3*mp4)
      aa(1,0,0,1)=aa(1,0,0,1)-(dsqrt(2.0d0)*(e1+e2+e3+e4)*wd(1,0,-1)*
     . dv*emi*gv2*kk)/mp3
      aa(1,0,1,0)=aa(1,0,1,0)-(dsqrt(2.0d0)*(e1+e2+e3+e4)*wd(1,0,1)*
     . dv*emi*gv2*kk)/mp4
      aa(1,0,1,1)=aa(1,0,1,1)+(dsqrt(2.0d0)*((e1+e2+mk)*(e1+e2-mk)*(e3
     . -e4)*pmi-(2.0d0*wd(1,0,0)*emi*kk*mk**2))*dv*gv2)/mk**2
      aa(1,1,-1,-1)=aa(1,1,-1,-1)-(2.0d0*dsqrt(2.0d0)*(epl*gv2-(ga2*
     . ppl))*wd(1,1,0)*dv*kk)
      aa(1,1,-1,0)=aa(1,1,-1,0)-(dsqrt(2.0d0)*(e1+e2+e3+e4)*(epl*gv2-
     . (ga2*ppl))*wd(1,1,-1)*dv*kk)/mp4
      aa(1,1,0,-1)=aa(1,1,0,-1)-(dsqrt(2.0d0)*(e1+e2+e3+e4)*(epl*gv2-
     . (ga2*ppl))*wd(1,1,1)*dv*kk)/mp3
      aa(1,1,0,0)=aa(1,1,0,0)-(dsqrt(2.0d0)*((e1+e2)*(e3+e4)+e3**2+e4
     . **2-(2.0d0*kk**2))*(epl*gv2-(ga2*ppl))*wd(1,1,0)*dv*kk)/(mp3*
     . mp4)
      aa(1,1,0,1)=aa(1,1,0,1)-(dsqrt(2.0d0)*(e1+e2+e3+e4)*(epl*gv2-(
     . ga2*ppl))*wd(1,1,-1)*dv*kk)/mp3
      aa(1,1,1,0)=aa(1,1,1,0)-(dsqrt(2.0d0)*(e1+e2+e3+e4)*(epl*gv2-(
     . ga2*ppl))*wd(1,1,1)*dv*kk)/mp4
      aa(1,1,1,1)=aa(1,1,1,1)-(2.0d0*dsqrt(2.0d0)*(epl*gv2-(ga2*ppl))*
     . wd(1,1,0)*dv*kk)

          endif
        endif
      endif

      return

      end











