****************************************************
*** subroutine dsansffsss                        ***
*** fermion + fermion -> scalar + scalar in      ***
*** s-channel scalar exchange (index k)          ***
*** 1 - arrow in, 2 - arrow out, k intermediate  ***
*** this code is computer generated by reduce    ***
*** and gentran.                                 ***
*** author: joakim edsjo, edsjo@physto.se        ***
****************************************************

      subroutine dsansffsss(p,costheta,kp1,kp2,kpk,kp3,kp4)
      implicit none

      include 'dsmssm.h'
      include 'dsandiacom.h'
      integer kp1,kp2,kpk,kp3,kp4
      real*8 p,costheta
      complex*16 dh,gv2,ga2

      call dsankinvar(p,costheta,kp1,kp2,kpk,kp3,kp4)
      if (s.lt.(mp3+mp4)**2) return
      dh=1.0d0/dcmplx(mk**2-s,-width(kpk)*mk)
      gv2=gl(kpk,kp4,kp3)*
     &  (gl(kpk,kp2,kp1)+gr(kpk,kp2,kp1))
      ga2=gl(kpk,kp4,kp3)*
     &  (gl(kpk,kp2,kp1)-gr(kpk,kp2,kp1))

      aa(0,0,0,0)=aa(0,0,0,0)-(dsqrt(2.0d0)*dh*epl*ga2*mw)
      aa(1,0,0,0)=aa(1,0,0,0)+dsqrt(2.0d0)*dh*gv2*mw*ppl

      return

      end
