****************************************************
*** subroutine dsantfffssex                      ***
*** fermion + fermion -> scalar + scalar in      ***
*** t-channel fermion exchange (index k)         ***
*** label 3 & 4 exchanged compared to tfffss     ***
*** 1 - arrow in, 2 - arrow out, k intermediate  ***
*** this code is computer generated by reduce    ***
*** and gentran.                                 ***
*** author: joakim edsjo, edsjo@physto.se        ***
****************************************************

      subroutine dsantfffssex(p,costheta,kp1,kp2,kpk,kp3,kp4)
      implicit none

      include 'dsmssm.h'
      include 'dsandiacom.h'
      integer kp1,kp2,kpk,kp3,kp4
      real*8 p,costheta
      complex*16 dt,gp2,gm2,gx2,gy2

      call dsankinvar(p,costheta,kp1,kp2,kpk,kp3,kp4)
      if (s.lt.(mp3+mp4)**2) return
      dt=1.0d0/dcmplx(mk**2-u,-width(kpk)*mk)
      gp2=gl(kp3,kp2,kpk)*gl(kp4,kpk,kp1)+
     &    gr(kp3,kp2,kpk)*gr(kp4,kpk,kp1)
      gm2=gl(kp3,kp2,kpk)*gl(kp4,kpk,kp1)-
     &    gr(kp3,kp2,kpk)*gr(kp4,kpk,kp1)
      gx2=gl(kp3,kp2,kpk)*gr(kp4,kpk,kp1)+
     &    gr(kp3,kp2,kpk)*gl(kp4,kpk,kp1)
      gy2=gl(kp3,kp2,kpk)*gr(kp4,kpk,kp1)-
     &    gr(kp3,kp2,kpk)*gl(kp4,kpk,kp1)

      aa(0,0,0,0)=aa(0,0,0,0)-(dsqrt(2.0d0)*(wd(1,0,0)*gy2*kk*pmi+e1*
     . emi*gy2-(e4*emi*gy2)+epl*gm2*mk+gy2*pmi*pp)*dt)
      aa(1,-1,0,0)=aa(1,-1,0,0)+dsqrt(2.0d0)*(epl*gx2-(gy2*ppl))*wd(1,
     . -1,0)*dt*kk
      aa(1,0,0,0)=aa(1,0,0,0)+dsqrt(2.0d0)*(wd(1,0,0)*emi*gx2*kk+e1*
     . gx2*pmi-(e4*gx2*pmi)+emi*gx2*pp+gp2*mk*ppl)*dt
      aa(1,1,0,0)=aa(1,1,0,0)+dsqrt(2.0d0)*(epl*gx2+gy2*ppl)*wd(1,1,0)
     . *dt*kk

      return

      end
