*********************************************************
*** subroutine dsanufffvv                             ***
*** fermion + fermion -> gauge boson + gauge boson in ***
*** u-channel fermion exchange (index k)              ***
*** 1 - arrow in, 2 - arrow out, k intermediate       ***
*** this code is computer generated by reduce         ***
*** and gentran.                                      ***
*** author: joakim edsjo, edsjo@physto.se             ***
*********************************************************

      subroutine dsanufffvv(p,costheta,kp1,kp2,kpk,kp3,kp4)
      implicit none

      include 'dsmssm.h'
      include 'dsandiacom.h'
      integer kp1,kp2,kpk,kp3,kp4
      real*8 p,costheta
      complex*16 du,gp2,gm2,gx2,gy2

      call dsankinvar(p,costheta,kp1,kp2,kpk,kp3,kp4)
      if (s.lt.(mp3+mp4)**2) return
      du=1.0d0/dcmplx(mk**2-u,-width(kpk)*mk)
      gp2=gl(kp3,kpk,kp2)*gl(kp4,kp1,kpk)+
     &   gr(kp3,kpk,kp2)*gr(kp4,kp1,kpk)
      gm2=gl(kp3,kpk,kp2)*gl(kp4,kp1,kpk)-
     &   gr(kp3,kpk,kp2)*gr(kp4,kp1,kpk)
      gx2=gl(kp3,kpk,kp2)*gr(kp4,kp1,kpk)+
     &   gr(kp3,kpk,kp2)*gl(kp4,kp1,kpk)
      gy2=gl(kp3,kpk,kp2)*gr(kp4,kp1,kpk)-
     &   gr(kp3,kpk,kp2)*gl(kp4,kp1,kpk)

      if (kp3.eq.kgamma) then
        if (kp4.eq.kgamma) then
      aa(0,0,-1,-1)=aa(0,0,-1,-1)-(dsqrt(2.0d0)*(3.0d0*(e2*gp2*pmi-(
     . e3*gp2*pmi)-(emi*gp2*pp)+gm2*kk*pmi+gx2*mk*ppl)*wd(1,0,0)+2.0d0
     . *wd(2,0,0)*gm2*pmi*pp-(3.0d0*e2*emi*gm2)+3.0d0*e3*emi*gm2-(
     . 3.0d0*emi*gp2*kk)-(3.0d0*epl*gy2*mk)+gm2*pmi*pp)*du)/3.0d0
      aa(0,0,-1,1)=aa(0,0,-1,1)-(4.0d0*wd(2,0,-2)*du*gm2*pmi*pp)/
     . dsqrt(3.0d0)
      aa(0,0,1,-1)=aa(0,0,1,-1)-(4.0d0*wd(2,0,2)*du*gm2*pmi*pp)/dsqrt
     . (3.0d0)
      aa(0,0,1,1)=aa(0,0,1,1)+(dsqrt(2.0d0)*(3.0d0*(e2*gp2*pmi-(e3*gp2
     . *pmi)-(emi*gp2*pp)-(gm2*kk*pmi)+gx2*mk*ppl)*wd(1,0,0)-(2.0d0*wd
     . (2,0,0)*gm2*pmi*pp)+3.0d0*e2*emi*gm2-(3.0d0*e3*emi*gm2)-(3.0d0*
     . emi*gp2*kk)+3.0d0*epl*gy2*mk-(gm2*pmi*pp))*du)/3.0d0
      aa(1,-1,-1,-1)=aa(1,-1,-1,-1)+(dsqrt(2.0d0)*(dsqrt(3.0d0)*((e2-
     . e3)*(epl*gm2-(gp2*ppl))+emi*gy2*mk+epl*gp2*kk-(gm2*kk*ppl)-(gx2
     . *mk*pmi))*wd(1,-1,0)+(epl*gp2-(gm2*ppl))*wd(2,-1,0)*pp)*du)/
     . dsqrt(3.0d0)
      aa(1,-1,-1,1)=aa(1,-1,-1,1)+2.0d0*(epl*gp2-(gm2*ppl))*wd(2,-1,-2
     . )*du*pp
      aa(1,-1,1,-1)=aa(1,-1,1,-1)+2.0d0*(epl*gp2-(gm2*ppl))*wd(2,-1,2)
     . *du*pp
      aa(1,-1,1,1)=aa(1,-1,1,1)-(dsqrt(2.0d0)*(dsqrt(3.0d0)*((e2-e3)*
     . (epl*gm2-(gp2*ppl))+emi*gy2*mk-(epl*gp2*kk)+gm2*kk*ppl-(gx2*mk*
     . pmi))*wd(1,-1,0)-((epl*gp2-(gm2*ppl))*wd(2,-1,0)*pp))*du)/dsqrt
     . (3.0d0)
      aa(1,0,-1,-1)=aa(1,0,-1,-1)+(dsqrt(2.0d0)*(3.0d0*(e2*emi*gm2-(e3
     . *emi*gm2)+emi*gp2*kk+epl*gy2*mk-(gm2*pmi*pp))*wd(1,0,0)+2.0d0*
     . wd(2,0,0)*emi*gp2*pp-(3.0d0*e2*gp2*pmi)+3.0d0*e3*gp2*pmi+emi*
     . gp2*pp-(3.0d0*gm2*kk*pmi)-(3.0d0*gx2*mk*ppl))*du)/3.0d0
      aa(1,0,-1,1)=aa(1,0,-1,1)+(4.0d0*wd(2,0,-2)*du*emi*gp2*pp)/dsqrt
     . (3.0d0)
      aa(1,0,1,-1)=aa(1,0,1,-1)+(4.0d0*wd(2,0,2)*du*emi*gp2*pp)/dsqrt(
     . 3.0d0)
      aa(1,0,1,1)=aa(1,0,1,1)-(dsqrt(2.0d0)*(3.0d0*(e2*emi*gm2-(e3*
     . emi*gm2)-(emi*gp2*kk)+epl*gy2*mk-(gm2*pmi*pp))*wd(1,0,0)-(2.0d0
     . *wd(2,0,0)*emi*gp2*pp)+3.0d0*e2*gp2*pmi-(3.0d0*e3*gp2*pmi)-(emi
     . *gp2*pp)-(3.0d0*gm2*kk*pmi)+3.0d0*gx2*mk*ppl)*du)/3.0d0
      aa(1,1,-1,-1)=aa(1,1,-1,-1)+(dsqrt(2.0d0)*(dsqrt(3.0d0)*((e2-e3)
     . *(epl*gm2+gp2*ppl)+emi*gy2*mk+epl*gp2*kk+gm2*kk*ppl+gx2*mk*pmi)
     . *wd(1,1,0)+(epl*gp2+gm2*ppl)*wd(2,1,0)*pp)*du)/dsqrt(3.0d0)
      aa(1,1,-1,1)=aa(1,1,-1,1)+2.0d0*(epl*gp2+gm2*ppl)*wd(2,1,-2)*du*
     . pp
      aa(1,1,1,-1)=aa(1,1,1,-1)+2.0d0*(epl*gp2+gm2*ppl)*wd(2,1,2)*du*
     . pp
      aa(1,1,1,1)=aa(1,1,1,1)-(dsqrt(2.0d0)*(dsqrt(3.0d0)*((e2-e3)*(
     . epl*gm2+gp2*ppl)+emi*gy2*mk-(epl*gp2*kk)-(gm2*kk*ppl)+gx2*mk*
     . pmi)*wd(1,1,0)-((epl*gp2+gm2*ppl)*wd(2,1,0)*pp))*du)/dsqrt(
     . 3.0d0)

        else

      aa(0,0,-1,-1)=aa(0,0,-1,-1)-(dsqrt(2.0d0)*(3.0d0*(e2*gp2*pmi-(
     . e3*gp2*pmi)-(emi*gp2*pp)+gm2*kk*pmi+gx2*mk*ppl)*wd(1,0,0)+2.0d0
     . *wd(2,0,0)*gm2*pmi*pp-(3.0d0*e2*emi*gm2)+3.0d0*e3*emi*gm2-(
     . 3.0d0*emi*gp2*kk)-(3.0d0*epl*gy2*mk)+gm2*pmi*pp)*du)/3.0d0
      aa(0,0,-1,0)=aa(0,0,-1,0)-(dsqrt(2.0d0)*(dsqrt(3.0d0)*((e2-e3)*
     . (e4*gp2-(gm2*kk))*pmi-((emi*gp2*pp-(gm2*kk*pmi)-(gx2*mk*ppl))*
     . e4)-(emi*gm2*kk*pp)-(gp2*kk**2*pmi)+gy2*kk*mk*ppl)*wd(1,0,-1)+
     . 2.0d0*wd(2,0,-1)*e4*gm2*pmi*pp)*du)/(dsqrt(3.0d0)*mp4)
      aa(0,0,-1,1)=aa(0,0,-1,1)-(4.0d0*wd(2,0,-2)*du*gm2*pmi*pp)/
     . dsqrt(3.0d0)
      aa(0,0,1,-1)=aa(0,0,1,-1)-(4.0d0*wd(2,0,2)*du*gm2*pmi*pp)/dsqrt
     . (3.0d0)
      aa(0,0,1,0)=aa(0,0,1,0)+(dsqrt(2.0d0)*(dsqrt(3.0d0)*((e2-e3)*(e4
     . *gp2+gm2*kk)*pmi-((emi*gp2*pp+gm2*kk*pmi-(gx2*mk*ppl))*e4)+emi*
     . gm2*kk*pp-(gp2*kk**2*pmi)-(gy2*kk*mk*ppl))*wd(1,0,1)-(2.0d0*wd(
     . 2,0,1)*e4*gm2*pmi*pp))*du)/(dsqrt(3.0d0)*mp4)
      aa(0,0,1,1)=aa(0,0,1,1)+(dsqrt(2.0d0)*(3.0d0*(e2*gp2*pmi-(e3*gp2
     . *pmi)-(emi*gp2*pp)-(gm2*kk*pmi)+gx2*mk*ppl)*wd(1,0,0)-(2.0d0*wd
     . (2,0,0)*gm2*pmi*pp)+3.0d0*e2*emi*gm2-(3.0d0*e3*emi*gm2)-(3.0d0*
     . emi*gp2*kk)+3.0d0*epl*gy2*mk-(gm2*pmi*pp))*du)/3.0d0
      aa(1,-1,-1,-1)=aa(1,-1,-1,-1)+(dsqrt(2.0d0)*(dsqrt(3.0d0)*((e2-
     . e3)*(epl*gm2-(gp2*ppl))+emi*gy2*mk+epl*gp2*kk-(gm2*kk*ppl)-(gx2
     . *mk*pmi))*wd(1,-1,0)+(epl*gp2-(gm2*ppl))*wd(2,-1,0)*pp)*du)/
     . dsqrt(3.0d0)
      aa(1,-1,-1,0)=aa(1,-1,-1,0)+(dsqrt(2.0d0)*((((epl*gm2-(gp2*ppl))
     . *e4-(epl*gp2*kk)+gm2*kk*ppl)*(e2-e3)+(emi*gy2*mk+epl*gp2*kk-(
     . gm2*kk*ppl)-(gx2*mk*pmi))*e4-((epl*gm2-(gp2*ppl))*(kk+pp)*kk)+
     . emi*gx2*kk*mk-(gy2*kk*mk*pmi))*wd(1,-1,-1)+(epl*gp2-(gm2*ppl))*
     . wd(2,-1,-1)*e4*pp)*du)/mp4
      aa(1,-1,-1,1)=aa(1,-1,-1,1)+2.0d0*(epl*gp2-(gm2*ppl))*wd(2,-1,-2
     . )*du*pp
      aa(1,-1,1,-1)=aa(1,-1,1,-1)+2.0d0*(epl*gp2-(gm2*ppl))*wd(2,-1,2)
     . *du*pp
      aa(1,-1,1,0)=aa(1,-1,1,0)-(dsqrt(2.0d0)*((((epl*gm2-(gp2*ppl))*
     . e4+epl*gp2*kk-(gm2*kk*ppl))*(e2-e3)+(emi*gy2*mk-(epl*gp2*kk)+
     . gm2*kk*ppl-(gx2*mk*pmi))*e4-((epl*gm2-(gp2*ppl))*(kk-pp)*kk)-(
     . emi*gx2*kk*mk)+gy2*kk*mk*pmi)*wd(1,-1,1)-((epl*gp2-(gm2*ppl))*
     . wd(2,-1,1)*e4*pp))*du)/mp4
      aa(1,-1,1,1)=aa(1,-1,1,1)-(dsqrt(2.0d0)*(dsqrt(3.0d0)*((e2-e3)*
     . (epl*gm2-(gp2*ppl))+emi*gy2*mk-(epl*gp2*kk)+gm2*kk*ppl-(gx2*mk*
     . pmi))*wd(1,-1,0)-((epl*gp2-(gm2*ppl))*wd(2,-1,0)*pp))*du)/dsqrt
     . (3.0d0)
      aa(1,0,-1,-1)=aa(1,0,-1,-1)+(dsqrt(2.0d0)*(3.0d0*(e2*emi*gm2-(e3
     . *emi*gm2)+emi*gp2*kk+epl*gy2*mk-(gm2*pmi*pp))*wd(1,0,0)+2.0d0*
     . wd(2,0,0)*emi*gp2*pp-(3.0d0*e2*gp2*pmi)+3.0d0*e3*gp2*pmi+emi*
     . gp2*pp-(3.0d0*gm2*kk*pmi)-(3.0d0*gx2*mk*ppl))*du)/3.0d0
      aa(1,0,-1,0)=aa(1,0,-1,0)+(dsqrt(2.0d0)*(dsqrt(3.0d0)*((e2-e3)*(
     . e4*gm2-(gp2*kk))*emi+(emi*gp2*kk+epl*gy2*mk-(gm2*pmi*pp))*e4-(
     . emi*gm2*kk**2)+epl*gx2*kk*mk-(gp2*kk*pmi*pp))*wd(1,0,-1)+2.0d0*
     . wd(2,0,-1)*e4*emi*gp2*pp)*du)/(dsqrt(3.0d0)*mp4)
      aa(1,0,-1,1)=aa(1,0,-1,1)+(4.0d0*wd(2,0,-2)*du*emi*gp2*pp)/dsqrt
     . (3.0d0)
      aa(1,0,1,-1)=aa(1,0,1,-1)+(4.0d0*wd(2,0,2)*du*emi*gp2*pp)/dsqrt(
     . 3.0d0)
      aa(1,0,1,0)=aa(1,0,1,0)-(dsqrt(2.0d0)*(dsqrt(3.0d0)*((e2-e3)*(
     . e4*gm2+gp2*kk)*emi-((emi*gp2*kk-(epl*gy2*mk)+gm2*pmi*pp)*e4)-(
     . emi*gm2*kk**2)-(epl*gx2*kk*mk)+gp2*kk*pmi*pp)*wd(1,0,1)-(2.0d0*
     . wd(2,0,1)*e4*emi*gp2*pp))*du)/(dsqrt(3.0d0)*mp4)
      aa(1,0,1,1)=aa(1,0,1,1)-(dsqrt(2.0d0)*(3.0d0*(e2*emi*gm2-(e3*
     . emi*gm2)-(emi*gp2*kk)+epl*gy2*mk-(gm2*pmi*pp))*wd(1,0,0)-(2.0d0
     . *wd(2,0,0)*emi*gp2*pp)+3.0d0*e2*gp2*pmi-(3.0d0*e3*gp2*pmi)-(emi
     . *gp2*pp)-(3.0d0*gm2*kk*pmi)+3.0d0*gx2*mk*ppl)*du)/3.0d0
      aa(1,1,-1,-1)=aa(1,1,-1,-1)+(dsqrt(2.0d0)*(dsqrt(3.0d0)*((e2-e3)
     . *(epl*gm2+gp2*ppl)+emi*gy2*mk+epl*gp2*kk+gm2*kk*ppl+gx2*mk*pmi)
     . *wd(1,1,0)+(epl*gp2+gm2*ppl)*wd(2,1,0)*pp)*du)/dsqrt(3.0d0)
      aa(1,1,-1,0)=aa(1,1,-1,0)+(dsqrt(2.0d0)*((((epl*gm2+gp2*ppl)*e4-
     . (epl*gp2*kk)-(gm2*kk*ppl))*(e2-e3)+(emi*gy2*mk+epl*gp2*kk+gm2*
     . kk*ppl+gx2*mk*pmi)*e4-((epl*gm2+gp2*ppl)*(kk-pp)*kk)+emi*gx2*kk
     . *mk+gy2*kk*mk*pmi)*wd(1,1,-1)+(epl*gp2+gm2*ppl)*wd(2,1,-1)*e4*
     . pp)*du)/mp4
      aa(1,1,-1,1)=aa(1,1,-1,1)+2.0d0*(epl*gp2+gm2*ppl)*wd(2,1,-2)*du*
     . pp
      aa(1,1,1,-1)=aa(1,1,1,-1)+2.0d0*(epl*gp2+gm2*ppl)*wd(2,1,2)*du*
     . pp
      aa(1,1,1,0)=aa(1,1,1,0)-(dsqrt(2.0d0)*((((epl*gm2+gp2*ppl)*e4+
     . epl*gp2*kk+gm2*kk*ppl)*(e2-e3)+(emi*gy2*mk-(epl*gp2*kk)-(gm2*kk
     . *ppl)+gx2*mk*pmi)*e4-((epl*gm2+gp2*ppl)*(kk+pp)*kk)-(emi*gx2*kk
     . *mk)-(gy2*kk*mk*pmi))*wd(1,1,1)-((epl*gp2+gm2*ppl)*wd(2,1,1)*e4
     . *pp))*du)/mp4
      aa(1,1,1,1)=aa(1,1,1,1)-(dsqrt(2.0d0)*(dsqrt(3.0d0)*((e2-e3)*(
     . epl*gm2+gp2*ppl)+emi*gy2*mk-(epl*gp2*kk)-(gm2*kk*ppl)+gx2*mk*
     . pmi)*wd(1,1,0)-((epl*gp2+gm2*ppl)*wd(2,1,0)*pp))*du)/dsqrt(
     . 3.0d0)

        endif
      else
        if (kp4.eq.kgamma) then

      aa(0,0,-1,-1)=aa(0,0,-1,-1)-(dsqrt(2.0d0)*(3.0d0*(e2*gp2*pmi-(
     . e3*gp2*pmi)-(emi*gp2*pp)+gm2*kk*pmi+gx2*mk*ppl)*wd(1,0,0)+2.0d0
     . *wd(2,0,0)*gm2*pmi*pp-(3.0d0*e2*emi*gm2)+3.0d0*e3*emi*gm2-(
     . 3.0d0*emi*gp2*kk)-(3.0d0*epl*gy2*mk)+gm2*pmi*pp)*du)/3.0d0
      aa(0,0,-1,1)=aa(0,0,-1,1)-(4.0d0*wd(2,0,-2)*du*gm2*pmi*pp)/
     . dsqrt(3.0d0)
      aa(0,0,0,-1)=aa(0,0,0,-1)-(dsqrt(2.0d0)*(dsqrt(3.0d0)*((e3*gp2+
     . gm2*kk)*e2*pmi-((emi*gp2*pp-(gx2*mk*ppl))*e3)-(e3**2*gp2*pmi)+
     . emi*gm2*kk*pp+gp2*kk**2*pmi+gy2*kk*mk*ppl)*wd(1,0,1)+2.0d0*wd(2
     . ,0,1)*e3*gm2*pmi*pp)*du)/(dsqrt(3.0d0)*mp3)
      aa(0,0,0,1)=aa(0,0,0,1)+(dsqrt(2.0d0)*(dsqrt(3.0d0)*wd(1,0,-1)*
     . e2*e3*gp2*pmi-(dsqrt(3.0d0)*wd(1,0,-1)*e2*gm2*kk*pmi)-(dsqrt(
     . 3.0d0)*wd(1,0,-1)*e3**2*gp2*pmi)-(dsqrt(3.0d0)*wd(1,0,-1)*e3*
     . emi*gp2*pp)+dsqrt(3.0d0)*wd(1,0,-1)*e3*gx2*mk*ppl-(dsqrt(3.0d0)
     . *wd(1,0,-1)*emi*gm2*kk*pp)+dsqrt(3.0d0)*wd(1,0,-1)*gp2*kk**2*
     . pmi-(dsqrt(3.0d0)*wd(1,0,-1)*gy2*kk*mk*ppl)-(2.0d0*wd(2,0,-1)*
     . e3*gm2*pmi*pp))*du)/(dsqrt(3.0d0)*mp3)
      aa(0,0,1,-1)=aa(0,0,1,-1)-(4.0d0*wd(2,0,2)*du*gm2*pmi*pp)/dsqrt
     . (3.0d0)
      aa(0,0,1,1)=aa(0,0,1,1)+(dsqrt(2.0d0)*(3.0d0*(e2*gp2*pmi-(e3*gp2
     . *pmi)-(emi*gp2*pp)-(gm2*kk*pmi)+gx2*mk*ppl)*wd(1,0,0)-(2.0d0*wd
     . (2,0,0)*gm2*pmi*pp)+3.0d0*e2*emi*gm2-(3.0d0*e3*emi*gm2)-(3.0d0*
     . emi*gp2*kk)+3.0d0*epl*gy2*mk-(gm2*pmi*pp))*du)/3.0d0
      aa(1,-1,-1,-1)=aa(1,-1,-1,-1)+(dsqrt(2.0d0)*(dsqrt(3.0d0)*((e2-
     . e3)*(epl*gm2-(gp2*ppl))+emi*gy2*mk+epl*gp2*kk-(gm2*kk*ppl)-(gx2
     . *mk*pmi))*wd(1,-1,0)+(epl*gp2-(gm2*ppl))*wd(2,-1,0)*pp)*du)/
     . dsqrt(3.0d0)
      aa(1,-1,-1,1)=aa(1,-1,-1,1)+2.0d0*(epl*gp2-(gm2*ppl))*wd(2,-1,-2
     . )*du*pp
      aa(1,-1,0,-1)=aa(1,-1,0,-1)+(dsqrt(2.0d0)*((((epl*gm2-(gp2*ppl))
     . *e3+epl*gp2*kk-(gm2*kk*ppl))*e2+((kk-pp)*kk-e3**2)*(epl*gm2-(
     . gp2*ppl))+(emi*gy2-(gx2*pmi))*e3*mk+emi*gx2*kk*mk-(gy2*kk*mk*
     . pmi))*wd(1,-1,1)+(epl*gp2-(gm2*ppl))*wd(2,-1,1)*e3*pp)*du)/mp3
      aa(1,-1,0,1)=aa(1,-1,0,1)-(dsqrt(2.0d0)*((((epl*gm2-(gp2*ppl))*
     . e3-(epl*gp2*kk)+gm2*kk*ppl)*e2+((kk+pp)*kk-e3**2)*(epl*gm2-(gp2
     . *ppl))+(emi*gy2-(gx2*pmi))*e3*mk-(emi*gx2*kk*mk)+gy2*kk*mk*pmi)
     . *wd(1,-1,-1)-((epl*gp2-(gm2*ppl))*wd(2,-1,-1)*e3*pp))*du)/mp3
      aa(1,-1,1,-1)=aa(1,-1,1,-1)+2.0d0*(epl*gp2-(gm2*ppl))*wd(2,-1,2)
     . *du*pp
      aa(1,-1,1,1)=aa(1,-1,1,1)-(dsqrt(2.0d0)*(dsqrt(3.0d0)*((e2-e3)*
     . (epl*gm2-(gp2*ppl))+emi*gy2*mk-(epl*gp2*kk)+gm2*kk*ppl-(gx2*mk*
     . pmi))*wd(1,-1,0)-((epl*gp2-(gm2*ppl))*wd(2,-1,0)*pp))*du)/dsqrt
     . (3.0d0)
      aa(1,0,-1,-1)=aa(1,0,-1,-1)+(dsqrt(2.0d0)*(3.0d0*(e2*emi*gm2-(e3
     . *emi*gm2)+emi*gp2*kk+epl*gy2*mk-(gm2*pmi*pp))*wd(1,0,0)+2.0d0*
     . wd(2,0,0)*emi*gp2*pp-(3.0d0*e2*gp2*pmi)+3.0d0*e3*gp2*pmi+emi*
     . gp2*pp-(3.0d0*gm2*kk*pmi)-(3.0d0*gx2*mk*ppl))*du)/3.0d0
      aa(1,0,-1,1)=aa(1,0,-1,1)+(4.0d0*wd(2,0,-2)*du*emi*gp2*pp)/dsqrt
     . (3.0d0)
      aa(1,0,0,-1)=aa(1,0,0,-1)+(dsqrt(2.0d0)*(dsqrt(3.0d0)*((e3*gm2+
     . gp2*kk)*e2*emi+(epl*gy2*mk-(gm2*pmi*pp))*e3-(e3**2*emi*gm2)+emi
     . *gm2*kk**2+epl*gx2*kk*mk+gp2*kk*pmi*pp)*wd(1,0,1)+2.0d0*wd(2,0,
     . 1)*e3*emi*gp2*pp)*du)/(dsqrt(3.0d0)*mp3)
      aa(1,0,0,1)=aa(1,0,0,1)-(dsqrt(2.0d0)*(dsqrt(3.0d0)*wd(1,0,-1)*
     . e2*e3*emi*gm2-(dsqrt(3.0d0)*wd(1,0,-1)*e2*emi*gp2*kk)-(dsqrt(
     . 3.0d0)*wd(1,0,-1)*e3**2*emi*gm2)+dsqrt(3.0d0)*wd(1,0,-1)*e3*epl
     . *gy2*mk-(dsqrt(3.0d0)*wd(1,0,-1)*e3*gm2*pmi*pp)+dsqrt(3.0d0)*wd
     . (1,0,-1)*emi*gm2*kk**2-(dsqrt(3.0d0)*wd(1,0,-1)*epl*gx2*kk*mk)-
     . (dsqrt(3.0d0)*wd(1,0,-1)*gp2*kk*pmi*pp)-(2.0d0*wd(2,0,-1)*e3*
     . emi*gp2*pp))*du)/(dsqrt(3.0d0)*mp3)
      aa(1,0,1,-1)=aa(1,0,1,-1)+(4.0d0*wd(2,0,2)*du*emi*gp2*pp)/dsqrt(
     . 3.0d0)
      aa(1,0,1,1)=aa(1,0,1,1)-(dsqrt(2.0d0)*(3.0d0*(e2*emi*gm2-(e3*
     . emi*gm2)-(emi*gp2*kk)+epl*gy2*mk-(gm2*pmi*pp))*wd(1,0,0)-(2.0d0
     . *wd(2,0,0)*emi*gp2*pp)+3.0d0*e2*gp2*pmi-(3.0d0*e3*gp2*pmi)-(emi
     . *gp2*pp)-(3.0d0*gm2*kk*pmi)+3.0d0*gx2*mk*ppl)*du)/3.0d0
      aa(1,1,-1,-1)=aa(1,1,-1,-1)+(dsqrt(2.0d0)*(dsqrt(3.0d0)*((e2-e3)
     . *(epl*gm2+gp2*ppl)+emi*gy2*mk+epl*gp2*kk+gm2*kk*ppl+gx2*mk*pmi)
     . *wd(1,1,0)+(epl*gp2+gm2*ppl)*wd(2,1,0)*pp)*du)/dsqrt(3.0d0)
      aa(1,1,-1,1)=aa(1,1,-1,1)+2.0d0*(epl*gp2+gm2*ppl)*wd(2,1,-2)*du*
     . pp
      aa(1,1,0,-1)=aa(1,1,0,-1)+(dsqrt(2.0d0)*((((epl*gm2+gp2*ppl)*e3+
     . epl*gp2*kk+gm2*kk*ppl)*e2+((kk+pp)*kk-e3**2)*(epl*gm2+gp2*ppl)+
     . (emi*gy2+gx2*pmi)*e3*mk+emi*gx2*kk*mk+gy2*kk*mk*pmi)*wd(1,1,1)+
     . (epl*gp2+gm2*ppl)*wd(2,1,1)*e3*pp)*du)/mp3
      aa(1,1,0,1)=aa(1,1,0,1)-(dsqrt(2.0d0)*((((epl*gm2+gp2*ppl)*e3-(
     . epl*gp2*kk)-(gm2*kk*ppl))*e2+((kk-pp)*kk-e3**2)*(epl*gm2+gp2*
     . ppl)+(emi*gy2+gx2*pmi)*e3*mk-(emi*gx2*kk*mk)-(gy2*kk*mk*pmi))*
     . wd(1,1,-1)-((epl*gp2+gm2*ppl)*wd(2,1,-1)*e3*pp))*du)/mp3
      aa(1,1,1,-1)=aa(1,1,1,-1)+2.0d0*(epl*gp2+gm2*ppl)*wd(2,1,2)*du*
     . pp
      aa(1,1,1,1)=aa(1,1,1,1)-(dsqrt(2.0d0)*(dsqrt(3.0d0)*((e2-e3)*(
     . epl*gm2+gp2*ppl)+emi*gy2*mk-(epl*gp2*kk)-(gm2*kk*ppl)+gx2*mk*
     . pmi)*wd(1,1,0)-((epl*gp2+gm2*ppl)*wd(2,1,0)*pp))*du)/dsqrt(
     . 3.0d0)

        else

      aa(0,0,-1,-1)=aa(0,0,-1,-1)-(dsqrt(2.0d0)*(3.0d0*(e2*gp2*pmi-(
     . e3*gp2*pmi)-(emi*gp2*pp)+gm2*kk*pmi+gx2*mk*ppl)*wd(1,0,0)+2.0d0
     . *wd(2,0,0)*gm2*pmi*pp-(3.0d0*e2*emi*gm2)+3.0d0*e3*emi*gm2-(
     . 3.0d0*emi*gp2*kk)-(3.0d0*epl*gy2*mk)+gm2*pmi*pp)*du)/3.0d0
      aa(0,0,-1,0)=aa(0,0,-1,0)-(dsqrt(2.0d0)*(dsqrt(3.0d0)*((e2-e3)*
     . (e4*gp2-(gm2*kk))*pmi-((emi*gp2*pp-(gm2*kk*pmi)-(gx2*mk*ppl))*
     . e4)-(emi*gm2*kk*pp)-(gp2*kk**2*pmi)+gy2*kk*mk*ppl)*wd(1,0,-1)+
     . 2.0d0*wd(2,0,-1)*e4*gm2*pmi*pp)*du)/(dsqrt(3.0d0)*mp4)
      aa(0,0,-1,1)=aa(0,0,-1,1)-(4.0d0*wd(2,0,-2)*du*gm2*pmi*pp)/
     . dsqrt(3.0d0)
      aa(0,0,0,-1)=aa(0,0,0,-1)-(dsqrt(2.0d0)*(dsqrt(3.0d0)*((e3*gp2+
     . gm2*kk)*e2*pmi-((emi*gp2*pp-(gx2*mk*ppl))*e3)-(e3**2*gp2*pmi)+
     . emi*gm2*kk*pp+gp2*kk**2*pmi+gy2*kk*mk*ppl)*wd(1,0,1)+2.0d0*wd(2
     . ,0,1)*e3*gm2*pmi*pp)*du)/(dsqrt(3.0d0)*mp3)
      aa(0,0,0,0)=aa(0,0,0,0)+(dsqrt(2.0d0)*(3.0d0*((e3-e4)*e2*gm2*pmi
     . -((emi*gm2*pp+gy2*mk*ppl)*e4)+(emi*gm2*pp-(gy2*mk*ppl))*e3-(e3
     . **2*gm2*pmi)+gm2*kk**2*pmi)*wd(1,0,0)*kk-(3.0d0*(e3*e4-kk**2)*
     . e2*emi*gm2)-((3.0d0*epl*gy2*mk-(gm2*pmi*pp))*e3*e4)-(4.0d0*wd(2
     . ,0,0)*e3*e4*gm2*pmi*pp)+3.0d0*e3**2*e4*emi*gm2-(3.0d0*e4*emi*
     . gm2*kk**2)-(3.0d0*epl*gy2*kk**2*mk)+3.0d0*gm2*kk**2*pmi*pp)*du)
     . /(3.0d0*mp3*mp4)
      aa(0,0,0,1)=aa(0,0,0,1)+(dsqrt(2.0d0)*(dsqrt(3.0d0)*((e3*gp2-(
     . gm2*kk))*e2*pmi-((emi*gp2*pp-(gx2*mk*ppl))*e3)-(e3**2*gp2*pmi)-
     . (emi*gm2*kk*pp)+gp2*kk**2*pmi-(gy2*kk*mk*ppl))*wd(1,0,-1)-(
     . 2.0d0*wd(2,0,-1)*e3*gm2*pmi*pp))*du)/(dsqrt(3.0d0)*mp3)
      aa(0,0,1,-1)=aa(0,0,1,-1)-(4.0d0*wd(2,0,2)*du*gm2*pmi*pp)/dsqrt
     . (3.0d0)
      aa(0,0,1,0)=aa(0,0,1,0)+(dsqrt(2.0d0)*(dsqrt(3.0d0)*((e2-e3)*(e4
     . *gp2+gm2*kk)*pmi-((emi*gp2*pp+gm2*kk*pmi-(gx2*mk*ppl))*e4)+emi*
     . gm2*kk*pp-(gp2*kk**2*pmi)-(gy2*kk*mk*ppl))*wd(1,0,1)-(2.0d0*wd(
     . 2,0,1)*e4*gm2*pmi*pp))*du)/(dsqrt(3.0d0)*mp4)
      aa(0,0,1,1)=aa(0,0,1,1)+(dsqrt(2.0d0)*(3.0d0*(e2*gp2*pmi-(e3*gp2
     . *pmi)-(emi*gp2*pp)-(gm2*kk*pmi)+gx2*mk*ppl)*wd(1,0,0)-(2.0d0*wd
     . (2,0,0)*gm2*pmi*pp)+3.0d0*e2*emi*gm2-(3.0d0*e3*emi*gm2)-(3.0d0*
     . emi*gp2*kk)+3.0d0*epl*gy2*mk-(gm2*pmi*pp))*du)/3.0d0
      aa(1,-1,-1,-1)=aa(1,-1,-1,-1)+(dsqrt(2.0d0)*(dsqrt(3.0d0)*((e2-
     . e3)*(epl*gm2-(gp2*ppl))+emi*gy2*mk+epl*gp2*kk-(gm2*kk*ppl)-(gx2
     . *mk*pmi))*wd(1,-1,0)+(epl*gp2-(gm2*ppl))*wd(2,-1,0)*pp)*du)/
     . dsqrt(3.0d0)
      aa(1,-1,-1,0)=aa(1,-1,-1,0)+(dsqrt(2.0d0)*((((epl*gm2-(gp2*ppl))
     . *e4-(epl*gp2*kk)+gm2*kk*ppl)*(e2-e3)+(emi*gy2*mk+epl*gp2*kk-(
     . gm2*kk*ppl)-(gx2*mk*pmi))*e4-((epl*gm2-(gp2*ppl))*(kk+pp)*kk)+
     . emi*gx2*kk*mk-(gy2*kk*mk*pmi))*wd(1,-1,-1)+(epl*gp2-(gm2*ppl))*
     . wd(2,-1,-1)*e4*pp)*du)/mp4
      aa(1,-1,-1,1)=aa(1,-1,-1,1)+2.0d0*(epl*gp2-(gm2*ppl))*wd(2,-1,-2
     . )*du*pp
      aa(1,-1,0,-1)=aa(1,-1,0,-1)+(dsqrt(2.0d0)*((((epl*gm2-(gp2*ppl))
     . *e3+epl*gp2*kk-(gm2*kk*ppl))*e2+((kk-pp)*kk-e3**2)*(epl*gm2-(
     . gp2*ppl))+(emi*gy2-(gx2*pmi))*e3*mk+emi*gx2*kk*mk-(gy2*kk*mk*
     . pmi))*wd(1,-1,1)+(epl*gp2-(gm2*ppl))*wd(2,-1,1)*e3*pp)*du)/mp3
      aa(1,-1,0,0)=aa(1,-1,0,0)+(dsqrt(2.0d0)*(dsqrt(3.0d0)*((e3+e4)*(
     . emi*gx2*mk-(epl*gm2*pp)+gp2*pp*ppl-(gy2*mk*pmi))-((e3-e4)*(epl*
     . gp2-(gm2*ppl))*e2)+(epl*gp2-(gm2*ppl))*e3**2-(epl*gp2*kk**2)+
     . gm2*kk**2*ppl)*wd(1,-1,0)*kk+2.0d0*(epl*gp2-(gm2*ppl))*wd(2,-1,
     . 0)*e3*e4*pp)*du)/(dsqrt(3.0d0)*mp3*mp4)
      aa(1,-1,0,1)=aa(1,-1,0,1)-(dsqrt(2.0d0)*((((epl*gm2-(gp2*ppl))*
     . e3-(epl*gp2*kk)+gm2*kk*ppl)*e2+((kk+pp)*kk-e3**2)*(epl*gm2-(gp2
     . *ppl))+(emi*gy2-(gx2*pmi))*e3*mk-(emi*gx2*kk*mk)+gy2*kk*mk*pmi)
     . *wd(1,-1,-1)-((epl*gp2-(gm2*ppl))*wd(2,-1,-1)*e3*pp))*du)/mp3
      aa(1,-1,1,-1)=aa(1,-1,1,-1)+2.0d0*(epl*gp2-(gm2*ppl))*wd(2,-1,2)
     . *du*pp
      aa(1,-1,1,0)=aa(1,-1,1,0)-(dsqrt(2.0d0)*((((epl*gm2-(gp2*ppl))*
     . e4+epl*gp2*kk-(gm2*kk*ppl))*(e2-e3)+(emi*gy2*mk-(epl*gp2*kk)+
     . gm2*kk*ppl-(gx2*mk*pmi))*e4-((epl*gm2-(gp2*ppl))*(kk-pp)*kk)-(
     . emi*gx2*kk*mk)+gy2*kk*mk*pmi)*wd(1,-1,1)-((epl*gp2-(gm2*ppl))*
     . wd(2,-1,1)*e4*pp))*du)/mp4
      aa(1,-1,1,1)=aa(1,-1,1,1)-(dsqrt(2.0d0)*(dsqrt(3.0d0)*((e2-e3)*
     . (epl*gm2-(gp2*ppl))+emi*gy2*mk-(epl*gp2*kk)+gm2*kk*ppl-(gx2*mk*
     . pmi))*wd(1,-1,0)-((epl*gp2-(gm2*ppl))*wd(2,-1,0)*pp))*du)/dsqrt
     . (3.0d0)
      aa(1,0,-1,-1)=aa(1,0,-1,-1)+(dsqrt(2.0d0)*(3.0d0*(e2*emi*gm2-(e3
     . *emi*gm2)+emi*gp2*kk+epl*gy2*mk-(gm2*pmi*pp))*wd(1,0,0)+2.0d0*
     . wd(2,0,0)*emi*gp2*pp-(3.0d0*e2*gp2*pmi)+3.0d0*e3*gp2*pmi+emi*
     . gp2*pp-(3.0d0*gm2*kk*pmi)-(3.0d0*gx2*mk*ppl))*du)/3.0d0
      aa(1,0,-1,0)=aa(1,0,-1,0)+(dsqrt(2.0d0)*(dsqrt(3.0d0)*((e2-e3)*(
     . e4*gm2-(gp2*kk))*emi+(emi*gp2*kk+epl*gy2*mk-(gm2*pmi*pp))*e4-(
     . emi*gm2*kk**2)+epl*gx2*kk*mk-(gp2*kk*pmi*pp))*wd(1,0,-1)+2.0d0*
     . wd(2,0,-1)*e4*emi*gp2*pp)*du)/(dsqrt(3.0d0)*mp4)
      aa(1,0,-1,1)=aa(1,0,-1,1)+(4.0d0*wd(2,0,-2)*du*emi*gp2*pp)/dsqrt
     . (3.0d0)
      aa(1,0,0,-1)=aa(1,0,0,-1)+(dsqrt(2.0d0)*(dsqrt(3.0d0)*((e3*gm2+
     . gp2*kk)*e2*emi+(epl*gy2*mk-(gm2*pmi*pp))*e3-(e3**2*emi*gm2)+emi
     . *gm2*kk**2+epl*gx2*kk*mk+gp2*kk*pmi*pp)*wd(1,0,1)+2.0d0*wd(2,0,
     . 1)*e3*emi*gp2*pp)*du)/(dsqrt(3.0d0)*mp3)
      aa(1,0,0,0)=aa(1,0,0,0)-(dsqrt(2.0d0)*(3.0d0*((e3-e4)*e2*emi*
     . gp2-((epl*gx2*mk+gp2*pmi*pp)*e4)-((epl*gx2*mk-(gp2*pmi*pp))*e3)
     . -(e3**2*emi*gp2)+emi*gp2*kk**2)*wd(1,0,0)*kk-(3.0d0*(e3*e4-kk**
     . 2)*e2*gp2*pmi)+(emi*gp2*pp-(3.0d0*gx2*mk*ppl))*e3*e4-(4.0d0*wd(
     . 2,0,0)*e3*e4*emi*gp2*pp)+3.0d0*e3**2*e4*gp2*pmi-(3.0d0*e4*gp2*
     . kk**2*pmi)+3.0d0*emi*gp2*kk**2*pp-(3.0d0*gx2*kk**2*mk*ppl))*du)
     . /(3.0d0*mp3*mp4)
      aa(1,0,0,1)=aa(1,0,0,1)-(dsqrt(2.0d0)*(dsqrt(3.0d0)*((e3*gm2-(
     . gp2*kk))*e2*emi+(epl*gy2*mk-(gm2*pmi*pp))*e3-(e3**2*emi*gm2)+
     . emi*gm2*kk**2-(epl*gx2*kk*mk)-(gp2*kk*pmi*pp))*wd(1,0,-1)-(
     . 2.0d0*wd(2,0,-1)*e3*emi*gp2*pp))*du)/(dsqrt(3.0d0)*mp3)
      aa(1,0,1,-1)=aa(1,0,1,-1)+(4.0d0*wd(2,0,2)*du*emi*gp2*pp)/dsqrt(
     . 3.0d0)
      aa(1,0,1,0)=aa(1,0,1,0)-(dsqrt(2.0d0)*(dsqrt(3.0d0)*((e2-e3)*(
     . e4*gm2+gp2*kk)*emi-((emi*gp2*kk-(epl*gy2*mk)+gm2*pmi*pp)*e4)-(
     . emi*gm2*kk**2)-(epl*gx2*kk*mk)+gp2*kk*pmi*pp)*wd(1,0,1)-(2.0d0*
     . wd(2,0,1)*e4*emi*gp2*pp))*du)/(dsqrt(3.0d0)*mp4)
      aa(1,0,1,1)=aa(1,0,1,1)-(dsqrt(2.0d0)*(3.0d0*(e2*emi*gm2-(e3*
     . emi*gm2)-(emi*gp2*kk)+epl*gy2*mk-(gm2*pmi*pp))*wd(1,0,0)-(2.0d0
     . *wd(2,0,0)*emi*gp2*pp)+3.0d0*e2*gp2*pmi-(3.0d0*e3*gp2*pmi)-(emi
     . *gp2*pp)-(3.0d0*gm2*kk*pmi)+3.0d0*gx2*mk*ppl)*du)/3.0d0
      aa(1,1,-1,-1)=aa(1,1,-1,-1)+(dsqrt(2.0d0)*(dsqrt(3.0d0)*((e2-e3)
     . *(epl*gm2+gp2*ppl)+emi*gy2*mk+epl*gp2*kk+gm2*kk*ppl+gx2*mk*pmi)
     . *wd(1,1,0)+(epl*gp2+gm2*ppl)*wd(2,1,0)*pp)*du)/dsqrt(3.0d0)
      aa(1,1,-1,0)=aa(1,1,-1,0)+(dsqrt(2.0d0)*((((epl*gm2+gp2*ppl)*e4-
     . (epl*gp2*kk)-(gm2*kk*ppl))*(e2-e3)+(emi*gy2*mk+epl*gp2*kk+gm2*
     . kk*ppl+gx2*mk*pmi)*e4-((epl*gm2+gp2*ppl)*(kk-pp)*kk)+emi*gx2*kk
     . *mk+gy2*kk*mk*pmi)*wd(1,1,-1)+(epl*gp2+gm2*ppl)*wd(2,1,-1)*e4*
     . pp)*du)/mp4
      aa(1,1,-1,1)=aa(1,1,-1,1)+2.0d0*(epl*gp2+gm2*ppl)*wd(2,1,-2)*du*
     . pp
      aa(1,1,0,-1)=aa(1,1,0,-1)+(dsqrt(2.0d0)*((((epl*gm2+gp2*ppl)*e3+
     . epl*gp2*kk+gm2*kk*ppl)*e2+((kk+pp)*kk-e3**2)*(epl*gm2+gp2*ppl)+
     . (emi*gy2+gx2*pmi)*e3*mk+emi*gx2*kk*mk+gy2*kk*mk*pmi)*wd(1,1,1)+
     . (epl*gp2+gm2*ppl)*wd(2,1,1)*e3*pp)*du)/mp3
      aa(1,1,0,0)=aa(1,1,0,0)+(dsqrt(2.0d0)*(dsqrt(3.0d0)*((e3+e4)*(
     . emi*gx2*mk+epl*gm2*pp+gp2*pp*ppl+gy2*mk*pmi)-((e3-e4)*(epl*gp2+
     . gm2*ppl)*e2)+(epl*gp2+gm2*ppl)*e3**2-(epl*gp2*kk**2)-(gm2*kk**2
     . *ppl))*wd(1,1,0)*kk+2.0d0*(epl*gp2+gm2*ppl)*wd(2,1,0)*e3*e4*pp)
     . *du)/(dsqrt(3.0d0)*mp3*mp4)
      aa(1,1,0,1)=aa(1,1,0,1)-(dsqrt(2.0d0)*((((epl*gm2+gp2*ppl)*e3-(
     . epl*gp2*kk)-(gm2*kk*ppl))*e2+((kk-pp)*kk-e3**2)*(epl*gm2+gp2*
     . ppl)+(emi*gy2+gx2*pmi)*e3*mk-(emi*gx2*kk*mk)-(gy2*kk*mk*pmi))*
     . wd(1,1,-1)-((epl*gp2+gm2*ppl)*wd(2,1,-1)*e3*pp))*du)/mp3
      aa(1,1,1,-1)=aa(1,1,1,-1)+2.0d0*(epl*gp2+gm2*ppl)*wd(2,1,2)*du*
     . pp
      aa(1,1,1,0)=aa(1,1,1,0)-(dsqrt(2.0d0)*((((epl*gm2+gp2*ppl)*e4+
     . epl*gp2*kk+gm2*kk*ppl)*(e2-e3)+(emi*gy2*mk-(epl*gp2*kk)-(gm2*kk
     . *ppl)+gx2*mk*pmi)*e4-((epl*gm2+gp2*ppl)*(kk+pp)*kk)-(emi*gx2*kk
     . *mk)-(gy2*kk*mk*pmi))*wd(1,1,1)-((epl*gp2+gm2*ppl)*wd(2,1,1)*e4
     . *pp))*du)/mp4
      aa(1,1,1,1)=aa(1,1,1,1)-(dsqrt(2.0d0)*(dsqrt(3.0d0)*((e2-e3)*(
     . epl*gm2+gp2*ppl)+emi*gy2*mk-(epl*gp2*kk)-(gm2*kk*ppl)+gx2*mk*
     . pmi)*wd(1,1,0)-((epl*gp2+gm2*ppl)*wd(2,1,0)*pp))*du)/dsqrt(
     . 3.0d0)

        endif
      endif

      return

      end
